### PR TITLE
sync: release 0.10.5

### PR DESCRIPTION
**Pull request by therealbobo**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area API-version

> /area build

> /area CI

> /area driver-kmod

> /area driver-bpf

> /area driver-modern-bpf

> /area libscap-engine-bpf

> /area libscap-engine-gvisor

> /area libscap-engine-kmod

> /area libscap-engine-modern-bpf

> /area libscap-engine-nodriver

> /area libscap-engine-noop

> /area libscap-engine-source-plugin

> /area libscap-engine-savefile

> /area libscap-engine-udig

> /area libscap

> /area libpman

/area libsinsp

> /area tests

> /area proposals

**Does this PR require a change in the driver versions?**

> /version driver-API-version-major

> /version driver-API-version-minor

> /version driver-API-version-patch

> /version driver-SCHEMA-version-major

> /version driver-SCHEMA-version-minor

> /version driver-SCHEMA-version-patch

**What this PR does / why we need it**:

Cherrypicks PR #958 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by FedeDP** [comment]
Please write in the OP which commits this cherry picks from master. Moreover, we should properly add both this and the other PR to the 0.10.5 milestone.

/milestone 0.10.5

**Comment by FedeDP** [comment]
> Moreover, we should properly add both this and the other PR to the 0.10.5 milestone.

Done :)
Thanks for this PR btw!

**Review by Andreagit97 — APPROVED** [review]
/approve

**Comment by therealbobo** [comment]
@LucaGuerra I fixed the description! 😄

**Review by LucaGuerra — APPROVED** [review]

**Comment by LucaGuerra** [comment]
/hold

@therealbobo is just running a bit of extra testing

**Pull request merged**
