### PR TITLE
new(userspace/libsinsp): add a `num-events` cmd line option to `sinsp-example`

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind feature

**Any specific area of the project related to this PR?**

/area libsinsp

**Does this PR require a change in the driver versions?**

**What this PR does / why we need it**:

Moreover, print some perf info at the end of the program and updated docs.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by FedeDP** [comment]
New output example:
```
-- Stop capture
Retrieved events: 1000000
Time spent: 1469ms
Events/ms: 680.735
```

**Review by Andreagit97 — APPROVED** [review]
/approve

**Pull request merged**
