### PR TITLE
fix(libscap): bump minimum schema version to 2.0.0

### PR DESCRIPTION
**Pull request by Molter73**
**What type of PR is this?**

/kind bug

**Any specific area of the project related to this PR?**

/area libscap

**What this PR does / why we need it**:

This PR superseds #443.

The minimum schema version in the libscap needs to be bumped in order for it to be compatible with the bump to `2.0.0` in the drivers.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by FedeDP — APPROVED** [review]
/approve

**Review by jasondellaluce — COMMENTED** [review]
LGTM!

**Review by Andreagit97 — APPROVED** [review]
/approve

**Pull request merged**
