### PR TITLE
cleanup(userspace): remove unused API

### PR DESCRIPTION
**Pull request by Andreagit97**
**What type of PR is this?**

/kind cleanup

**Any specific area of the project related to this PR?**

/area libsinsp

**Does this PR require a change in the driver versions?**

No

**What this PR does / why we need it**:

These APIs were DEPRECATED and now are no more used so we should remove them :)

```c
void list_events(sinsp* inspector, bool markdown=false);
void list_fields(bool verbose, bool markdown=false);
void sinsp::set_cri_delay(uint64_t);
inline ppm_event_category get_info_category() const;
```

Moreover there were some old helpers used in the old modern bpf testing framework

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by FedeDP — DISMISSED** [review]
/approve

**Review by jasondellaluce — DISMISSED** [review]

**Comment by Andreagit97** [comment]
I will add other possible unused APIs here :)

**Review by FedeDP — APPROVED** [review]
/approve

I love little cleanups!

**Review by jasondellaluce — APPROVED** [review]

**Pull request merged**
