### PR TITLE
refactor(userspace/libsinsp)!: remove `friend` classes, `VISIBILITY_PRIVATE`, and `VISIBILITY_PROTECTED`

### PR DESCRIPTION
**Pull request by jasondellaluce**
**What type of PR is this?**

/kind cleanup

**Any specific area of the project related to this PR?**

/area libsinsp

/area tests

**Does this PR require a change in the driver versions?**

**What this PR does / why we need it**:

In the process of making our APIs clear and stable, I've been hunting for all the single points in which we violate the basic OOP principles of information hiding. We have 2 main ways by which this happens: `friend` classes (thanks C++) and the `VISIBILITY_*` macros, by which visibility restrictions of classes can entirely be violated.

In this contribution I entirely removed `VISIBILITY_*` and reduced `friend` classes to the bare minimum (only to their legitimate use cases). Although the diff seems big, the changes are very pragmatic. First, I proceeded by putting all the class members and methods that used to be illegally accessed as private, and then I introduced getter and setters wherever applicable so that they could be safely accessed. This all happens in the first commit. Then, the second commit just refactors libsinsp and its tests to use the new accessors instead of doing direct class member access. All the accessors have been inlined so that it makes no difference compared to now at compile-time.

It's worth mentioning that I just focused on the things that were illegally accessed, and I didn't add accessors for anything else. The content of this PR, and all the class members/methods involved, is just the minimum set of changes required in order to remove `friends`s and `VISIBILITY_*`. If this pattern will be liked, we'll consider adding accessors for other things in the future.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

This is a potential breaking change for some adopters which relied on the unsafe class member access. The migration path is provided in all cases through the new accessor methods.

**Does this PR introduce a user-facing change?**:

```release-note
refactor(userspace/libsinsp)!: remove `friend` classes, `VISIBILITY_PRIVATE`, and `VISIBILITY_PROTECTED`
```

### CODE REVIEW

**Comment by FedeDP** [comment]
Astonishing job, as always @jasondellaluce !
While there are multiple breaking changes, i think this is a HUGE step forward in the formalization of libs external APIs and a much needed cleanup.
I am all for it, thanks for taking care of doing this!

**Review by FedeDP — APPROVED** [review]
/approve

**Review by Andreagit97 — APPROVED** [review]
/approve

**Pull request merged**
