### PR TITLE
fix(driver): fixed build against linux v6.7-rc4.

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind bug

**Any specific area of the project related to this PR?**

/area driver-kmod
/area driver-bpf
/area driver-modern-bpf

**Does this PR require a change in the driver versions?**

/version driver-API-version-patch

**What this PR does / why we need it**:

Fixes drivers build against linux v6.7-rc4+.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
fix(driver): fixed build against linux 6.7
```

### CODE REVIEW

**Comment by FedeDP** [comment]
I was able to locally build drivers.
The CI driverkit job is failig weirdly: https://github.com/falcosecurity/libs/actions/runs/7178620051.
I can repro it locally and am trying to understand what's happening.

**Comment by FedeDP** [comment]
Bumped api version patch.
/unhold

**Comment by FedeDP** [comment]
/milestone next-driver

I think we should merge this for the next-driver milestone otherwise Falco 0.37 will ship a driver that won't run on kernel 6.7 that is going to be released in 2-3 weeks (ie: before the Falco release...).

**Comment by FedeDP** [comment]
Need to rebase once #1567 is in.

**Comment by FedeDP** [comment]
Driverkit is now fixed: https://github.com/falcosecurity/driverkit/pull/310
And a new patch release is coming: https://github.com/falcosecurity/driverkit/releases/tag/v0.16.2

**Comment by FedeDP** [comment]
Rebased on top of master.

**Comment by FedeDP** [comment]
CI is now passing against this branch (after the new driverkit patch release): https://github.com/falcosecurity/libs/actions/runs/7184655332/job/19566212831

**Review by incertum — DISMISSED** [review]
/approve

Thanks @FedeDP :rocket: !

**Comment by FedeDP** [comment]
@alexellis do you know what can we do to install correct headers?
We need headers to build and test our kernel drivers, but CI is failing with:
> E: Unable to locate package linux-headers-5.10.201
> E: Couldn't find any package by glob 'linux-headers-5.10.201'

This is the same error we have in https://github.com/falcosecurity/falco/pull/2961 too.

**Comment by FedeDP** [comment]
Tested latest mainline kernel build against this branch: https://github.com/falcosecurity/libs/actions/runs/7247366053/job/19741136375 :green_circle:  (6.7-rc6).

**Review by Andreagit97 — APPROVED** [review]
/approve

**Review by leogr — APPROVED** [review]

**Review by Andreagit97 — APPROVED** [review]
/approve

**Pull request merged**
