### PR TITLE
docs(release-process): update diagram according to the doc

### PR DESCRIPTION
**Pull request by leogr**
Signed-off-by: Leonardo Grasso <me@leonardograsso.com>

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

/kind cleanup

> /kind design

/kind documentation

> /kind failing-test

> /kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area API-version

> /area build

> /area CI

> /area driver-kmod

> /area driver-bpf

> /area driver-modern-bpf

> /area libscap-engine-bpf

> /area libscap-engine-gvisor

> /area libscap-engine-kmod

> /area libscap-engine-modern-bpf

> /area libscap-engine-nodriver

> /area libscap-engine-noop

> /area libscap-engine-source-plugin

> /area libscap-engine-savefile

> /area libscap-engine-udig

> /area libscap

> /area libpman

> /area libsinsp

> /area tests

> /area proposals

**Does this PR require a change in the driver versions?**

> /version driver-API-version-major

> /version driver-API-version-minor

> /version driver-API-version-patch

> /version driver-SCHEMA-version-major

> /version driver-SCHEMA-version-minor

> /version driver-SCHEMA-version-patch

**What this PR does / why we need it**:

Follow-up #821

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

/cc @FedeDP 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by FedeDP — DISMISSED** [review]
/approve

**Review by Molter73 — COMMENTED** [review]
Could we also update the tag names? I have no idea how this image was created 🤣

**Comment by leogr** [comment]
> Could we also update the tag names? I have no idea how this image was created rofl

Which ones? I probably miss that :D 

N.B. SVG is basically XML, one can edit them directly into the SVG source code (that's what I did :sweat_smile: )

**Comment by Molter73** [comment]
I was referring to the tags `x.y.z-rc1`, `x.y.z`, we can probably use `M.m.0-rc1`, `M.m.0` and so on for consistency.

**Comment by leogr** [comment]
> I was referring to the tags `x.y.z-rc1`, `x.y.z`, we can probably use `M.m.0-rc1`, `M.m.0` and so on for consistency.

@Molter73 
You are right! I don't know why, but my mind ignored them. Fixing. Thank you! :)

**Review by FedeDP — APPROVED** [review]
/approve
Beautiful!

**Review by Molter73 — APPROVED** [review]
/lgtm

**Pull request merged**
