### PR TITLE
refactor(userspace/libsinsp): remove old meta events implementation

### PR DESCRIPTION
**Pull request by jasondellaluce**
**What type of PR is this?**

/kind cleanup

**Any specific area of the project related to this PR?**

/area libsinsp

**Does this PR require a change in the driver versions?**

**What this PR does / why we need it**:

This PR aims to ultimately have only one way in the inspector for injecting asynchronous meta-events. The only piece remaining using the old approach was the generator of internal PROCINFO events. This has now been ported to the async event queue approach.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by FedeDP — APPROVED** [review]
/approve

**Comment by FedeDP** [comment]
Thank you very much for the cleanup @jasondellaluce !!

**Review by Andreagit97 — APPROVED** [review]
/approve

**Review by FedeDP — APPROVED** [review]
/approve

**Review by leogr — APPROVED** [review]

**Pull request merged**
