### PR TITLE
refactor(libsinsp): remove some unused API

### PR DESCRIPTION
**Pull request by Andreagit97**
Signed-off-by: Andrea Terzolo andrea.terzolo@polito.it

**What type of PR is this?**

/kind cleanup

**Any specific area of the project related to this PR?**

/area libsinsp

**What this PR does / why we need it**:

This PR removes some unused stuff:

1. `add_evttype_filter` API.
2. `m_evttype_filter` member. 
3. `sinsp_evttype_filter` class.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

### CODE REVIEW

**Comment by FedeDP** [comment]
Thank you man, we needed some spring cleaning!

**Review by FedeDP — APPROVED** [review]
/approve

CI builds went fine!

**Review by leogr — APPROVED** [review]
:heart_eyes: 

:wastebasket: :broom:

**Pull request merged**
