### PR TITLE
Extract cached populate values

### PR DESCRIPTION
**Pull request by mstemm**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

> /area driver-kmod

> /area driver-ebpf

> /area libscap

/area libsinsp

> /area tests

> /area proposals

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by FedeDP** [comment]
Hi Mark! Is this PR starting from the #336 branch? I see similar changes. Can you open it from master instead? 
Thank you!

**Comment by mstemm** [comment]
> Hi Mark! Is this PR starting from the #336 branch? I see similar changes. Can you open it from master instead? Thank you!

Yes sorry, I picked the wrong base branch. I rebased it.

**Review by leogr — APPROVED** [review]
Great catch! Thank you :)

/approve

**Review by Andreagit97 — APPROVED** [review]
/approve

**Pull request merged**
