### PR TITLE
new(userspace/libsinsp): expose threadinfo `category` to state table API

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind cleanup

**Any specific area of the project related to this PR?**

/area libsinsp

**Does this PR require a change in the driver versions?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by Andreagit97 — APPROVED** [review]
/approve

**Comment by FedeDP** [comment]
/close

As per https://github.com/falcosecurity/libs/pull/2167#issuecomment-2503412340 comment, we don't need this; the container plugin will be responsible to attach the `category` foreign key to threadinfo, fill it and extract those 3 fields.

**Pull request closed without merging**
