### PR TITLE
Makefile for scap_open test

### PR DESCRIPTION
**Pull request by liorzemah**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area libscap

/area tests

**What this PR does / why we need it**:

Add another ability to build scap_open test via makefile

**Which issue(s) this PR fixes**:

https://github.com/falcosecurity/libs/issues/482

Fixes #

**Special notes for your reviewer**:

First of all need to build scap libraries (using existing cmake) and then you can to build scap_open test by using the makefile instead of CMakeList.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by Andreagit97** [comment]
Thank you for this @liorzemah!! The [DCO](https://cert-manager.io/docs/contributing/sign-off/) is missing, you need to merge the PR, if you have problems in doing this feel free to ask :)

**Comment by liorzemah** [comment]
@Andreagit97 I added the DCO

**Comment by Andreagit97** [comment]
Nice, thank you @liorzemah! It LGTM! It would be amazing if you could add just 2 lines in the [scap-open `README.md`](https://github.com/falcosecurity/libs/tree/master/userspace/libscap/examples/01-open#build-%EF%B8%8F)  (maybe in a new dedicated section `Build with Makefile`) in which you explain the necessary steps to use this makefile cloning the `libs` repository from scratch. In this way also other folks would benefit from this amazing contribution. WDYT @FedeDP @Molter73 @liorzemah?

**Comment by liorzemah** [comment]
@Andreagit97 I updated scap_open README

**Review by leogr — APPROVED** [review]
nice :+1:

**Comment by FedeDP** [comment]
/hold

Pr #546 adds support for pkg-config files. I think this PR will be useless once we properly install pkg-config scripts.

**Pull request closed without merging**
