### PR TITLE
update(ci): use cncf provided runners for arm64

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind cleanup

**Any specific area of the project related to this PR?**

/area CI

**Does this PR require a change in the driver versions?**

**What this PR does / why we need it**:

Depends upon #2073 and #2049 that were partially split from this one.
Will eventually rebase once they get merged.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by FedeDP** [comment]
Drivers CI is green: https://github.com/falcosecurity/libs/actions/runs/10848223544/job/30104926169?pr=2064

Going to remove the `wip` commit that triggered it.

**Comment by FedeDP** [comment]
Since this may take a bit longer to wrap up, i extracted https://github.com/falcosecurity/libs/pull/2066 to fix drivers CI in the meantime.

**Comment by FedeDP** [comment]
Rebased on top of latest master.

**Comment by FedeDP** [comment]
Rebased on top of latest master.

**Comment by FedeDP** [comment]
Will rebase this one once https://github.com/falcosecurity/libs/pull/2120 is merged, taking care of porting `latest-kernel` ci job to use cncf provided arm64 runner.

**Comment by FedeDP** [comment]
Rebased.

**Review by leogr — APPROVED** [review]

**Review by LucaGuerra — APPROVED** [review]

**Pull request merged**
