### PR TITLE
fix(userspace/libsinsp): properly include <memory> in libsinsp token_bucket unit test

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

> /area driver-kmod

> /area driver-ebpf

> /area libscap

> /area libsinsp

/area tests

> /area proposals

**What this PR does / why we need it**:

This fixes build in debian 10 for example.  
Discovered while testing https://github.com/falcosecurity/test-infra/pull/636.  
It seems like make_shared actually needs this include, otherwise failing with:
> error: 'make_shared' is not a member of 'std'

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by leogr — APPROVED** [review]
/approve

**Comment by FedeDP** [comment]
I'd wait for https://github.com/falcosecurity/test-infra/pull/636 to be merged, and then try a retest for build-libs!

**Review by gnosek — APPROVED** [review]

**Pull request merged**
