### PR TITLE
fix(driver/bpf): fixed a typo in old ebpf probe code for linux >= 6.11.

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind bug

**Any specific area of the project related to this PR?**

/area driver-bpf

**Does this PR require a change in the driver versions?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by FedeDP** [comment]
/hold
will port the latest-kernel CI to test against arm64 too.

**Review by leogr — APPROVED** [review]

**Comment by FedeDP** [comment]
@leogr still working to improve the CI.
/hold

**Review by Molter73 — APPROVED** [review]
/approve

**Comment by FedeDP** [comment]
Ok i expanded the latest-kernel CI to test the build on arm64 too: https://github.com/falcosecurity/libs/actions/runs/11363216135/job/31606690972

/unhold

**Review by leogr — APPROVED** [review]

**Review by jasondellaluce — APPROVED** [review]

**Pull request merged**
