### PR TITLE
update(libsinsp): Add sinsp_evt::set_num

### PR DESCRIPTION
**Pull request by geraldcombs**
Event extraction can be cached based on the event number. Add a setter so that externally constructed events can be cached correctly.

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

/kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area API-version

> /area build

> /area CI

> /area driver-kmod

> /area driver-bpf

> /area driver-modern-bpf

> /area libscap-engine-bpf

> /area libscap-engine-gvisor

> /area libscap-engine-kmod

> /area libscap-engine-modern-bpf

> /area libscap-engine-nodriver

> /area libscap-engine-noop

> /area libscap-engine-source-plugin

> /area libscap-engine-savefile

> /area libscap

> /area libpman

/area libsinsp

> /area tests

> /area proposals

**Does this PR require a change in the driver versions?**

> /version driver-API-version-major

> /version driver-API-version-minor

> /version driver-API-version-patch

> /version driver-SCHEMA-version-major

> /version driver-SCHEMA-version-minor

> /version driver-SCHEMA-version-patch

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by incertum — COMMENTED** [review]
Just adding the function without using it?

**Comment by geraldcombs** [comment]
> Just adding the function without using it?

Correct. I'm using it externally in a [Falco dissector for Wireshark](https://gitlab.com/wireshark/wireshark/-/tree/master/plugins/epan/falco_bridge) and for that particular use case, plugin extraction returns the same cached extraction fields unless I set the event number.

**Review by incertum — APPROVED** [review]
/approve

/milestone 0.14.0

**Review by Andreagit97 — APPROVED** [review]
/approve

**Pull request merged**
