### PR TITLE
chore: downgrade flushing log messages to debug

### PR DESCRIPTION
**Pull request by Stringy**
**What type of PR is this?**

/kind cleanup

**Any specific area of the project related to this PR?**

/area libsinsp

**Does this PR require a change in the driver versions?**

N/A

**What this PR does / why we need it**:

We've found that the "Flushing..." log messages appear very frequently in the logs, but don't provide much information in themselves. I've downgraded the messages to SEV_DEBUG to clean up the logs a little.

**Which issue(s) this PR fixes**:

N/A

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

No

```release-note
NONE
```

### CODE REVIEW

**Comment by FedeDP** [comment]
Thanks for the PR! 

cc @jasondellaluce are you ok with the changes?

**Review by FedeDP — APPROVED** [review]
/approve

**Review by LucaGuerra — APPROVED** [review]

**Pull request merged**
