### PR TITLE
chore(ci): enforce bundled deps generated binary (sinsp-example) to be as static as possible

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind cleanup

**Any specific area of the project related to this PR?**

/area CI

**Does this PR require a change in the driver versions?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by FedeDP** [comment]
Last test then i rebase and remove the wip.
I think this might be important to avoid future issues with cmake changes that might break static (bundled deps) builds.
/cc @Andreagit97

**Review by Andreagit97 — APPROVED** [review]
/approve

**Comment by Andreagit97** [comment]
yep in my opinion this is good for 0.13.0

**Review by jasondellaluce — APPROVED** [review]
/approve

**Pull request merged**
