### PR TITLE
sync: 0.17.2

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind cleanup

**Any specific area of the project related to this PR?**

/area build

**Does this PR require a change in the driver versions?**

**What this PR does / why we need it**:

Cherry picks:
* https://github.com/falcosecurity/libs/pull/1885
* https://github.com/falcosecurity/libs/pull/1900
* https://github.com/falcosecurity/libs/pull/1902
* https://github.com/falcosecurity/libs/pull/1905
* https://github.com/falcosecurity/libs/pull/1909

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

https://github.com/falcosecurity/libs/pull/1900 needed a manual fix since master had also changes from https://github.com/falcosecurity/libs/pull/1878 that caused a conflict.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by leogr — DISMISSED** [review]

**Comment by FedeDP** [comment]
/hold 
Will cherry pick #1909 too!

**Comment by FedeDP** [comment]
/unhold

Cherry-picked.

**Review by Andreagit97 — APPROVED** [review]
/approve

**Review by LucaGuerra — APPROVED** [review]

**Pull request merged**
