### PR TITLE
cleanup(driver) inconsistent int types

### PR DESCRIPTION
**Pull request by ecbadeaux**
**What type of PR is this?**

/kind bug

/kind cleanup

**Any specific area of the project related to this PR?**

/area driver-bpf

**Does this PR require a change in the driver versions?**

No.

**What this PR does / why we need it**:

Make bpf code more consistent.
@incertum here is a larger MR as requested.

**Which issue(s) this PR fixes**:

part of #902
(partial fix other issues still remain in 902)

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ecbadeaux** [comment]
@Andreagit97 @FedeDP 
Tagging so you guys can see this. Would like to get this in as soon as possible so merge conflicts do not arise.

**Comment by incertum** [comment]
I will review this PR tomorrow, it's now already very late for me.

**Review by incertum — APPROVED** [review]
/approve

/unhold

**Review by Andreagit97 — APPROVED** [review]
Thank you for this!
/approve

**Pull request merged**
