### PR TITLE
new(drivers): splice system call

### PR DESCRIPTION
**Pull request by loresuso**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

/kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area API-version

> /area build

> /area CI

/area driver-kmod

/area driver-bpf

/area driver-modern-bpf

> /area libscap-engine-bpf

> /area libscap-engine-gvisor

> /area libscap-engine-kmod

> /area libscap-engine-modern-bpf

> /area libscap-engine-nodriver

> /area libscap-engine-noop

> /area libscap-engine-source-plugin

> /area libscap-engine-savefile

> /area libscap-engine-udig

> /area libscap

> /area libpman

> /area libsinsp

> /area tests

> /area proposals

**Does this PR require a change in the driver versions?**

> /version driver-API-version-major

> /version driver-API-version-minor

> /version driver-API-version-patch

> /version driver-SCHEMA-version-major

> /version driver-SCHEMA-version-minor

> /version driver-SCHEMA-version-patch

**What this PR does / why we need it**:

This PR adds support for the `splice` syscall.  Given that this system call uses two fds, the old implementation in the other drivers with autofiller doesn't work (tests were failing) because old drivers do not handle casts with file descriptors properly. Moreover, ensure to pass to scap a portable representation of splice flags, like usual. 

**Which issue(s) this PR fixes**:

Part of #723 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by loresuso** [comment]
Moreover, this system call is pretty similar to `copy_file_range`. I think in our parsers we should do something like: https://github.com/falcosecurity/libs/blob/d761ce2e923e3ca82019d3739471938da3dc1d76/userspace/libsinsp/parsers.cpp#L779-L788

**Review by Andreagit97 — APPROVED** [review]
/approve

**Comment by Andreagit97** [comment]
/hold 
until https://github.com/falcosecurity/libs/pull/909 is merged

**Comment by loresuso** [comment]
Just rebased, now it will have no conflicts

**Review by hbrueckner — APPROVED** [review]
Thanks a lot @loresuso !

**Review by Andreagit97 — APPROVED** [review]
/approve

**Comment by Andreagit97** [comment]
thank you!

**Pull request merged**
