### PR TITLE
fix(libsinsp): max proc lookup number logging

### PR DESCRIPTION
**Pull request by deepskyblue86**
**What type of PR is this?**

> /kind bug

**Any specific area of the project related to this PR?**

> /area libsinsp

**Does this PR require a change in the driver versions?**

**What this PR does / why we need it**:
`m_n_proc_lookups` was incremented before doing the proc lookup, causing `Reached max process lookup number, duration=0ms` logs when max is configured to 1.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by FedeDP — APPROVED** [review]
/approve

**Review by Andreagit97 — APPROVED** [review]
/approve

**Comment by Andreagit97** [comment]
This is probably ok for 0.19.0

**Pull request merged**
