### PR TITLE
cleanup(driver/bpf/filler_helpers.h) inconsistent int types

### PR DESCRIPTION
**Pull request by ecbadeaux**
**What type of PR is this?**

/kind bug

/kind cleanup

**Any specific area of the project related to this PR?**

/area driver-bpf

**Does this PR require a change in the driver versions?**

No.

**What this PR does / why we need it**:

Make bpf code more consistent.

**Which issue(s) this PR fixes**:

part of #902
(partial fix other issues still remain in 902)

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by incertum** [comment]
@ecbadeaux how many PRs are still pending, perhaps we can consolidate just a bit? To have maybe just 2-3PRs instead of 5+?

**Comment by ecbadeaux** [comment]
> @ecbadeaux how many PRs are still pending, perhaps we can consolidate just a bit? To have maybe just 2-3PRs instead of 5+?

@incertum I can gladly close this MR and knock them all out. I was keeping these MR's small so someone wouldn't have to read an XXXXXL merge request.

Let me know what you'd prefer. Seems like you are the main reviewer anyways.

**Comment by incertum** [comment]
Maybe partition changes over 2-3 PRs in total? This should probably be ok to review. You can decide on how to partition.

**Comment by ecbadeaux** [comment]
@incertum Are we going to merge these or do you want me to close them?

**Comment by incertum** [comment]
How about just re pushing on both and adding commits? We can review commit by commit.

**Comment by ecbadeaux** [comment]
@incertum I'll tag you again when all of this is ready to be reviewed.

**Comment by incertum** [comment]
Sounds good, ah you need to remove the merge commit, always only use rebase. Ty!

**Comment by ecbadeaux** [comment]
Closing to reopen with clean branch and commits (follow the conversation above)

**Pull request closed without merging**
