### PR TITLE
new(driver): collect `dev` and `inode` in all open-family syscalls 

### PR DESCRIPTION
**Pull request by mrgian**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area API-version

> /area build

> /area CI

/area driver-kmod

/area driver-bpf

/area driver-modern-bpf

> /area libscap-engine-bpf

> /area libscap-engine-gvisor

> /area libscap-engine-kmod

> /area libscap-engine-modern-bpf

> /area libscap-engine-nodriver

> /area libscap-engine-noop

> /area libscap-engine-source-plugin

> /area libscap-engine-savefile

> /area libscap

> /area libpman

/area libsinsp

/area tests

> /area proposals

**Does this PR require a change in the driver versions?**

> /version driver-API-version-major

> /version driver-API-version-minor

> /version driver-API-version-patch

> /version driver-SCHEMA-version-major

> /version driver-SCHEMA-version-minor

> /version driver-SCHEMA-version-patch

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
new(driver): collect `dev` and `inode` in all open-family syscalls 
```

### CODE REVIEW

**Review by jasondellaluce — COMMENTED** [review]
Nice!

**Review by FedeDP — APPROVED** [review]
Thanks for this PR!
/approve

**Comment by FedeDP** [comment]
Uh just noticed, shouldn't we also update `parsers`: https://github.com/falcosecurity/libs/blob/master/userspace/libsinsp/parsers.cpp#L2585?

**Comment by mrgian** [comment]
> Uh just noticed, shouldn't we also update `parsers`: https://github.com/falcosecurity/libs/blob/master/userspace/libsinsp/parsers.cpp#L2673 and https://github.com/falcosecurity/libs/blob/master/userspace/libsinsp/parsers.cpp#L2707?

Forgot about that. I agree!
It should be fixed now.

**Review by FedeDP — APPROVED** [review]
/approve

**Review by jasondellaluce — APPROVED** [review]

**Pull request merged**
