### PR TITLE
chore(PULL_REQUEST_TEMPLATE.md): add savefile engine entry

### PR DESCRIPTION
**Pull request by jasondellaluce**
**What type of PR is this?**

/kind documentation

**Any specific area of the project related to this PR?**

**Does this PR require a change in the driver versions?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by FedeDP — DISMISSED** [review]
/approve

**Comment by Andreagit97** [comment]
Thank you very much for this!! Since you are here, maybe we can add also an area `/area CI` WDYT @jasondellaluce @FedeDP? Sometimes it could be useful but i always forget to add it :(

**Comment by jasondellaluce** [comment]
I agree. If Fede is onboard, I would add it to the template.

**Review by FedeDP — APPROVED** [review]
/approve

**Review by Andreagit97 — APPROVED** [review]

**Pull request merged**
