### PR TITLE
update(ci): bumped kernel_tests to v0.2.3

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind cleanup

**Any specific area of the project related to this PR?**

/area CI

**Does this PR require a change in the driver versions?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by Andreagit97 — APPROVED** [review]
/approve

**Comment by FedeDP** [comment]
New matrixes with improved step names :)
[matrix_ARM64.md](https://github.com/falcosecurity/libs/files/12194835/matrix_ARM64.md)
[matrix_X64.md](https://github.com/falcosecurity/libs/files/12194836/matrix_X64.md)

**Pull request merged**
