### PR TITLE
refactor(userspace/libsinsp): modularize filtercheck.h/.cpp and filter.h/.cpp in many subfiles

### PR DESCRIPTION
**Pull request by jasondellaluce**
**What type of PR is this?**

/kind cleanup

**Any specific area of the project related to this PR?**

/area libsinsp

**Does this PR require a change in the driver versions?**

No

**What this PR does / why we need it**:

This does nothing. The change splits the gigantic `filterchecks.cpp` into many subfiles, each with its own specific filtercheck class definition. Accordingly, the `sinsp_filter_check` definition has been split from `filter.cpp` too, as it was defined in another header.

This applies no change to the code, it just moves it around. Git history and blame has been preserved to the maximum feasible extent.

The goal is to improve modularization, maintainability, and order in the codebase.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by FedeDP** [comment]
What about adding a new subfolder "filterchecks" under libsinsp?

**Comment by jasondellaluce** [comment]
> What about adding a new subfolder "filterchecks" under libsinsp?

I thought about it -- my decision was not to do it for now given that we may want to spend some thinking on the filterchecks classes in the future. Given that we started having the good practice of reflecting our directory structure in the definitions' namespace, I personally think this can wait. But yeah, I'd like that in future refactors.

**Review by Andreagit97 — APPROVED** [review]
/approve

**Review by FedeDP — APPROVED** [review]
/approve

**Pull request merged**
