### PR TITLE
sync: release 0.17.x

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind cleanup

**Any specific area of the project related to this PR?**

/area driver-kmod

**Does this PR require a change in the driver versions?**

**What this PR does / why we need it**:

Cherry picks #1884 from master.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by LucaGuerra — APPROVED** [review]

**Comment by FedeDP** [comment]
Close and reopen to trigger CI.
/close

**Review by leogr — APPROVED** [review]

**Pull request merged**
