### PR TITLE
fix(libscap): add support for PT_ENUMFLAGS to scap_event_encode

### PR DESCRIPTION
**Pull request by LucaGuerra**
Signed-off-by: Luca Guerra <luca@guerra.sh>

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

> /area driver-kmod

> /area driver-ebpf

/area libscap

> /area libsinsp

> /area tests

> /area proposals

**What this PR does / why we need it**:

Add the relevant `PT_ENUMFLAGS` 8, 16, 32 to the respective cases when encoding events.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by FedeDP — APPROVED** [review]
Top!
/approve

**Comment by Andreagit97** [comment]
Thank you @LucaGuerra!
/approve

**Review by Andreagit97 — APPROVED** [review]
/approve

**Pull request merged**
