### PR TITLE
cleanup(scap,sinsp): remove userspace/common

### PR DESCRIPTION
**Pull request by gnosek**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

/kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area API-version

> /area build

> /area CI

> /area driver-kmod

> /area driver-bpf

> /area driver-modern-bpf

> /area libscap-engine-bpf

> /area libscap-engine-gvisor

> /area libscap-engine-kmod

> /area libscap-engine-modern-bpf

> /area libscap-engine-nodriver

> /area libscap-engine-noop

> /area libscap-engine-source-plugin

> /area libscap-engine-savefile

> /area libscap-engine-udig

/area libscap

> /area libpman

/area libsinsp

> /area tests

> /area proposals

**Does this PR require a change in the driver versions?**

> /version driver-API-version-major

> /version driver-API-version-minor

> /version driver-API-version-patch

> /version driver-SCHEMA-version-major

> /version driver-SCHEMA-version-minor

> /version driver-SCHEMA-version-patch

**What this PR does / why we need it**:

This PR removes userspace/common/. It contained:
* int types defined in types.h, which can be easily replaced with stdint.h
* a #define for strcasecmp for MSVC, moved to the one place that uses it (note: it's inconsistent with the *other* place that uses strcasecmp
* falcosecurity/log.h which should just live in scap
* strl* implementations for when an environment doesn't supply them; I moved this to libscap/

The downside of having all this outside libscap is complicating the include path, especially given that types.h was included in driver/ppm_events_public.h using a relative path, which just about made it impossible to include directly outside libscap. Sadly, the config file for strl.h still needs to be autogenerated but that can be mostly handled via LIBSCAP_INCLUDE_DIRS.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

None of the shouting `BREAKING CHANGE`s below should really affect users of the code but still.

**Does this PR introduce a user-facing change?**:

```release-note
cleanup(build): you no longer need to include ../common
BREAKING CHANGE: ../common/falcosecurity/log.h is now scap_log.h
BREAKING CHANGE: ../common/types.h no longer exists (use stdint.h)
BREAKING CHANGE: ../common/strl.h is now strl.h (within libscap)
BREAKING CHANGE: ../common/common_config.h (used only by strl.h) is now scap_strl_config.h
```

### CODE REVIEW

**Comment by gnosek** [comment]
> Please double check driver/SCHEMA_VERSION file. See [versioning](https://github.com/falcosecurity/libs/blob/master/driver/README.VERSION.md#schema-version-number).

Dear bot, I did double-check. Replacing __u64 with uint64_t doesn't really constitute an API change.

**Review by jasondellaluce — APPROVED** [review]

**Comment by gnosek** [comment]
> New changes are detected. LGTM label has been removed.

FWIW it's just a (conflict-free) rebase, zero code changes

**Pull request merged**
