### PR TITLE
feat(driver-kmod): Add RISC-V kernel module support

### PR DESCRIPTION
**Pull request by Xeonacid**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

/kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area API-version

/area build

> /area CI

/area driver-kmod

> /area driver-bpf

> /area driver-modern-bpf

> /area libscap-engine-bpf

> /area libscap-engine-gvisor

> /area libscap-engine-kmod

> /area libscap-engine-modern-bpf

> /area libscap-engine-nodriver

> /area libscap-engine-noop

> /area libscap-engine-source-plugin

> /area libscap-engine-savefile

> /area libscap-engine-udig

> /area libscap

> /area libpman

> /area libsinsp

/area tests

> /area proposals

**Does this PR require a change in the driver versions?**

> /version driver-API-version-major

/version driver-API-version-minor

> /version driver-API-version-patch

> /version driver-SCHEMA-version-major

> /version driver-SCHEMA-version-minor

> /version driver-SCHEMA-version-patch

I don't know if this is correct. Please fix it if I'm wrong.

**What this PR does / why we need it**:

Add RISC-V kernel module support

**Which issue(s) this PR fixes**:

Fixes partially #1175 (Only kernel module is supported, but not eBPF probe)

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
feat(driver-kmod): add riscv kernel module support
```

---

Currently, some tests are failing. I'm submitting a draft PR for an early review, please.
```text
[  FAILED  ] 11 tests, listed below:
[  FAILED  ] SyscallExit.clone3X_child
[  FAILED  ] SyscallExit.clone3X_create_child_with_2_threads
[  FAILED  ] SyscallExit.clone3X_child_clone_parent_flag
[  FAILED  ] SyscallExit.clone3X_child_new_namespace_from_child
[  FAILED  ] SyscallExit.clone3X_child_new_namespace_create_thread
[  FAILED  ] SyscallExit.cloneX_child
[  FAILED  ] SyscallExit.execveatX_correct_exit
[  FAILED  ] SyscallExit.execveatX_execve_exit
[  FAILED  ] SyscallEnter.spliceE
[  FAILED  ] Actions.dynamic_snaplen_negative_fd
[  FAILED  ] Actions.dynamic_snaplen_no_socket
```
Any clue for the failing tests is highly appreciated.

### CODE REVIEW

**Comment by FedeDP** [comment]
Thank you very much! This is super nice!
Are you working on eBPF and modern bpf too? Because we aim for feature parity for out drivers :) 

Note, however, that even if risc-v supported is merged for all drivers, i'd put its support status to `experimental` since we are not able to test it :/ 
It means no CI, and that means nobody would notice if we break it, unfortunately.

**Comment by Xeonacid** [comment]
>Are you working on eBPF and modern bpf too? Because we aim for feature parity in our drivers :)

Yeah. The eBPF support code is most completed (I think). It compiles but the verifier rejects to load so I didn't commit. Here is the tail log:
```text
261: (15) if r1 == 0x2 goto pc+59 321: R0=0 R1=2 R2=scalar(umax=131071,var_off=(0x0; 0x1ffff)) R3=scalar() R4=map_value(off=0,ks=8,vs=48,imm=0) R5=scalar() R6=ctx(off=0,imm=0) R7=map_value(off=0,ks=4,vs=181,imm=0) R8=map_value(off=0,ks=4,vs=262144,imm=0) R9=4294967293 R10=fp0 fp-8=mmmmmmmm fp-16=map_value fp-24=1 fp-32=
321: (bf) r1 = r8                     ; R1_w=map_value(off=0,ks=4,vs=262144,imm=0) R8=map_value(off=0,ks=4,vs=262144,imm=0)
322: (0f) r1 += r2                    ; R1_w=map_value(off=0,ks=4,vs=262144,umax=131071,var_off=(0x0; 0x1ffff)) R2=scalar(umax=131071,var_off=(0x0; 0x1ffff))
323: (6b) *(u16 *)(r1 +0) = r3
misaligned value access off (0x0; 0x1ffff)+0+0 size 2
processed 266 insns (limit 1000000) max_states_per_insn 0 total_states 11 peak_states 11 mark_read 10
```
Should I push it here or create another PR? The log is confusing and I'd like to finish the kernel module first.

> Note, however, that even if risc-v supported is merged for all drivers, i'd put its support status to `experimental` since we are not able to test it :/ It means no CI, and that means nobody would notice if we break it, unfortunately.

We (PLCT Lab, ISRC, ISCAS) may provide real RISC-V hardware SSH access and [ci](https://ci.rvperf.org/) if you need. :)

**Comment by FedeDP** [comment]
> Should I push it here or create another PR? The log is confusing and I'd like to finish the kernel module first.
The modern bpf probe is on the way. :P

I agree, we can split them in multiple PRs; it will be much easier to review :) perhaps you can open them already, as wip!

> We (PLCT Lab, ISRC, ISCAS) may provide [real RISC-V hardware SSH access](https://github.com/plctlab/riscv-lab-access) and [ci](https://ci.rvperf.org/) if you need. :)


Woow! Would you be willing to work on that too? Btw it would be great if we could install a github action runner to integrate that into our CI pipeline. But a ci job on jenkins would be great too!

**Comment by Xeonacid** [comment]
> I agree, we can split them in multiple PRs; it will be much easier to review :) perhaps you can open them already, as wip!

Yep, I will do that soon.

> Woow! Would you be willing to work on that too? Btw it would be great if we could install a github action runner to integrate that into our CI pipeline. But a ci job on jenkins would be great too!

It is my honor to work on this. Unfortunately, GitHub Actions [don't support riscv](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/about-self-hosted-runners#architectures) self-hosted runner at this time. :(

**Comment by FedeDP** [comment]
> It is my honor to work on this. Unfortunately, GitHub Actions [don't support riscv](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/about-self-hosted-runners#architectures) self-hosted runner at this time. :(

You are right, i totally forgot about that! Thank you very much for your work, it will be a pleasure to follow and review it!

**Comment by Xeonacid** [comment]
> > We (PLCT Lab, ISRC, ISCAS) may provide [real RISC-V hardware SSH access](https://github.com/plctlab/riscv-lab-access) and [ci](https://ci.rvperf.org/) if you need. :)
> 
> Woow! Would you be willing to work on that too?

You may create a PR at https://github.com/plctlab/riscv-lab-access to add your GitHub username (whose associated ssh key would be your pubkey for the machine) to `developers.list`. Thanks!

**Comment by FedeDP** [comment]
> You may create a PR at https://github.com/plctlab/riscv-lab-access to add your GitHub username (whose associated ssh key would be your pubkey for the machine) to developers.list. Thanks!

Nice! I will wait before doing that because that is something we (maitnainers) might want to discuss before. But thank you anyway, it will be nice to have access to a risc-v instance :)

**Comment by incertum** [comment]
@Xeonacid re some test failures on your dev box you asked about. Seems to only fully work on ubuntu, I also always get some failures on my fedora dev box, meaning you can ignore them. The CI runs them in ubuntu and this should be our current measure, we are working on improving things, thank you!

**Comment by Xeonacid** [comment]
> @Xeonacid re some test failures on your dev box you asked about. Seems to only fully work on ubuntu, I also always get some failures on my fedora dev box, meaning you can ignore them. The CI runs them in ubuntu and this should be our current measure, we are working on improving things, thank you!

Oops, thanks for your valuable information! I will try on Ubuntu riscv64. (FYI I tested on Arch Linux before)

**Comment by Xeonacid** [comment]
FYI these tests are failing on Ubuntu riscv64:
```text
[  FAILED  ] 10 tests, listed below:
[  FAILED  ] SyscallExit.clone3X_child
[  FAILED  ] SyscallExit.clone3X_create_child_with_2_threads
[  FAILED  ] SyscallExit.clone3X_child_clone_parent_flag
[  FAILED  ] SyscallExit.clone3X_child_new_namespace_from_child
[  FAILED  ] SyscallExit.clone3X_child_new_namespace_create_thread
[  FAILED  ] SyscallExit.cloneX_child
[  FAILED  ] SyscallExit.execveatX_correct_exit
[  FAILED  ] SyscallExit.execveatX_execve_exit
[  FAILED  ] Actions.dynamic_snaplen_negative_fd
[  FAILED  ] Actions.dynamic_snaplen_no_socket
```
I'm a little struggling to find the reason. Debugging is not that easy for a kernel module.  :(

**Comment by FedeDP** [comment]
> I'm a little struggling to find the reason. Debugging is not that easy for a kernel module. :(

:( can you share full output for these test cases?

**Comment by Xeonacid** [comment]
> > I'm a little struggling to find the reason. Debugging is not that easy for a kernel module. :(
> 
> :( can you share full output for these test cases?

Sure.
<details>
<summary>Failing tests log</summary>
  
```markdown
[ RUN      ] SyscallExit.clone3X_child
/home/xeonacid/libs/test/drivers/event_class/event_class.cpp:960: Failure
Failed
There is no event '335' in the buffers.

[  FAILED  ] SyscallExit.clone3X_child (435 ms)
[ RUN      ] SyscallExit.clone3X_create_child_with_2_threads
/home/xeonacid/libs/test/drivers/event_class/event_class.cpp:960: Failure
Failed
There is no event '335' in the buffers.

/home/xeonacid/libs/test/drivers/test_suites/syscall_exit_suite/clone3_x.cpp:316: Failure
Failed
There is a fatal failure in the child
[  FAILED  ] SyscallExit.clone3X_create_child_with_2_threads (495 ms)
[ RUN      ] SyscallExit.clone3X_child_clone_parent_flag
/home/xeonacid/libs/test/drivers/event_class/event_class.cpp:960: Failure
Failed
There is no event '335' in the buffers.

[  FAILED  ] SyscallExit.clone3X_child_clone_parent_flag (447 ms)
[ RUN      ] SyscallExit.clone3X_child_new_namespace_from_child
/home/xeonacid/libs/test/drivers/event_class/event_class.cpp:960: Failure
Failed
There is no event '335' in the buffers.

[  FAILED  ] SyscallExit.clone3X_child_new_namespace_from_child (459 ms)
[ RUN      ] SyscallExit.clone3X_child_new_namespace_from_caller
[       OK ] SyscallExit.clone3X_child_new_namespace_from_caller (375 ms)
[ RUN      ] SyscallExit.clone3X_child_new_namespace_create_thread
/home/xeonacid/libs/test/drivers/event_class/event_class.cpp:960: Failure
Failed
There is no event '335' in the buffers.

[  FAILED  ] SyscallExit.clone3X_child_new_namespace_create_thread (511 ms)
[ RUN      ] SyscallExit.cloneX_father
[       OK ] SyscallExit.cloneX_father (371 ms)
[ RUN      ] SyscallExit.cloneX_child
/home/xeonacid/libs/test/drivers/event_class/event_class.cpp:960: Failure
Failed
There is no event '223' in the buffers.

[  FAILED  ] SyscallExit.cloneX_child (471 ms)
...
[ RUN      ] SyscallExit.execveatX_correct_exit
[OUTPUT] SyscallExit.execveatX_success test
/home/xeonacid/libs/test/drivers/event_class/event_class.cpp:975: Failure
Failed
There is an event '331' in the buffers, but it shouldn't be there

[  FAILED  ] SyscallExit.execveatX_correct_exit (411 ms)
[ RUN      ] SyscallExit.execveatX_execve_exit
[OUTPUT] SyscallExit.execveatX_success test
/home/xeonacid/libs/test/drivers/event_class/event_class.cpp:960: Failure
Failed
There is no event '293' in the buffers.

[  FAILED  ] SyscallExit.execveatX_execve_exit (339 ms)
...
[ RUN      ] Actions.dynamic_snaplen_negative_fd
/home/xeonacid/libs/test/drivers/event_class/event_class.cpp:858: Failure
Expected equality of these values:
  size
    Which is: 0
  expected_size
    Which is: 80
>>>>> length of the param is not correct. Param id = 2

/home/xeonacid/libs/test/drivers/event_class/event_class.cpp:631: Failure
Expected equality of these values:
  memcmp(m_event_params[m_current_param].valptr, param, buf_dimension)
    Which is: -72
  0
>>>>> value of the param is not correct. Param id = 2

[  FAILED  ] Actions.dynamic_snaplen_negative_fd (407 ms)
[ RUN      ] Actions.dynamic_snaplen_no_socket
/home/xeonacid/libs/test/drivers/event_class/event_class.cpp:858: Failure
Expected equality of these values:
  size
    Which is: 0
  expected_size
    Which is: 80
>>>>> length of the param is not correct. Param id = 2

/home/xeonacid/libs/test/drivers/event_class/event_class.cpp:631: Failure
Expected equality of these values:
  memcmp(m_event_params[m_current_param].valptr, param, buf_dimension)
    Which is: -72
  0
>>>>> value of the param is not correct. Param id = 2

[  FAILED  ] Actions.dynamic_snaplen_no_socket (479 ms)
```
</details>

**Comment by FedeDP** [comment]
I think risc-v needs to enable `CAPTURE_SCHED_PROC_FORK` just like ARM64 and S390X (see driver/feature_gates.h:L63 and L173 and L233.
I am not sure about other feature gates (ie: `CAPTURE_SCHED_PROC_EXEC` or `CAPTURE_SOCKETCALL` or `CAPTURE_PAGE_FAULTS`); we will need some in-depth research about them :) 

With this change, i expect `clone` related tests to pass.
Then we will tackle the remaining ones (but let's first confirm that this patch works!)

**Comment by FedeDP** [comment]
About `execveat` ones: most probably risc-v behaves like s390x, and correctly returns a `EXECVEAT_X` when the syscall succeeds, instead of an `EXECVE_X` event.
See test/drivers/test_suites/syscall_exit_suite/execveat_x.cpp:L210 and L334 :)

**Comment by Xeonacid** [comment]
@FedeDP Oh many thanks! I noticed these options and forget them.😭 I will have a try.

**Comment by FedeDP** [comment]
Also, i'd avoid adding a new PPM_SC and entry in syscall_table in this PR; moreover, i'd also call the `driver/syscall_compat_riscv.h` -> `riscv64`, to be consistent ;) 

Note: once https://github.com/falcosecurity/syscalls-bumper is ported to support riscv64, we will have:
* automatic PPM_SC entries
* automatic syscall table entries
* automatic driver/report.md generation
* automatic compat table generation

Of course, compat table is needed for this PR to work, but i'd avoid touching PPM_SC, syscall table and driver report in this PR to keep it as simple as possible.

(i just opened the riscv64 support PR on syscalls bumper :) https://github.com/falcosecurity/syscalls-bumper/pull/11)

**Comment by Xeonacid** [comment]
Thanks to @FedeDP 's advice, only 2 tests are failing now:
```markdown
[ RUN      ] Actions.dynamic_snaplen_negative_fd
/home/xeonacid/libs/test/drivers/event_class/event_class.cpp:858: Failure
Expected equality of these values:
  size
    Which is: 0
  expected_size
    Which is: 80
>>>>> length of the param is not correct. Param id = 2

/home/xeonacid/libs/test/drivers/event_class/event_class.cpp:631: Failure
Expected equality of these values:
  memcmp(m_event_params[m_current_param].valptr, param, buf_dimension)
    Which is: -72
  0
>>>>> value of the param is not correct. Param id = 2

[  FAILED  ] Actions.dynamic_snaplen_negative_fd (395 ms)
[ RUN      ] Actions.dynamic_snaplen_no_socket
/home/xeonacid/libs/test/drivers/event_class/event_class.cpp:858: Failure
Expected equality of these values:
  size
    Which is: 0
  expected_size
    Which is: 80
>>>>> length of the param is not correct. Param id = 2

/home/xeonacid/libs/test/drivers/event_class/event_class.cpp:631: Failure
Expected equality of these values:
  memcmp(m_event_params[m_current_param].valptr, param, buf_dimension)
    Which is: -72
  0
>>>>> value of the param is not correct. Param id = 2

[  FAILED  ] Actions.dynamic_snaplen_no_socket (387 ms)
```

> I am not sure about other feature gates (ie: `CAPTURE_SCHED_PROC_EXEC` or `CAPTURE_SOCKETCALL` or `CAPTURE_PAGE_FAULTS`); we will need some in-depth research about them :)

- `CAPTURE_SCHED_PROC_EXEC`: not needed
`bpftrace -e 'tracepoint:syscalls:sys_exit_execve { printf("execve!\n"); }'` works fine on riscv and related tests are passed.
- `CAPTURE_SOCKETCALL`: not needed
riscv does not have a `socketcall` syscall.
- `CAPTURE_PAGE_FAULTS`: unsupported
This tracepoint seems only supported on x86.

Other review comments have been resolved!

**Comment by FedeDP** [comment]
Great job!! I am going to have a look at these ones then :)

**Comment by FedeDP** [comment]
In both cases it is 99% failing on:
```
evt_test->assert_bytebuf_param(2, buf, DEFAULT_SNAPLEN);
```
Because it sees 0B instead of 80B. It is interesting to understand why :D

**Comment by FedeDP** [comment]
So, most probably, we are failing in `compute_snaplen`, in `ppm_events:L386`.
I don't know why though; on which kernel version are you testing?

**Comment by FedeDP** [comment]
> You may create a PR at https://github.com/plctlab/riscv-lab-access to add your GitHub username (whose associated ssh key would be your pubkey for the machine) to developers.list. Thanks!

I created the PR to be able to access a riscv64 machine and test myself :)

**Comment by FedeDP** [comment]
@Xeonacid i added myself to the developers.list; how can i access a risc-v machine? I can't find any doc on the provided link :/

**Comment by Xeonacid** [comment]
> @Xeonacid i added myself to the developers.list; how can i access a risc-v machine? I can't find any doc on the provided link :/

Sorry for my late reply. I was Away From Ground 🛫.
Please try using your GitHub associated SSH key to log in to the `d2` machine with these credentials:
```text
Host d2
    HostName 127.0.0.1
    Port 13309
    User fededp
    ProxyJump rvlab

Host rvlab
    HostName lab.rvperf.org
    User fededp
```

And you may copy `~xeonacid/libs/build` folder to yours (You have sudo w/o passwd) or just use my project directory, to less suffer from build from scratch which takes much longer time than a common x86 machine. :P

**Comment by FedeDP** [comment]
So, it seems like `rvlab` is accepting my key, while `d2` is not:
```
ssh d2 -vv

debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Offering public key: ...
debug2: we sent a publickey packet, wait for reply
debug1: Server accepts key: ...
Authenticated to lab.rvperf.org ([47.99.40.199]:22) using "publickey".

...

debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey,password
debug1: Next authentication method: publickey
debug1: Offering public key: ...
debug2: we sent a publickey packet, wait for reply
debug1: Authentications that can continue: publickey,password
debug2: we did not send a packet, disable method
debug1: Next authentication method: password
```

**Comment by Xeonacid** [comment]
> So, it seems like `rvlab` is accepting my key, while `d2` is not:

Oh, apologize for forgetting to change `AllowUsers` in `/etc/ssh/sshd_config`. Please try now. :)

**Comment by FedeDP** [comment]
Ok the issue is that `ppm_copy_from_user` (https://github.com/falcosecurity/libs/blob/master/driver/ppm_events.c#L796) is returning non-zero in those tests.
I don't get why this happens. Note that we also have a `TEST(SyscallExit, writeX_fail)` that actually tests the very same thing (ie: that a write of `DEFAULT_SNAPLEN*2` bytes to -1 FD fails and the event only carries `DEFAULT_SNAPLEN` bytes.
The only difference is that here (ie: both `TEST(Actions, dynamic_snaplen_negative_fd)` and `TEST(Actions, dynamic_snaplen_no_socket)` we are cloning and the write is executed by the child.

**Comment by FedeDP** [comment]
It seems like i have no more root access (neither `git`, `cmake` or other deps are installed)!

**Comment by Xeonacid** [comment]
> It seems like i have no more root access (neither `git`, `cmake` or other deps are installed)!

Really? Nothing should be changed here. 🤔 
```bash
$ sudo cat /etc/sudoers
...
# User privilege specification
root    ALL=(ALL:ALL) ALL
xeonacid ALL=(ALL:ALL) NOPASSWD: ALL
fededp ALL=(ALL:ALL) NOPASSWD: ALL
...
```
Also `git` and `cmake` are both installed.

Please make sure you are accessing `d2` instead of `rvlab`. :P

**Comment by incertum** [comment]
CC @oheifetz

**Comment by FedeDP** [comment]
Hey @Xeonacid can you rebase this on top of latest master?
I don't think anything will be solved, but at least we will have latest code running in the tests!

**Comment by FedeDP** [comment]
I think it is just another `if defined riscv` issue, like eg `execveat_x`: https://github.com/falcosecurity/libs/blob/98d7df69b660703527e3dc612841465b162be74d/test/drivers/test_suites/syscall_exit_suite/execveat_x.cpp#L497

It should be fixed with:
```
#if defined(__s390x__) || defined(__riscv)
```

**Comment by FedeDP** [comment]
I really want to fix other 2 tests so that we can proceed and merge this one...need to find some spare time to look into them once again.

**Comment by FedeDP** [comment]
Rebased on top of master and fixed the execveat related failing test ;)

**Comment by FedeDP** [comment]
Me and @Andreagit97 have finally found the root cause of the test issues! Basically, the `buf` variable was paged out by the kernel, thus was not available in the context of the syscall exit while retrieving the argument from userspace, because it generated a page fault instead.

Pushed a fix (already tested on `riscv` `d2` host).
We are good to go!

**Comment by Andreagit97** [comment]
Thank you very much for the contribution and sorry for the delay!

**Review by FedeDP — APPROVED** [review]
It's been a great journey! Thank you very much for this contribution!
/approve

**Comment by Andreagit97** [comment]
SCHEMA_VERSION is a false positive here
/unhold

**Review by Andreagit97 — APPROVED** [review]
/approve

**Comment by yzewei** [comment]
> Other review comments have been resolved!

@Xeonacid  @FedeDP  Hello riscv open source workers! I would like to ask how did you locate these features?
There is a similar problem under the loongarch architecture, which I am working on
Thank you very much!

**Pull request merged**
