### PR TITLE
fix(ci): fixed github actions from master branch

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind bug

**Any specific area of the project related to this PR?**

/area build

**What this PR does / why we need it**:

Drops libs-builder image from gh actions: always install deps; the step takes like 30s and fixes multiple issues with default secret.

Moreover, refactored jobs in matrixes.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by FedeDP** [comment]
It seems the problem lies in the fact that libs-builder:dev is private :/

**Comment by FedeDP** [comment]
Ok, gh actions should be now fixed.
/cc @leogr @Andreagit97

**Review by Andreagit97 — APPROVED** [review]
/approve

**Review by leogr — APPROVED** [review]
:crossed_fingers:

**Pull request merged**
