### PR TITLE
fix: fixes returning uring_setup retvalue

### PR DESCRIPTION
**Pull request by andreabonanno**
Signed-off-by: Andrea Bonanno <andrea@bonanno.cloud>

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

 /kind bug

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

 /area driver-kmod

**What this PR does / why we need it**:
Fixes passing the `io_uring_setup` return value. 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by FedeDP — COMMENTED** [review]
/ok-to-test

**Review by FedeDP — APPROVED** [review]
/approve

**Review by leogr — APPROVED** [review]
/approve

**Pull request merged**
