### PR TITLE
vote: update(OWNERS): add jasondellaluce to approvers

### PR DESCRIPTION
**Pull request by jasondellaluce**
**What type of PR is this?**

/kind documentation

**Any specific area of the project related to this PR?**

**Does this PR require a change in the driver versions?**

**What this PR does / why we need it**:

As discussed in the community call of 2023-01-11, I'd like to propose myself as an approver in this repository. I worked on the codebase for a while and gained good knowledge of it, so I'd like to help the group of maintainers managing the repo with all its ever-growing PRs and issues.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by FedeDP** [comment]
Yay!!!
Well, big enormous huge :+1: from me!
Jason has big and deep knowledge on the whole libs repo; moreover, i think there are some parts of the code where the [bus factor](https://en.wikipedia.org/wiki/Bus_factor) is basically 1, ie: Jason only :laughing: 
Looking forward to have you on board!

**Comment by Molter73** [comment]
Super happy to see this PR! I think you'll be a great addition to the maintainers @jasondellaluce, so big +1 from my side!

**Review by LucaGuerra — APPROVED** [review]
Yes. Already adding the first approve.

**Comment by leogr** [comment]
big :+1: from me too :hugs: 

/hold for the vote to be complete as per our [governance rules](https://github.com/falcosecurity/evolution/blob/main/GOVERNANCE.md#maintainership) :angel:

**Comment by hbrueckner** [comment]
Hi @jasondellaluce, excellent addition to team. I am looking forward working with you!
vote: +1

**Comment by Andreagit97** [comment]
i think we can merge this we have already reached the majority, we miss just @gnosek and @mstemm votes

**Review by leogr — APPROVED** [review]
Welcome!

**Comment by leogr** [comment]
> i think we can merge this we have already reached the majority, we miss just @gnosek and @mstemm votes

Correct :+1: 

/hold cancel

**Comment by jasondellaluce** [comment]
Thanks everyone!

**Pull request merged**
