### PR TITLE
cleanup(libsinsp): do not rely on null-terminated string_views

### PR DESCRIPTION
**Pull request by LucaGuerra**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind cleanup

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area libsinsp

**Does this PR require a change in the driver versions?**

No

**What this PR does / why we need it**:

During recent refactors of parameter handling in parsers we introduced `std::string_view`s to handle strings coming from the drivers. However, in subsequent calls that required `const char *` we relied on the fact that those string views had a NUL right after the end. This is technically an oob read (although harmless in this case) and so we just need to handle this properly by using `std::string`s when necessary. We already got rid of a few instances, this PR cleans up the rest of them.

cc @gnosek @fededp

/milestone 0.15.0

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by incertum — COMMENTED** [review]
Quite happy to see this string handling cleanup, because as you know some inconsistencies drove me nuts in recent patches we worked on together lately 😉 .

**Comment by FedeDP** [comment]
Must be rebased on master to fix ci i guess :)  (https://github.com/falcosecurity/libs/pull/1617)

**Review by jasondellaluce — APPROVED** [review]
/approve

**Review by Andreagit97 — APPROVED** [review]
/approve

**Pull request merged**
