### PR TITLE
update(driver): add a backoff in case of modern probe timeout

### PR DESCRIPTION
**Pull request by Andreagit97**
Signed-off-by: Andrea Terzolo <andrea.terzolo@polito.it>

**What type of PR is this?**

/kind feature

**Any specific area of the project related to this PR?**

/area libscap-engine-modern-bpf

**Does this PR require a change in the driver versions?**

No

**What this PR does / why we need it**:

This PR reduces the number of timeouts in the modern bpf probe

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by FedeDP — DISMISSED** [review]
/approve
So we are now following same algorithm as kmod and ebpf, right?

**Comment by Andreagit97** [comment]
> So we are now following same algorithm as kmod and ebpf, right?

Yes, exactly

**Review by hbrueckner — DISMISSED** [review]
Looks nice.
/lgtm

**Review by leogr — DISMISSED** [review]

**Review by FedeDP — APPROVED** [review]
/approve

**Comment by Andreagit97** [comment]
I had to retrigger the CI to run jobs :/ @leogr

**Review by LucaGuerra — APPROVED** [review]

**Pull request merged**
