### PR TITLE
Change event_flags from EF_NONE to EF_DROP_SIMPLE_CON for io_uring sycalls

### PR DESCRIPTION
**Pull request by alacuku**
```
Signed-off-by: Aldo Lacuku <aldo@lacuku.eu>
```

**What type of PR is this?**

/kind feature

**Any specific area of the project related to this PR?**

/area driver-kmod

/area driver-ebpf

/area libscap

/area libsinsp

**What this PR does / why we need it**:

This PR changes `event_flags` from `EF_NONE` to `EF_DROP_SIMPLE_CONS` for `io_uring` sycalls family. The events generated by uring syscalls can be skipped by consumers that privilege low overhead to full event capture.

Note that Falco needs to be run with `-A` flag in order to match rules against events generated by `io_uring` system calls.

**Does this PR introduce a user-facing change?**:

```release-note
update: add `io_uring` system calls family to the `EF_DROP_SIMPLE_CONS` group
```

### CODE REVIEW

**Comment by FedeDP** [comment]
Hi Aldo! Thanks for this PR! :blush:
/ok-to-test

**Review by FedeDP — DISMISSED** [review]
/approve

**Review by leogr — DISMISSED** [review]
/approve

**Comment by FedeDP** [comment]
@alacuku can you also fix category for io_uring syscalls? 
In event_table we have `EC_OTHER` for `io_uring_setup` and `io_uring_register`, while on syscall_info_table we have `EC_IO_OTHER` for all.
I think `EC_IO_OTHER` is ok!

**Review by Andreagit97 — APPROVED** [review]
/approve

**Review by FedeDP — APPROVED** [review]
/approve

**Pull request merged**
