### PR TITLE
new(modern_bpf): add missing tracepoints

### PR DESCRIPTION
**Pull request by Andreagit97**
**What type of PR is this?**

/kind feature

**Any specific area of the project related to this PR?**

/area libscap-engine-modern-bpf

/area tests

**Does this PR require a change in the driver versions?**

No

**What this PR does / why we need it**:

This PR adds 2 new tracepoints to the modern probe (https://github.com/falcosecurity/libs/issues/513) :

- `sched_process_exit`
- `sched_switch`

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

This PR seems huge because I've just added the `delete` call to all tests :) 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by FedeDP** [comment]
> This PR seems huge because I've just added the delete call to all tests :)

Couldn't we use an `unique_ptr` for that instead? :)

**Review by FedeDP — COMMENTED** [review]
PR LGTM!
Amazing work as always @Andreagit97 !

**Comment by hbrueckner** [comment]
Hi @Andreagit97,

excellent work! Test passes on `s390x`:
````
[----------] 2 tests from GenericTracepoints
[ RUN      ] GenericTracepoints.sched_proc_exit
[       OK ] GenericTracepoints.sched_proc_exit (12 ms)
[ RUN      ] GenericTracepoints.sched_switch
[       OK ] GenericTracepoints.sched_switch (11 ms)
[----------] 2 tests from GenericTracepoints (24 ms total)
````
I reviewed your commits, no comments from my side this time.

/lgtm

**Comment by Andreagit97** [comment]
I've not use `make_unique<>` because it requires c++14

**Review by FedeDP — APPROVED** [review]
/approve

**Review by leogr — APPROVED** [review]

**Pull request merged**
