### PR TITLE
update(CI): build also `bpf_test` in ARM64 job

### PR DESCRIPTION
**Pull request by Andreagit97**
Signed-off-by: Andrea Terzolo <andrea.terzolo@polito.it>

**What type of PR is this?**

/kind feature

**Any specific area of the project related to this PR?**

/area build

**Does this PR require a change in the driver versions?**

**What this PR does / why we need it**:

This PR allows us to build also the `bpf_test` executable in CI, this could help us in not introducing tests not compatible with some architectures, like in this case https://github.com/falcosecurity/libs/pull/503/commits/bee4e7bbe54e3ab573e9dfd3a2a4844d15b0579a

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by FedeDP — DISMISSED** [review]
/approve

**Review by Molter73 — CHANGES_REQUESTED** [review]
This is awesome to have!

Can we update the name for the workflow? I notice it is still called `build-modern-bpf-arm64 🙃 (system_deps)` but we are now running tests and building with `-DUSE_BUNDLED_DEPS=ON`

**Comment by Molter73** [comment]
Never mind the first part of my review, I just noticed we are not running the tests, only building them, the system deps though do make some noise to me.

**Comment by Andreagit97** [comment]
> Never mind the first part of my review, I just noticed we are not running the tests, only building them, the system deps though do make some noise to me.

indeed this is a good point, let's check if it runs also with system deps, it should do it :crossed_fingers:

**Comment by Andreagit97** [comment]
we have it :tada:
/unhold

**Review by Molter73 — APPROVED** [review]
/lgtm

**Review by FedeDP — APPROVED** [review]
/approve

**Pull request merged**
