### PR TITLE
sync: release 0.18.2

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind cleanup

**Any specific area of the project related to this PR?**

**Does this PR require a change in the driver versions?**

**What this PR does / why we need it**:

Cherrypicks:
* https://github.com/falcosecurity/libs/pull/2150
* https://github.com/falcosecurity/libs/pull/2119

from master.

Also, it cherry-picks all CI changes from master to be able to successfully pass CI checks.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by leogr — APPROVED** [review]

**Comment by leogr** [comment]
> We will probably need to cherry pick also all CI changes...

@FedeDP let me know, I can re-approve, eventually

**Review by leogr — APPROVED** [review]

**Comment by Andreagit97** [comment]
https://github.com/falcosecurity/test-infra/pull/1697

**Pull request merged**
