### PR TITLE
fix(userspace/libscap): add a CI job for musl static builds and fix issues with it

### PR DESCRIPTION
**Pull request by jasondellaluce**
**What type of PR is this?**

/kind bug

**Any specific area of the project related to this PR?**

/area CI

/area libscap

**Does this PR require a change in the driver versions?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

In Falco our build pipeline prevents us from bumping the libs due to a failure in the MUSL static build. This PR attempts fixing that and also adds a CI job covering that compilation case for preventing future regressions.

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by FedeDP** [comment]
Great, thank you @jasondellaluce !

**Review by incertum — APPROVED** [review]
/approve

**Comment by FedeDP** [comment]
Uh the ci was failing but obviously the job was still not marked as required status check.
@jasondellaluce care to take a look on Monday? :)

**Pull request merged**
