### PR TITLE
Adding openat2 header file under __NR_openat2 and UDIG ifdef code block

### PR DESCRIPTION
**Pull request by akulhar**
Signed-off-by: akulhar <kulhar1985@gmail.com>

**What type of PR is this?**
Fix for storage size of ‘how’ isn’t known compilation error 

> Uncomment one (or more) `/kind <>` lines:

/kind bug

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area build

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by akulhar** [comment]
@poiana Do I need to add release-note-label, let me know the process in case it is required?

**Comment by leogr** [comment]
> @poiana Do I need to add release-note-label, let me know the process in case it is required?

No, you don't need to add it. `NONE` is ok in this case. 
Btw, your PR SGTM, but I have to find the time to try it. Thank you!

**Review by leogr — APPROVED** [review]
/approve

**Review by FedeDP — APPROVED** [review]
/approve

Thank you!

**Pull request merged**
