### PR TITLE
fix(userspace): add compat syscalls header 

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind cleanup

**Any specific area of the project related to this PR?**

/area libscap
/area libsinsp

**Does this PR require a change in the driver versions?**

NO.

**What this PR does / why we need it**:

Allow userspace to be able to see all syscall_table, making syscallNR -> PPME event lookup working for any syscall.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by Andreagit97 — APPROVED** [review]
/approve

**Review by LucaGuerra — APPROVED** [review]
I did find those functions a bit confusing, compat tables sound ok to me

**Review by Andreagit97 — APPROVED** [review]
/approve

**Pull request merged**
