### PR TITLE
update(userspace): stop capture before closing the engine

### PR DESCRIPTION
**Pull request by Andreagit97**
**What type of PR is this?**

/kind cleanup

/kind feature

**Any specific area of the project related to this PR?**

/area libscap

**Does this PR require a change in the driver versions?**

**What this PR does / why we need it**:

This PR ensures the capture stop before closing the engine.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by FedeDP** [comment]
I am a bit against this since I introduced the split between open/start and stop/close.
I think closing a scap should not stopping the capture just like opening scap is not starting the capture. You are just retrieving an handle and closing it, but capture should be manually managed!
At the bare minimum, we should check if capture has been started before (perhaps caching a boolean); yet I don't like this asimmetry in the Scap API!

**Comment by Andreagit97** [comment]
uhm completely agree with open/start question, but with stop/close here I'm missing something... 

> I think closing a scap should not stopping the capture just like opening scap is not starting the capture. You are just retrieving an handle and closing it, but capture should be manually managed!

When you close the engine you are destroying everything so explicitly or implicitly the capture should be stopped :thinking: I see the `stop` and `start` as idempotent actions so, the `stop` when closing the engine ensures only a graceful termination if the client forgot to explicitly call it. The APIs are still different, the scap_close call only the vtable close method inside it to ensure a correct termination :/

**Comment by Andreagit97** [comment]
let's say (`open` -> `start_capture` is always not true but `close` -> `stop_capture` is always true)

**Comment by FedeDP** [comment]
Mmmh what if instead:
* open
* start ?
* stop ? -> if i run start, i know i need to run stop
* close

Note moreover, that closing scap without stopping will always also stop capture in one way or another (ie: for bpf and modern bpf, we kill the probe; for kmod, the consumer gets detached and cleaned up).

**Review by FedeDP — APPROVED** [review]
/approve

**Review by leogr — APPROVED** [review]

**Pull request merged**
