### PR TITLE
fix(userspace): resolve some alerts generated by the Falco CodeQL job

### PR DESCRIPTION
**Pull request by Andreagit97**
Signed-off-by: Andrea Terzolo <andrea.terzolo@polito.it>

**What type of PR is this?**

/kind bug

/kind cleanup

**Any specific area of the project related to this PR?**

/area libscap

**Does this PR require a change in the driver versions?**

No

**What this PR does / why we need it**:

This PR should solve some issues highlighted by the CodeQL job in Falco:

- https://github.com/falcosecurity/falco/security/code-scanning/18
- https://github.com/falcosecurity/falco/security/code-scanning/19

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by Andreagit97** [comment]
cc @LucaGuerra

**Review by LucaGuerra — APPROVED** [review]
lgtm

**Review by FedeDP — APPROVED** [review]
/approve

**Pull request merged**
