### PR TITLE
[part 4/n] Split scap_*.c into platform-specific files

### PR DESCRIPTION
**Pull request by gnosek**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

/kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area API-version

> /area build

> /area CI

> /area driver-kmod

> /area driver-bpf

> /area driver-modern-bpf

> /area libscap-engine-bpf

> /area libscap-engine-gvisor

> /area libscap-engine-kmod

> /area libscap-engine-modern-bpf

> /area libscap-engine-nodriver

> /area libscap-engine-noop

> /area libscap-engine-source-plugin

> /area libscap-engine-savefile

> /area libscap-engine-udig

/area libscap

> /area libpman

> /area libsinsp

> /area tests

> /area proposals

**Does this PR require a change in the driver versions?**

> /version driver-API-version-major

> /version driver-API-version-minor

> /version driver-API-version-patch

> /version driver-SCHEMA-version-major

> /version driver-SCHEMA-version-minor

> /version driver-SCHEMA-version-patch

**What this PR does / why we need it**:

This PR splits scap_procs.c, scap_fds.c, scap_userlist.c, and scap_iflist.c into platform-independent and platform-specific parts. There are no code changes, except for strerror which now lives in a separate file (scap_procs.c was pretty arbitrary TBH). This means we're dealing with moderately pointless code, like win32/scap_userlist.c but this PR deliberately doesn't address that so it's easier to review.

Git history should be preserved in all the new files.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by FedeDP** [comment]
Isn't this a 4/n? :P https://github.com/falcosecurity/libs/pull/487
:rofl:

**Comment by gnosek** [comment]
One, two, many, lots ;)

**Review by FedeDP — APPROVED** [review]
I think it might be the right time to merge this, given we are pretty far from next release.
/approve

**Review by LucaGuerra — APPROVED** [review]
agree, let's test this (I probably need to rebase another PR already but still...)

**Pull request merged**
