### PR TITLE
fix(driver): Remove __NR_socketcall check

### PR DESCRIPTION
**Pull request by sumitd2**
Signed-off-by: Sumit Dubey <sumit.dubey2@ibm.com>

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

/area driver-kmod

/area driver-bpf

> /area driver-modern-bpf

> /area libscap-engine-bpf

> /area libscap-engine-gvisor

> /area libscap-engine-kmod

> /area libscap-engine-modern-bpf

> /area libscap-engine-nodriver

> /area libscap-engine-noop

> /area libscap-engine-source-plugin

> /area libscap-engine-udig

> /area libscap

> /area libsinsp

> /area tests

> /area proposals

**What this PR does / why we need it**:

Both the socket family system calls, and __NR_socketcall are defined on ppc64le. So removed the __NR_socketcall check in syscall_table.c.

**Which issue(s) this PR fixes**:

Socket events not being reported by sinsp-example. https://github.com/falcosecurity/libs/issues/360 (Second comment from author).

Fixes #

**Special notes for your reviewer**:
None
**Does this PR introduce a user-facing change?**:
No

```release-note
NONE
```

### CODE REVIEW

**Comment by FedeDP** [comment]
Hi! Thanks for this PR! 
/cc @Andreagit97

**Comment by FedeDP** [comment]
I think there is a bit more of logic around socketcall:
* https://github.com/falcosecurity/libs/search?q=__NR_socketcall
* https://github.com/falcosecurity/libs/search?q=_HAS_SOCKETCALL

**Review by Andreagit97 — APPROVED** [review]
Hi, @sumitd2 thank you for this fix! The `#ifndef __NR_socketcall` cause all other socket-related syscalls to become generic events since the driver can't find the right events in the table. The logic to manage together `__NR_socketcall` and all network syscalls should be already in place, so this fix should be enough, thank you again :rocket:

**Review by FedeDP — APPROVED** [review]
/approve

**Pull request merged**
