### PR TITLE
sync: release 0.13.2

### PR DESCRIPTION
**Pull request by Andreagit97**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

Backports 
- [x] https://github.com/falcosecurity/libs/pull/1373
- [x] https://github.com/falcosecurity/libs/pull/1392
- [x] https://github.com/falcosecurity/libs/pull/1396
- [x] https://github.com/falcosecurity/libs/pull/1402
- [x] https://github.com/falcosecurity/libs/pull/1403
- [x] https://github.com/falcosecurity/libs/pull/1405
- [x] https://github.com/falcosecurity/libs/pull/1379

from master.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by FedeDP — APPROVED** [review]
/approve

**Review by LucaGuerra — APPROVED** [review]
Thanks!

**Pull request merged**
