### PR TITLE
fix(libsinsp): safely check number of parameters on execve exit parser

### PR DESCRIPTION
**Pull request by loresuso**
Signed-off-by: Lorenzo Susini <susinilorenzo1@gmail.com>

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

> /area driver-kmod

> /area driver-ebpf

> /area libscap

/area libsinsp

> /area tests

> /area proposals

**What this PR does / why we need it**:

Safely check the version of the execve event in the exit parser by checking the number of parameters

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by FedeDP** [comment]
I like this! Thank you very much :copyright: 

/ok-to-test

**Review by FedeDP — APPROVED** [review]
/approve

**Review by leogr — APPROVED** [review]
/approve

**Comment by FedeDP** [comment]
Closing and reopening to wakeup poiana :P 
/close

**Pull request merged**
