### PR TITLE
update(OWNERS): add Luca Guerra (LucaGuerra) to owners

### PR DESCRIPTION
**Pull request by LucaGuerra**
Signed-off-by: Luca Guerra <luca@guerra.sh>

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind documentation

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area proposals

**What this PR does / why we need it**:

As we discussed in yesterday's (Aug 3rd 2022) Falco community call and given the positive feedback from other current maintainers present, since I worked over the course of the past few months on new features, bugfixes, releases, security content, reviews and refactoring on the Falco libraries I would like to bring my contributions to this project to the next level by proposing myself as a maintainer.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by FedeDP** [comment]
I wasn't present yesterday at the community meeting therefore i could not state my incredible joy in seeing this PR!
Luca is a great guy and an even better security oriented developer :closed_lock_with_key:  I am glad to see you joining us, and am sure that you will help us improve the libs with both PRs and reviews! Welcome on board :) 
This is a big :+1: from me!

**Comment by Andreagit97** [comment]
Also for me a huge +1 :heart_eyes:

**Comment by Molter73** [comment]
+1 on my end as well, Luca makes really great contributions to the repo, we would benefit greatly from having him onboard!

**Review by Andreagit97 — APPROVED** [review]
/approve

**Comment by leogr** [comment]
Big +1 me too. I know Luca and his skill. After his recent contribution, I'm totally convinced he deserves to be a maintainer.

PS 
@LucaGuerra 
Could you open a PR in test-infra to add yourself as a member of the org and to the libs-maintainers team, please?
https://github.com/falcosecurity/test-infra/blob/master/config/org.yaml#L19

**Review by leogr — APPROVED** [review]
Welcome! :hugs:

**Pull request merged**
