### PR TITLE
Reintroducing the token_bucket unit test adapted to gtest

### PR DESCRIPTION
**Pull request by loresuso**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

/kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

> /area driver-kmod

> /area driver-ebpf

> /area libscap

> /area libsinsp

/area tests

> /area proposals

**What this PR does / why we need it**:
This PR reintroduces the `token_bucket` unit test that previously belonged to the `falco` repository. As `token_bucket` was moved from there to this repository, its unit tests must be adapted to use `gtest`, since this is the testing framework that `libs` uses. 

**Which issue(s) this PR fixes**:

Fixes https://github.com/falcosecurity/libs/issues/137

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by leogr — APPROVED** [review]
/approve

**Review by FedeDP — APPROVED** [review]
Great job, thanks!

**Review by gnosek — APPROVED** [review]

**Pull request merged**
