### PR TITLE
sync: release 0.17.1

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind cleanup

**Any specific area of the project related to this PR?**

/area libsinsp

**Does this PR require a change in the driver versions?**

**What this PR does / why we need it**:

Cherry picks 2 PRs from master for the 0.17.1 release:
* https://github.com/falcosecurity/libs/pull/1879
* https://github.com/falcosecurity/libs/pull/1880

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by LucaGuerra — APPROVED** [review]

**Comment by FedeDP** [comment]
Closing and reopening to re-trigger ci after base change.
/close

**Review by Andreagit97 — APPROVED** [review]
/approve

**Pull request merged**
