### PR TITLE
update(cmake): Install libraries into CMAKE_INSTALL_LIBDIR

### PR DESCRIPTION
**Pull request by geraldcombs**
Install libraries into CMAKE_INSTALL_LIBDIR. This appears to be more compliant with the FHS[1] and simplifies linking when BUILD_SHARED_LIBS is enabled.

[1] https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s06.html

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

/kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area API-version

/area build

> /area CI

> /area driver-kmod

> /area driver-bpf

> /area driver-modern-bpf

> /area libscap-engine-bpf

> /area libscap-engine-gvisor

> /area libscap-engine-kmod

> /area libscap-engine-modern-bpf

> /area libscap-engine-nodriver

> /area libscap-engine-noop

> /area libscap-engine-source-plugin

> /area libscap-engine-savefile

> /area libscap-engine-udig

> /area libscap

> /area libpman

> /area libsinsp

> /area tests

> /area proposals

**Does this PR require a change in the driver versions?**

> /version driver-API-version-major

> /version driver-API-version-minor

> /version driver-API-version-patch

> /version driver-SCHEMA-version-major

> /version driver-SCHEMA-version-minor

> /version driver-SCHEMA-version-patch

**What this PR does / why we need it**:

This avoids having to mess with LD_LIBRARY_PATH or -Wl,-rpath when using shared libs.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by geraldcombs** [comment]
We might want to close this in favor of https://salsa.debian.org/debian/falcosecurity-libs/-/blob/master/debian/patches/fix-library-install-path.patch

**Comment by geraldcombs** [comment]
> We might want to close this in favor of https://salsa.debian.org/debian/falcosecurity-libs/-/blob/master/debian/patches/fix-library-install-path.patch

I replaced the original PR changes with the patch.

**Review by gnosek — APPROVED** [review]

**Comment by FedeDP** [comment]
cc @terylt @araujof you might be interested in this one :)

**Review by FedeDP — APPROVED** [review]
/approve

**Pull request merged**
