### PR TITLE
new(gvisor): get socket from configuration file, fix tests

### PR DESCRIPTION
**Pull request by LucaGuerra**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

/kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

> /area driver-kmod

> /area driver-bpf

> /area driver-modern-bpf

> /area libscap-engine-bpf

/area libscap-engine-gvisor

> /area libscap-engine-kmod

> /area libscap-engine-modern-bpf

> /area libscap-engine-nodriver

> /area libscap-engine-noop

> /area libscap-engine-source-plugin

> /area libscap-engine-udig

/area libscap

> /area libsinsp

> /area tests

> /area proposals

**What this PR does / why we need it**:

This PR adds some enhancements to gVisor support:
1. small change to the interface to be able to read the socket directly from the configuration file
2. fixes to the procfs unit test and parsing

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
new(gvisor): enable reading the socket path from configuration file
```

### CODE REVIEW

**Comment by loresuso** [comment]
Very nice PR, I like it!

**Comment by FedeDP** [comment]
Very nice PR as always Luca!
/ok-to-test

**Review by FedeDP — APPROVED** [review]
/approve

**Review by Andreagit97 — APPROVED** [review]
/approve

**Pull request merged**
