### PR TITLE
Fix kmod build error

### PR DESCRIPTION
**Pull request by gnosek**
SCAP_HANDLE_T must be defined before including scap_open.h (which gets included from kmod.h)

Also, remove a few unnecessary `#include`s; in particular, including engine internal headers shouldn't be needed (any more; it was a temporary measure during the engine refactor)

```
/draios/falco-libs/userspace/libscap/engine/kmod/scap_kmod.c:26:0: error: "SCAP_HANDLE_T" redefined [-Werror]
 #define SCAP_HANDLE_T struct kmod_engine
 ^
In file included from /draios/falco-libs/userspace/libscap/engine/kmod/kmod.h:21:0,
                 from /draios/falco-libs/userspace/libscap/engine/kmod/scap_kmod.c:25:
/draios/falco-libs/userspace/libscap/scap_open.h:24:0: note: this is the location of the previous definition
 #define SCAP_HANDLE_T void
 ^
```

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

/kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area API-version

/area build

> /area CI

> /area driver-kmod

> /area driver-bpf

> /area driver-modern-bpf

> /area libscap-engine-bpf

> /area libscap-engine-gvisor

/area libscap-engine-kmod

> /area libscap-engine-modern-bpf

> /area libscap-engine-nodriver

> /area libscap-engine-noop

> /area libscap-engine-source-plugin

> /area libscap-engine-savefile

> /area libscap-engine-udig

/area libscap

> /area libpman

> /area libsinsp

> /area tests

> /area proposals

**Does this PR require a change in the driver versions?**

> /version driver-API-version-major

> /version driver-API-version-minor

> /version driver-API-version-patch

> /version driver-SCHEMA-version-major

> /version driver-SCHEMA-version-minor

> /version driver-SCHEMA-version-patch

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by FedeDP** [comment]
Thank you @gnosek! Great catch! 
I wonder why are CI didn't catch that (and nobody noticed; i think scap is building to everyone, eg @LucaGuerra @Andreagit97 and me). 

Roll up roll up for the Mystery Tour!

**Review by Andreagit97 — APPROVED** [review]
probably this issue is triggered with not clean builds :thinking: 
BTW LGTM
/apporve

**Comment by LucaGuerra** [comment]
> Roll up roll up for the Mystery Tour!

In my case I tried the full build (including Falco) after my changes, then I noticed there was an hold and I had to rebase, so I only "formally" rebased my changes without retesting with Falco. In fact, after the rebase the PR I merged doesn't build with Falco :)

**Pull request merged**
