### PR TITLE
fix(test): fix memleak in sinsp-example formatters

### PR DESCRIPTION
**Pull request by LucaGuerra**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area tests
/area libsinsp

**Does this PR require a change in the driver versions?**

No.

**What this PR does / why we need it**:

If you try to run e2e tests with Asan you will get LeakSanitizer complaining about the memory that was lost here. Easy fix with a `unique_ptr`.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by incertum** [comment]
@LucaGuerra let's sync with @gnosek who reworked a lot in https://github.com/falcosecurity/libs/pull/839.

**Review by gnosek — APPROVED** [review]
My rework fixes that too but it's no reason to hold back this fix

**Comment by LucaGuerra** [comment]
Thanks @gnosek , I now noticed that this exact change (plus removal of `net_formatter`) is also in the other PR, will be easy to merge the rework on top of this :) Thanks for agreeing to merge this PR so https://github.com/falcosecurity/libs/pull/978 can be unblocked

**Review by FedeDP — APPROVED** [review]
/approve

**Pull request merged**
