### PR TITLE
fix(userspace/libsinsp): fix checks on PT_BYTEBUF fields and optimize bcontains/bstartswith

### PR DESCRIPTION
**Pull request by jasondellaluce**
**What type of PR is this?**

/kind bug

**Any specific area of the project related to this PR?**

/area libsinsp

**What this PR does / why we need it**:

This PR brings 3 contributions:
1. Fix a regression in filterchecks involving fields of type PT_BYTEBUF. After the recent refactorings of #201, the length of the right-hand bytebuf values was not passed-down in `sinsp_filter_check::compare`, which inherently ended up making all checks on bytebufs return true due to a `memcmp` being performed with length = 0.
2. Optimizes the performance of `bcontains` and `bstartswith` operators. Previously, the operator performed the hexstr <->  bytebuf conversion at each check, which is not performant and should instead be done at initialization time. Now, the hex string is converted to a bytebuf right at the filter compilation level
3. Add a first attempt of unit testing for filtercheck operators, starting with the `bcontains` operator (and `bstartswith`, since they are similar). We didn't have unit tests for filterchecks and operators so far, and perhaps the class designs involved are not much testable, but we can use this first attempt as a base to do more of these in the future.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by FedeDP — COMMENTED** [review]
This is beautiful @jasondellaluce , thank you so much!
LGTM, waiting on the CI to do its job :)

**Review by leogr — APPROVED** [review]
Nice!

LGTM

**Review by FedeDP — APPROVED** [review]
/approve

**Comment by loresuso** [comment]
I like it, thanks! 🎉

**Pull request merged**
