### PR TITLE
update(scap-open): count the number of timeouts if buffers are empty

### PR DESCRIPTION
**Pull request by Andreagit97**
**What type of PR is this?**

/kind feature

**Any specific area of the project related to this PR?**

/area scap-open

**Does this PR require a change in the driver versions?**

**What this PR does / why we need it**:

This PR allows us to understand the number of times the userspace tries to poll the ring buffers but they are empty 

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by FedeDP — DISMISSED** [review]
/approve

**Review by FedeDP — APPROVED** [review]
/approve

**Review by leogr — APPROVED** [review]

**Pull request merged**
