### PR TITLE
new(test): add "Coverage" build type to generate test coverage info

### PR DESCRIPTION
**Pull request by LucaGuerra**
Signed-off-by: Luca Guerra <luca@guerra.sh>

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind feature

**Any specific area of the project related to this PR?**

/area libscap
/area libsinsp
/area tests

**Does this PR require a change in the driver versions?**

**What this PR does / why we need it**:

When working on tests it's sometimes useful to generate coverage information to be used as a guide improve our current test suite. I have already inspected reports generated via this gcov + lcov (I discovered "the hard way" that this is the combination that works best) and there are definitely areas in which we can easily improve, specifically in libsinsp.

Additional thoughts: Note that aiming for 100% coverage is not really the point here but in order to get to a better baseline we can add coverage generation to the CI, and maybe alert if the code that is being added is lowering the overall coverage, encouraging the author to add UTs where possible.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by FedeDP — COMMENTED** [review]
I really like this!
/cc @leogr

**Review by FedeDP — APPROVED** [review]
/approve

**Review by leogr — APPROVED** [review]
Nice!

**Pull request merged**
