### PR TITLE
new(ci): dynamic badge for latest kernel workflow

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind feature

**Any specific area of the project related to this PR?**

/area CI

**Does this PR require a change in the driver versions?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

This PR is using a gist created from my `FedeDP` github account. Github does not support organization gists (https://github.com/orgs/community/discussions/7923). 
We might want to move this under Poiana account in the future.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by FedeDP** [comment]
See the generated readme from run: https://github.com/falcosecurity/libs/actions/runs/5443297895/jobs/9899650455?pr=1186

https://github.com/falcosecurity/libs/blob/5957c05a47075ae8954663730822d73cebd223bf/README.md

**Review by jasondellaluce — APPROVED** [review]
/approve

**Review by leogr — APPROVED** [review]
:+1:

**Pull request merged**
