### PR TITLE
update(userspace/libscap): Makes BPF_PROGS_MAX configurable at compile time

### PR DESCRIPTION
**Pull request by Stringy**
**What type of PR is this?**

/kind feature

**Any specific area of the project related to this PR?**
/area libscap

**What this PR does / why we need it**:

This is a very small change that makes BPF_PROGS_MAX configurable at compile time. I'm currently building a custom probe that works with Falco (as outlined in #267 ) and it has more programs than libscap can currently work with. This change will allow me to define a larger limit.

As an aside, accesses to the various arrays that use BPF_PROGS_MAX as their size are not bounds-checked and whilst I have not added these checks here they might also make sense for a bit more robustness in the libs. (I am happy to add them if desired!) 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by Andreagit97** [comment]
Thank you for this PR @Stringy! That's a great idea! In my opinion, would be great to achieve a little bit more robustness in the libs with these checks on the max array dimensions!
/ok-to-test

**Review by leogr — DISMISSED** [review]
Good idea :+1: 

/approve

**Comment by FedeDP** [comment]
> As an aside, accesses to the various arrays that use BPF_PROGS_MAX as their size are not bounds-checked and whilst I have not added these checks here they might also make sense for a bit more robustness in the libs. (I am happy to add them if desired!)

+1!

**Comment by Stringy** [comment]
> Can't we have a cmake option around that though? 

Good point! I'll add one as well. 

And, due to popular demand, I'll add those bounds checks :) with any luck I'll get those done today and added to this PR

**Review by FedeDP — APPROVED** [review]
Love it! Thank you!
/approve

**Review by Andreagit97 — APPROVED** [review]
/approve

**Pull request merged**
