### PR TITLE
cleanup(ci): split a driverkit workflow from main ci workflow.

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind cleanup

**Any specific area of the project related to this PR?**

/area CI

**Does this PR require a change in the driver versions?**

**What this PR does / why we need it**:

The PR extracts a driverkit workflow from the main ci workflow (that is indeed getting too big).

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by Molter73 — APPROVED** [review]
/lgtm

**Review by Andreagit97 — APPROVED** [review]
/approve

**Pull request merged**
