### PR TITLE
cleanup(build): replace CMD_MAKE with CMAKE_MAKE_PROGRAM

### PR DESCRIPTION
**Pull request by mattnite**
**What type of PR is this?**

/kind cleanup

**Any specific area of the project related to this PR?**

/area build

**Does this PR require a change in the driver versions?**

No.

**What this PR does / why we need it**:

This change makes it easier for downstream users to compile `falcosecurity/libs` with bundled dependencies. `CMD_MAKE` was introduced with the commit `907d1a81d9407eb3ead2ce400eb8b5dc222e404a` (2014) to support SunOS by setting the value to `gmake` instead of `make`. With `CMAKE_MAKE_PROGRAM` CMake will handle make program selection for us.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

I have not tested building on SunOS, just following [CMake documentation](https://cmake.org/cmake/help/v3.24/variable/CMAKE_MAKE_PROGRAM.html). If that's something you require, then I'm happy to put in more work.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by FedeDP** [comment]
I love this; just approved the CI tests :) 

@gnosek perhaps has more historically knowledge about this?

**Comment by gnosek** [comment]
Unbelievable as it is, 2014 is even before my time ;)

Still, I don't think killing SunOS support is going to be too problematic :)

We could also clean up some headers but that's a separate thing. Still, if this lands (and I see no reason it shouldn't), we should remove the other SunOS bits in the same release IMO.

**Review by FedeDP — APPROVED** [review]
/approve

**Comment by Andreagit97** [comment]
> remove the other SunOS bits in the same release IMO.

@gnosek any pointer to the SunOS stuff? do you mind cleaning them if you know where they are :joy: :pray:?

**Review by Andreagit97 — APPROVED** [review]
/approve

**Comment by gnosek** [comment]
@Andreagit97 https://github.com/falcosecurity/libs/pull/1172 is what I had in mind

**Comment by Andreagit97** [comment]
thank you!

**Comment by deepskyblue86** [comment]
A little note: if you happen to use `ninja` it might kill your box because dependencies will be built with default parallel jobs.

**Pull request merged**
