### PR TITLE
update(cmake): Build zlib using CMake on Windows

### PR DESCRIPTION
**Pull request by geraldcombs**
Build zlib using CMake on Windows instead of nmake. The nmakefile passes "-base:0x5A4C0000" to the linker, which is too small on Arm64 and not really needed or wanted on any platform these days.

https://github.com/madler/zlib/issues/325

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

/kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area API-version

/area build

> /area CI

> /area driver-kmod

> /area driver-bpf

> /area driver-modern-bpf

> /area libscap-engine-bpf

> /area libscap-engine-gvisor

> /area libscap-engine-kmod

> /area libscap-engine-modern-bpf

> /area libscap-engine-nodriver

> /area libscap-engine-noop

> /area libscap-engine-source-plugin

> /area libscap-engine-savefile

> /area libscap

> /area libpman

> /area libsinsp

> /area tests

> /area proposals

**Does this PR require a change in the driver versions?**

> /version driver-API-version-major

> /version driver-API-version-minor

> /version driver-API-version-patch

> /version driver-SCHEMA-version-major

> /version driver-SCHEMA-version-minor

> /version driver-SCHEMA-version-patch

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by LucaGuerra — APPROVED** [review]

**Review by FedeDP — APPROVED** [review]
/approve

**Comment by incertum** [comment]
We likely need a rebase, thanks!

**Review by Andreagit97 — APPROVED** [review]
/approve

**Review by FedeDP — APPROVED** [review]
/approve

**Comment by FedeDP** [comment]
Ehy @geraldcombs it seems like this PR broke master CI:
> CI Build / build-libs-others-amd64 😨 (windows-latest, MultiThreaded) (push) Failing after 5m

Can you give it a look?

**Comment by geraldcombs** [comment]
> Ehy @geraldcombs it seems like this PR broke master CI:
> 
> > CI Build / build-libs-others-amd64 😨 (windows-latest, MultiThreaded) (push) Failing after 5m
> 
> Can you give it a look?

Fix inbound in #1940.

**Pull request merged**
