### PR TITLE
sync: release 0.10.3

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind bug

**Any specific area of the project related to this PR?**

**Does this PR require a change in the driver versions?**

**What this PR does / why we need it**:

Cherrypicks PR #850 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by Andreagit97 — APPROVED** [review]
/approve

**Review by jasondellaluce — APPROVED** [review]
/approve

**Review by leogr — APPROVED** [review]

**Comment by FedeDP** [comment]
Closing and reopening to trigger poiana...
/close

**Comment by FedeDP** [comment]
Latest commit adds a fake (empty) `test-drivers-x86` job to bear with required status checks on prow.

**Review by Andreagit97 — APPROVED** [review]
/approve

**Review by LucaGuerra — APPROVED** [review]

**Pull request merged**
