### PR TITLE
refactor(userspace/libsinsp): update filter parser and grammar to accept embedded expressions after boolean operators

### PR DESCRIPTION
**Pull request by jasondellaluce**
**What type of PR is this?**

/kind feature

**Any specific area of the project related to this PR?**

/area libsinsp

/area tests

**What this PR does / why we need it**:

This updates the filter parser inside libsinsp to accept cases where embedded expressions (starting with `(`) follow a boolean operator (`and`, `or`, `not`) without leaving a whitespace. The parser is currently very strict and always requires a whitespace after boolean operators, but that's an unnecessary constraint towards the non-ambiguity of the parsing language.

With this, filters such as `evt.num > 0 and(proc.name = 'cat')` are correctly parsed and accepted. 

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
refactor(userspace/libsinsp): update filter parser and grammar to accept embedded expressions after boolean operators
```

### CODE REVIEW

**Comment by FedeDP** [comment]
> This updates the filter parser inside libsinsp to accept cases where embedded expressions (starting with () follow a boolean operator (and, or, not) without leaving a whitespace

Mmmh i am not sure about this one, i quite like the idea of having the blank space as separator. 
But i have no strong opinions.
@leogr wdyt?

**Comment by jasondellaluce** [comment]
This only applies for the open parenthesis case, for every other case the white space will still be required. See the added test to see what this looks like. Happy to have feedback!

I'm not strong about this changes, but I think they would be have some value. I think this was supported by the previous parser too, so the goal here is to lead to less to none breaking changes in existing filters/rules.

**Comment by FedeDP** [comment]
> This only applies for the open parenthesis case, for every other case the white space will still be required

Yep i understood that!
> I think this was supported by the previous parser too, so the goal here is to lead to less to none breaking changes in existing filters/rules.

Uh, then we must keep previous behavior :)

**Review by FedeDP — APPROVED** [review]
/approve

**Review by Andreagit97 — APPROVED** [review]
/approve

**Pull request merged**
