### PR TITLE
update(userspace)!: support state access and event parsing in plugin API

### LINKED ISSUE #991: [New Feature] Standardize state management and support it in plugin API
**Description**

In the tech stack of Falco and its libraries, the whole architecture is event-driven and mostly functionally stateless, with the only exception being libsinsp. Among the many responsibilities and features of libsinsp, the most important is for certain state management. Libsinsp consumes every event collected by drivers and plugins and maintains an internal eventually-consistent cache representing the machine's state, which includes all the threads, file descriptors, containers, infrastructure info, etc.

Whoever worked on the libs codebase for a good amount of time is likely aware that the way state management is currently implemented is sticky, strongly coupled, and quite fragile. This is one of the biggest parts of technical debt that the libraries suffer from, it prevents us from cleaning up the API interfaces for all the consumers, and makes it increasingly harder to introduce new features.

**Feature**

This issue aims to track the effort of introducing a standard and long sustainable way for defining stateful components inside libsinsp and to make them accessible from other actors. Nonetheless, the highest priority is to not introduce performance regressions in any of the hot paths in which the current stateful components are involved. Additionally, we should avoid introduce excessive breaking changes for libraries consumers (ideally, we should not introduce any breaking change at all). The end goal is to walk the first steps toward a stable API for libsinsp itself, as the state management components are the biggest blockers for that.

**Implications for the plugin API**

The core purpose of the plugin API is to allow the libraries to be extended. Given the domain complexity that state management inevitably introduces, the effort of bringing stateful capabilities in the plugin system has been delayed since it launch. As such, the goal that I foresee for this initiative is to introduce a solution that would functionally work for both libsinsp and the plugin API, with adequate levels of simplifications.

For more context, this has been requested and discussed multiple times over the past year. Relevant links are:
- https://kubernetes.slack.com/archives/CMWH3EH32/p1644507264083289
- https://kubernetes.slack.com/archives/CMWH3EH32/p1643838967857299
- https://github.com/falcosecurity/plugins/issues/85
- https://github.com/falcosecurity/falco/issues/1704

### PR DESCRIPTION
**Pull request by jasondellaluce**
**What type of PR is this?**

/kind design

/kind feature

**Any specific area of the project related to this PR?**

/area libsinsp

/area tests

**Does this PR require a change in the driver versions?**

No

**What this PR does / why we need it**:

This follows up the work started with #1078. Now that libsinsp provides a standardized way of interacting with its internal state tables, we can update the plugin API to leverage it. This PR contributes to the plugin system with the following:
- Refactor some types to be more robust and less ambiguous (e.g. having a platform agnostic representation for booleans)
- Create APIs for the plugin to do inversion of control and invoke methods of its owner (e.g. an inspector)
- Create APIs for the plugin to access an inspector's state tables for read, write, and discovery purposes
  - Plugins are also able to define their own state tables and register them in the inspector
  - Cross-plugin state table access is supported
- The field extraction capability has been extended for leveraging the state access APIs
- A new capability has been added for "parsing events", which hooks into the event parsing phase of libsinsp, with access to the state tables API as well
- Tests, tests, and examples

**Which issue(s) this PR fixes**:

Fixes #991
Fixes https://github.com/falcosecurity/plugins/issues/85

**Special notes for your reviewer**:

700+ LOC are dedicated to tests.

**Does this PR introduce a user-facing change?**:

```release-note
update(userspace)!: support state access and event parsing in plugin API
```

### CODE REVIEW

**Review by leogr — COMMENTED** [review]
First, this is incredible! Whoa! :star_struck: 

Second too hard to check in detail :sweat_smile: , but overall, SGTM.

I reserve some time for another check, then I will give my approval :+1:

**Comment by jasondellaluce** [comment]
Integrated all the naming suggestions from @leogr (🙏 ) and rebased on top of master.

**Review by Andreagit97 — APPROVED** [review]
/approve

**Review by leogr — APPROVED** [review]
:+1:

**Pull request merged**
