### PR TITLE
chore(userspace/libsinsp): expose plugin schema in sinsp_plugin::info vector returned by plugin_infos()

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

/kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

> /area driver-kmod

> /area driver-ebpf

> /area libscap

/area libsinsp

> /area tests

> /area proposals

**What this PR does / why we need it**:

This allows consumers to also print plugin schema when eg: listing plugins. 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by FedeDP** [comment]
As a self documentation, perhaps it would be useful to call `list_open_params()` for source plugins too, and returning the list of possible open params?

**Comment by jasondellaluce** [comment]
I think `list_open_params` is a bit different, because unlike infos it has to be called after `init()`.

**Comment by FedeDP** [comment]
Yeah, and while schema is already retrieved, `list_open_params` is never called (ie: i'd have to call it for each plugin in place in `get_plugin_infos`, and it can lead to terrible performance).
That is exactly why i avoided adding it for now.

**Comment by FedeDP** [comment]
This can be closed IMO; it gives no value considering that you can call "sinsp::get_plugins()" API and have access to full plugin API.

**Pull request closed without merging**
