### PR TITLE
chore(userspace): link static `libelf` when using `BUNDLED_DEPS`

### PR DESCRIPTION
**Pull request by Andreagit97**
**What type of PR is this?**

/kind feature

**Any specific area of the project related to this PR?**

/area build

**Does this PR require a change in the driver versions?**

No

**What this PR does / why we need it**:

This PR ensures that `libelf` is statically linked when we build with `BUNDLED_DEPS`.  `BUNDLED_DEPS` are used when we build for example tar packages so we prefer to have always static libraries in order to ship the package without system dependencies

Moreover this PR adds `libbpf` as a cmake component since we don't want to use this folder during the packaging phase with `cpack`

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by leogr — APPROVED** [review]
LGTM

**Review by FedeDP — APPROVED** [review]
/approve

**Pull request merged**
