### PR TITLE
update(OWNERS): add Federico Di Pierro (fededp) to OWNERS

### PR DESCRIPTION
**Pull request by FedeDP**
Signed-off-by: Federico Di Pierro <nierro92@gmail.com>

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

/kind documentation

> /kind failing-test

> /kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area build

> /area driver-kmod

> /area driver-ebpf

> /area libscap

> /area libsinsp

> /area tests

> /area proposals

**What this PR does / why we need it**:
I am proposing myself as a maintainer: during the last few months i have been quite busy fixing eBPF issues, improving overall code quality and implementing both fixes and new features on the libs repository.
Moreover, i engaged as much as i could with the community by answering issues both on github and on the Falco slack channel, whenever i had an answer.
Finally, i am helping other maintainers taking a breath by actively reviewing PRs (even if my approval has no value right now!)
I feel this is the right time to step up my contributions and assume this important role for the project!

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by leodido — APPROVED** [review]

**Review by gnosek — APPROVED** [review]

**Comment by leogr** [comment]
Hey, @FedeDP I have sent you a GitHub invitation to the Falcosecurity Github org. Ping me once you accept it :)

Ofc, huge +1 for me :partying_face:

**Comment by FedeDP** [comment]
Aaaan accepted @leogr !

Btw thanks @leodido and @gnosek for your trust :)

**Review by leogr — APPROVED** [review]
/approve


Welcome! :partying_face:

**Pull request merged**
