### PR TITLE
new(event_table): add a new plugin category 

### PR DESCRIPTION
**Pull request by Andreagit97**
**What type of PR is this?**

/kind feature

**Any specific area of the project related to this PR?**

/area driver-kmod

/area tests

**Does this PR require a change in the driver versions?**

No

**What this PR does / why we need it**:

 This PR adds a new event category called `EC_PLUGIN`

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
new(event_table): add a new plugin category
```

### CODE REVIEW

**Review by FedeDP — APPROVED** [review]
/approve

**Review by leogr — APPROVED** [review]
:heart:

**Comment by Andreagit97** [comment]
just amended the last commit to refresh the CI

**Review by FedeDP — APPROVED** [review]
/approve

**Review by leogr — APPROVED** [review]
:heart:

**Pull request merged**
