### PR TITLE
update(build): allow gvisor compilation toggle -DBUILD_LIBSCAP_GVISOR

### PR DESCRIPTION
**Pull request by LucaGuerra**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test
/kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area build

> /area driver-kmod

> /area driver-ebpf

> /area libscap

> /area libsinsp

> /area tests

> /area proposals

**What this PR does / why we need it**:

Currently, libscap includes library functions useful for gVisor message ingestion by default that depend on libraries that might take a long time to compile such as protobuf (which is also required by libsinsp). For some use cases, it is not necessary to build this support, for example when only a lightweight version of libscap is necessary that only interfaces with the ebpf probe or kernel module, such as the `scap-open` example.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jasondellaluce** [comment]
LGTM!

**Review by FedeDP — APPROVED** [review]
/approve

**Review by Andreagit97 — APPROVED** [review]
/approve

**Review by FedeDP — APPROVED** [review]

**Pull request merged**
