### PR TITLE
cleanup(ci): use new kernel-testing provided composite action.

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind cleanup

**Any specific area of the project related to this PR?**

/area CI

**Does this PR require a change in the driver versions?**

**What this PR does / why we need it**:

Moreover, bumped the framework to v0.3.0.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by FedeDP** [comment]
I will use this branch to start kernel-tests CI and check that everything is ok before unholding.

**Review by Andreagit97 — APPROVED** [review]
/approve

**Review by jasondellaluce — APPROVED** [review]
/approve

**Review by jasondellaluce — APPROVED** [review]
/approve

**Comment by FedeDP** [comment]
>  Drivers CI Build / test-drivers-arm64 😇 (bundled_deps) (pull_request) Queued — Waiting to run this check... 

Sigh

**Pull request merged**
