### PR TITLE
cleanup(libsinsp): throw exception for invalid parsed string vectors

### PR DESCRIPTION
**Pull request by LucaGuerra**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind cleanup

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area libsinsp

**Does this PR require a change in the driver versions?**

No

**What this PR does / why we need it**:

After https://github.com/falcosecurity/libs/pull/1800 we want to make sure that what we receive from the drivers is actually what we expect. So, I've changed the way we parse those kind of parameters to check for the NUL terminator, and added a shorthand helper to convert the parameter from buffer to vector.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by LucaGuerra** [comment]
I would propose to add this to 0.16.0, this way during testing we will more easily notice any failures in the drivers due to any issue with #1800

**Review by FedeDP — APPROVED** [review]
/approve

**Review by Andreagit97 — APPROVED** [review]
/approve

**Pull request merged**
