### PR TITLE
update(userspace/plugin): bump plugin API version to 2.0.0

### PR DESCRIPTION
**Pull request by jasondellaluce**
**What type of PR is this?**

/kind documentation

/kind feature

**Any specific area of the project related to this PR?**

/area API-version

**Does this PR require a change in the driver versions?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Linked to https://github.com/falcosecurity/falco/issues/2074, this updates the plugin API to regulate and document the concurrency constraints of the API symbols. Few outdated descriptions have been updated too.

This changes require a minor API version bump to 1.1.0, because this doesn't introduce a breaking change (older frameworks will still load the concurrency-compliant new plugins). 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
update(userspace/plugin): bump plugin API version to 2.0.0
```

### CODE REVIEW

**Comment by jasondellaluce** [comment]
Actually, we need to bump to `2.0.0` to properly prevent old plugins to be loaded in newer versions of the framework. This is needed to avoid data races on old plugins that don't support concurrency.

**Review by Andreagit97 — APPROVED** [review]
/approve

**Comment by jasondellaluce** [comment]
Holding this until we have stable support for multi-source in Falco and we know for sure that these docs are enough for the requirements. At the same time, we delay breaking changes on master for existing released plugins.

**Review by Andreagit97 — APPROVED** [review]
/approve

**Pull request merged**
