### PR TITLE
cleanup(scap,sinsp): assorted cleanups

### PR DESCRIPTION
**Pull request by gnosek**
This is a collection of random cleanups I came across. Nothing too groundbreaking but maybe nice to have:

Some basic proclist tests for test_input and savefile (these have complicated relationships with platforms):

* new(tests): sanity check for test_input proc table
* new(tests): basic savefile test

An unnecessary include:

* cleanup(scap): remove unneeded #include

A small cmake cleanup:

 * cleanup(scap): do not use an intermediate cmake var

Removing a few unused libscap functions:

* cleanup(scap): remove unused scap_proc_add
* cleanup(scap): remove unused scap_retrieve_machine_info
* cleanup(scap): remove unused scap_create_iflist
* cleanup(scap): remove scap_get_os_platform

The last one is both unused and misleading: it takes a handle, which might imply that, when reading a capture file, it will return the os/arch the capture was made on. It does nothing of the sort and returns a compile time constant instead.

I have a patch queued that stores the os/arch information in the capture file itself, which would allow for reliable information (exposed via machine_info). WDYT? Do we want this or do I drop it?

Remove an unused variable, shadowing an actually used one:

 * cleanup(scap): remove dead variable

Clean up sinsp_dumper a little:

* cleanup(sinsp): DRY dumper code a tiny bit
* cleanup(sinsp): don't hold an inspector in sinsp_network_interfaces
* cleanup(sinsp): make m_network_interfaces an instance, not pointer
* cleanup(sinsp): sinsp doesn't need sinsp_network_interfaces to be a friend

Reduce the number of raw pointers and the dependency on `sinsp` (or, to be precise, on an `m_inspector` field)

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area API-version

> /area build

> /area CI

> /area driver-kmod

> /area driver-bpf

> /area driver-modern-bpf

> /area libscap-engine-bpf

> /area libscap-engine-gvisor

> /area libscap-engine-kmod

> /area libscap-engine-modern-bpf

> /area libscap-engine-nodriver

> /area libscap-engine-noop

> /area libscap-engine-source-plugin

> /area libscap-engine-savefile

> /area libscap-engine-udig

> /area libscap

> /area libpman

> /area libsinsp

> /area tests

> /area proposals

**Does this PR require a change in the driver versions?**

> /version driver-API-version-major

> /version driver-API-version-minor

> /version driver-API-version-patch

> /version driver-SCHEMA-version-major

> /version driver-SCHEMA-version-minor

> /version driver-SCHEMA-version-patch

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
cleanup(scap)!: removed scap_create_iflist
cleanup(scap)!: removed scap_retrieve_machine_info
cleanup(scap)!: removed scap_get_os_platform
cleanup(scap)!: removed scap_proc_add
```

### CODE REVIEW

**Review by incertum — APPROVED** [review]
/approve

**Review by FedeDP — APPROVED** [review]
/approve

**Comment by FedeDP** [comment]
@gnosek needs a rebase here :) Then we can proceed!

**Review by Andreagit97 — APPROVED** [review]
/approve

**Pull request merged**
