### PR TITLE
fix(build): set gtest tag instead of using main

### PR DESCRIPTION
**Pull request by LucaGuerra**
Signed-off-by: Luca Guerra <luca@guerra.sh>

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area build

> /area driver-kmod

> /area driver-bpf

> /area driver-modern-bpf

> /area libscap-engine-bpf

> /area libscap-engine-gvisor

> /area libscap-engine-kmod

> /area libscap-engine-modern-bpf

> /area libscap-engine-nodriver

> /area libscap-engine-noop

> /area libscap-engine-source-plugin

> /area libscap-engine-udig

> /area libscap

> /area libsinsp

> /area tests

> /area proposals

**What this PR does / why we need it**:

This PR sets GoogleTest to v1.12.1, which is also the latest release to support C++11 (https://github.com/google/googletest/releases/tag/release-1.12.1).

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
fix(build): set GoogleTest version v1.12.1
```

### CODE REVIEW

**Comment by FedeDP** [comment]
Thank you!
/ok-to-test

**Review by FedeDP — APPROVED** [review]
/approve

**Review by Andreagit97 — APPROVED** [review]
/approve

**Comment by FedeDP** [comment]
Prow :sleeping:

**Review by leogr — APPROVED** [review]
:+1:

**Pull request merged**
