### PR TITLE
update luajit to let Falco use same luajit as libs

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind cleanup

**Any specific area of the project related to this PR?**

/area build

**What this PR does / why we need it**:

This PR updates luajit version to allow Falco to use the luajit provided by libs.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
build: upgrade luajit to commit f3c856915b4ce7ccd24341e8ac73e8a9fd934171 (latest available in the 2.1 branch)
```

### CODE REVIEW

**Review by fntlnz — APPROVED** [review]

**Review by leogr — APPROVED** [review]
:partying_face: 
/approve

**Comment by leogr** [comment]
Something strange happened with this PR :point_down: 
Screenshot from 2021-11-17 12-14-09

But commits have been already merged by @poiana into `master` :point_down: 

Screenshot from 2021-11-17 12-15-22

It seems a GitHub problem. I will try to investigate, anyway atm I don't have any idea how to fix it (eventually, we could just not fix it since the commits went to the right place).

**Comment by leogr** [comment]
I have looked into both webhooks and audit logs, but I have not found any clue. The commits are actually merged by @poiana but for some reasons, GitHub did not notice that.

cc @maxgio92 

Closing, since this PR is in practice already merged into `master`.
/close

**Pull request closed without merging**
