### PR TITLE
Fix random build warnings

### PR DESCRIPTION
**Pull request by gnosek**
**What type of PR is this?**

> /kind cleanup

**Any specific area of the project related to this PR?**

> /area build

**Does this PR require a change in the driver versions?**

**What this PR does / why we need it**:

This PR fixes a bunch of warnings I hit. Nothing too groundbreaking, but a tiny step forward to building with -Werror :)

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by LucaGuerra — APPROVED** [review]
LGTM

**Review by incertum — APPROVED** [review]
/approve

**Comment by LucaGuerra** [comment]
Thanks for the question :sweat_smile: 

I think the fixes make sense and make libs easier to build for consumers. They can go in 0.11.0 ! Of course, Falco builds just fine!

/milestone 0.11.0

**Pull request merged**
