### PR TITLE
chore(libs): fix -Werror=unused-variable

### PR DESCRIPTION
**Pull request by clan**
**What type of PR is this?**

/kind bug

**Any specific area of the project related to this PR?**

/area build

**Does this PR require a change in the driver versions?**

No

**What this PR does / why we need it**:

otherwise test will give wrong result if compiler has -Werror flags, complained with:

  error: unused variable 'g_ppm_class' [-Werror=unused-variable]

**Does this PR introduce a user-facing change?**:

No

```release-note
NONE
```

### CODE REVIEW

**Comment by FedeDP** [comment]
Thanks for this fix! Please note that CI issues are not caused by your PR; they are caused by https://github.com/falcosecurity/libs/pull/2053 that (correctly) enabled `BUILD_WARNINGS_AS_ERRORS` in CI.

Also, i think your fix is valuable for next driver release!
/milestone 7.3.0+driver

**Comment by FedeDP** [comment]
Hi! Can you rebase on latest master to fix the CI? :) thank you!

**Comment by clan** [comment]
> Hi! Can you rebase on latest master to fix the CI? :) thank you!

done.

**Review by FedeDP — APPROVED** [review]
/approve

**Review by LucaGuerra — APPROVED** [review]

**Comment by hhoffstaette** [comment]
Out of curiosity, why does the cast fix this problem? It's side-effect-free and the compiler could still be allowed to delete everything except the return value.

**Comment by clan** [comment]
> Out of curiosity, why does the cast fix this problem? It's side-effect-free and the compiler could still be allowed to delete everything except the return value. **Edit**: this is not just a common convention/compatibility feature but actually in the [C standard](https://cplusplus.github.io/CWG/issues/1054.html). 🧐

I think it's harmless for the feature test code, which won't cause run-time problem. I'm not sure whether there are any side effect (performance, etc.), may be depend on optimization level? What's the difference when compare to compiler's attribute (___attribute((unused)))? Will do more research when have time (by compare the generated asm code).

**Comment by hhoffstaette** [comment]
> I'm not sure whether there are any side effect (performance, etc.), may be depend on optimization level? What's the difference when compare to compiler's attribute (___attribute((unused)))?

I put it into CompilerExplorer [here](https://godbolt.org/z/4z3reecqf) and as expected there is no difference between the cast and ((unused)). As soon as you enable `-O` the store is optimized away (also expected). I've used ((unused)) before; my question was purely whether the void cast is some kind of historic convention that all compilers implement to be compatible with each other, or whether this is specified somewhere. Turns out it is. :)

**Pull request merged**
