### PR TITLE
wip: abstract platform-specific libscap code

### PR DESCRIPTION
**Pull request by gnosek**
**Don't mind me, I'm just here for the CI** :)

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

/kind cleanup

/kind design

> /kind documentation

> /kind failing-test

> /kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area API-version

> /area build

> /area driver-kmod

> /area driver-bpf

> /area driver-modern-bpf

> /area libscap-engine-bpf

> /area libscap-engine-gvisor

> /area libscap-engine-kmod

> /area libscap-engine-modern-bpf

> /area libscap-engine-nodriver

> /area libscap-engine-noop

> /area libscap-engine-source-plugin

> /area libscap-engine-udig

/area libscap

> /area libpman

> /area libsinsp

> /area tests

> /area proposals

**Does this PR require a change in the driver versions?**

> /version driver-API-version-major

> /version driver-API-version-minor

> /version driver-API-version-patch

> /version driver-SCHEMA-version-major

> /version driver-SCHEMA-version-minor

> /version driver-SCHEMA-version-patch

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

Please don't look at this quite yet :) 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by FedeDP** [comment]
Is this a duplicate of #636 ?

**Comment by gnosek** [comment]
@FedeDP no, it's my garbage PR to use the Windows CI ;) Once I clean it all up and I'm happy with the changes, I'll submit them as proper PRs and close this one (though it will hopefully get rebased down to nothing over time).

**Comment by gnosek** [comment]
This PR has served its purpose, I'll close it now.

**Pull request closed without merging**
