### PR TITLE
update(driver): updated report format.

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind cleanup

**Any specific area of the project related to this PR?**

**Does this PR require a change in the driver versions?**

**What this PR does / why we need it**:

Just UX updates for driver report.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by Andreagit97 — APPROVED** [review]
/approve
:heart_eyes:

**Review by LucaGuerra — APPROVED** [review]
:man_artist:

**Comment by FedeDP** [comment]
Poiana :skull:

**Pull request merged**
