### PR TITLE
refactor(userspace/libsinsp)!: drop support to protodecoders

### PR DESCRIPTION
**Pull request by jasondellaluce**
**What type of PR is this?**

/kind cleanup

**Any specific area of the project related to this PR?**

/area libsinsp

**Does this PR require a change in the driver versions?**

**What this PR does / why we need it**:

Protodecoders are an ancient internal-only code instrument for implementing protocol decoders, which was introduced with the intention of supporting many. Over ~9 years, the only implementation we had for it is implementing the `syslog.*` fields. So, this proposes to remove protodecoders and implement those field in a simpler, more maintainable, and performant way (with no callback tangle).

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
refactor(userspace/libsinsp)!: drop support to protodecoders
```

### CODE REVIEW

**Review by FedeDP — APPROVED** [review]
/approve

**Comment by LucaGuerra** [comment]
I see that there is a `!` in the list, what's the breaking change for the consumers of libs? I assume that it is the fact that it was technically possible to use protodecoders before (but nobody did).

**Review by LucaGuerra — APPROVED** [review]
LGTM

**Comment by jasondellaluce** [comment]
> I see that there is a ! in the name, what's the breaking change for the consumers of libs? I assume that it is the fact that it was technically possible to use protodecoders before (but nobody did).

This. You never know.

**Pull request merged**
