### PR TITLE
update(build): update libcurl to 8.7.1

### PR DESCRIPTION
**Pull request by LucaGuerra**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind feature

**Any specific area of the project related to this PR?**

/area build

**Does this PR require a change in the driver versions?**

No

**What this PR does / why we need it**:

Yesterday a an update with security content was released for libcurl. This integrates the latest fixes.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by FedeDP — APPROVED** [review]
/approve

**Review by Andreagit97 — APPROVED** [review]
/approve

**Comment by FedeDP** [comment]
> [ RUN      ] async_key_value_source_test.prune_old_metadata
pure virtual method called
terminate called without an active exception
Aborted

:/

**Pull request merged**
