### PR TITLE
fix(sinsp): Support 'mmap' and 'mmap2' system calls filtering by fd values

### PR DESCRIPTION
**Pull request by eddyduer-sysdig**
**What type of PR is this?**

/kind bug

**Any specific area of the project related to this PR?**

/area driver-kmod

/area driver-bpf

/area driver-modern-bpf

/area libsinsp

**Does this PR require a change in the driver versions?**

/version driver-SCHEMA-version-minor

**What this PR does / why we need it**:

Parser assumed that FD is always first. For mmap and mmap2 this is not the case, so parsing using any of the FD fields (e.g. fd.name) did not work

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
fix: filtering for 'mmap' and 'mmap2' using fd values
```

### CODE REVIEW

**Review by jasondellaluce — COMMENTED** [review]
Hey @eddyduer-sysdig thanks for the contribution. Few points for proceeding:
- If the PR is ready for review, please remove the Draft status so that other maintainers will know they can take a look
- Make sure you [sign-off](https://github.com/falcosecurity/.github/blob/main/CONTRIBUTING.md#developer-certificate-of-origin) all your commit as that's a requirement for our governance

@FedeDP do we usually bump the SCHEMA version minor/patch when we change the `EF_*` flags of events, like in this case?

**Review by Andreagit97 — APPROVED** [review]
/approve

**Review by FedeDP — APPROVED** [review]
/approve

**Pull request merged**
