### PR TITLE
sync: cherry pick for 0.14.2

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind cleanup

**Any specific area of the project related to this PR?**

/area libsinsp

**Does this PR require a change in the driver versions?**

**What this PR does / why we need it**:

Cherry picks https://github.com/falcosecurity/libs/pull/1645 from master.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by jasondellaluce — APPROVED** [review]
/approve

**Review by LucaGuerra — APPROVED** [review]

**Review by leogr — APPROVED** [review]

**Comment by FedeDP** [comment]
Why jobs are not triggering? Trying to close and reopne.
/close

**Comment by FedeDP** [comment]
STARTED!

**Pull request merged**
