### PR TITLE
fix(libsinsp): check ipvXnet size before comparing

### PR DESCRIPTION
**Pull request by LucaGuerra**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area libsinsp

**Does this PR require a change in the driver versions?**

No

**What this PR does / why we need it**:

Very similar to https://github.com/falcosecurity/libs/pull/1953 but in the "fd.net" part of the filterchecks. In this case we could get a type confusion for the parameter value, leading to an incorrect comparison (ipv4 vs ipv6).

We still need tests for these cases because they are very tricky.

cc @jasondellaluce , can you think of other places where this may happen?

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
fix(libsinsp): check ipv4/ipv6 size on fd.*net comparisons
```

### CODE REVIEW

**Review by jasondellaluce — APPROVED** [review]

**Comment by jasondellaluce** [comment]
>  can you think of other places where this may happen?

Good catch! I think this is the last instance of this, and also a friendly reminder that we'll need to stop having edge-cases for comparisons.

**Review by Andreagit97 — COMMENTED** [review]
Can we add some tests for these cases? Maybe we will figure out other issues :/

**Review by Andreagit97 — APPROVED** [review]
/approve

**Review by jasondellaluce — APPROVED** [review]

**Pull request merged**
