### PR TITLE
Fix some issues raised by clang-tidy

### PR DESCRIPTION
**Pull request by deepskyblue86**
**What type of PR is this?**

/kind bug

**Any specific area of the project related to this PR?**

/area libscap

/area libsinsp

**Does this PR require a change in the driver versions?**

**What this PR does / why we need it**:
Fix some issues raised by clang-tidy with `clang-analyzer-cplusplus-*` checks.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by FedeDP — APPROVED** [review]
/approve

**Review by LucaGuerra — APPROVED** [review]

**Comment by FedeDP** [comment]
We need to fix CI :/ then this need a rebase and can get merged! Sorry for the inconvenience!

**Comment by FedeDP** [comment]
Can you rebase on latest master? Now ci is fixed.

**Review by Andreagit97 — APPROVED** [review]
/approve

**Review by FedeDP — APPROVED** [review]
/approve

**Pull request merged**
