### PR TITLE
update(cmake): Make sure libscap.pc matches our install behavior

### PR DESCRIPTION
**Pull request by geraldcombs**
Use the same LIBSCAP_INSTALL_LIBS for our install targets and as the starting point for our pkgconfig linker flags.

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

/kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area API-version

/area build

> /area CI

> /area driver-kmod

> /area driver-bpf

> /area driver-modern-bpf

> /area libscap-engine-bpf

> /area libscap-engine-gvisor

> /area libscap-engine-kmod

> /area libscap-engine-modern-bpf

> /area libscap-engine-nodriver

> /area libscap-engine-noop

> /area libscap-engine-source-plugin

> /area libscap-engine-savefile

> /area libscap-engine-udig

/area libscap

> /area libpman

> /area libsinsp

> /area tests

> /area proposals

**Does this PR require a change in the driver versions?**

> /version driver-API-version-major

> /version driver-API-version-minor

> /version driver-API-version-patch

> /version driver-SCHEMA-version-major

> /version driver-SCHEMA-version-minor

> /version driver-SCHEMA-version-patch

**What this PR does / why we need it**:

This ensures that our libscap pkgconfig linker flags match our installed libraries.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by gnosek** [comment]
We're trying to link scap_error and scap_engine_util as dynamic libraries (on Linux at least) but tbh I like this approach a lot. Big :+1: from me once we figure out the failing linux build!

**Comment by gnosek** [comment]
@geraldcombs how about this?

```
diff --git a/cmake/modules/libscap.cmake b/cmake/modules/libscap.cmake
index 979243642..a20cb0738 100644
--- a/cmake/modules/libscap.cmake
+++ b/cmake/modules/libscap.cmake
@@ -94,7 +94,7 @@ foreach(libscap_install_lib ${LIBSCAP_INSTALL_LIBS})
        get_target_property(install_lib_link_libraries ${libscap_install_lib} LINK_LIBRARIES)
        foreach (install_lib_link_library ${install_lib_link_libraries})
                if (NOT ${install_lib_link_library} IN_LIST libscap_conditional_libs)
-                       list(APPEND libscap_link_libraries ${install_lib_link_libraries})
+                       list(APPEND libscap_link_libraries ${install_lib_link_library})
                endif()
        endforeach()
 endforeach()
```

**Comment by geraldcombs** [comment]
I found a way to automatically build our install library and link flag lists. Assuming the tests pass I should be done making changes to the PR.

**Comment by FedeDP** [comment]
Let's try 
/milestone 0.12.0

Even if we are very very close to the tag.
Thank you for the patch @geraldcombs, our CMake hero :D

**Comment by FedeDP** [comment]
@gnosek PTAL :)

**Review by FedeDP — APPROVED** [review]
LGTM; test `build-shared-libs-linux-amd64` is passing; also, can we expand the test to osx and win too?
I would love it!
Anyway, we can do it in a follow up PR.
/approve

**Review by LucaGuerra — APPROVED** [review]

**Pull request merged**
