### PR TITLE
Sync/release 0.10.2

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind bug

**Any specific area of the project related to this PR?**

/area libsinsp

**Does this PR require a change in the driver versions?**

**What this PR does / why we need it**:

Cherrypicks #841 for 0.10.2 release.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by Andreagit97 — APPROVED** [review]
/approve

**Review by jasondellaluce — APPROVED** [review]
/approve

**Review by leogr — APPROVED** [review]

**Comment by FedeDP** [comment]
Note: there is no `test-drivers-x86` job on this branch, although it is a required job by poiana.
How should we proceed? @leogr 
Shall we add a `test-drivers-x86` job on this branch that does nothing?

**Pull request merged**
