### PR TITLE
cleanup(driver): create consistencies (syscall_arg_t)

### PR DESCRIPTION
**Pull request by ecbadeaux**
**What type of PR is this?**

/kind bug

/kind cleanup

**Any specific area of the project related to this PR?**

/area driver-kmod

**Does this PR require a change in the driver versions?**

No.

**What this PR does / why we need it**:

Use more consistent types and standards across the dirver code base.

**Which issue(s) this PR fixes**:

part of #902
(partial fix other issues still remain in 902)

**Special notes for your reviewer**:

Tagging @dwindsor @incertum  for visibility.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by incertum — APPROVED** [review]
/approve

**Review by Andreagit97 — APPROVED** [review]
/approve

**Comment by Andreagit97** [comment]
Thank you for this!

**Pull request merged**
