### PR TITLE
chore(driver): bump API driver version

### PR DESCRIPTION
**Pull request by Andreagit97**
Signed-off-by: Andrea Terzolo <andrea.terzolo@polito.it>

**What type of PR is this?**

/kind feature

**Any specific area of the project related to this PR?**

/area build

**What this PR does / why we need it**:

Due to the changes in https://github.com/falcosecurity/libs/pull/414, there is a breaking change in the interface between driver and libs so we need to bump the driver API version

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by gnosek** [comment]
If only we kept the original field ordering in #414 (added the new fields at the end). Also, this really belongs to the original PR but there's nothing we can do about it now.

poiana, will you pick this up? ⬇️ 

/approve

**Comment by Andreagit97** [comment]
> If only we kept the original field ordering in #414 (added the new fields at the end). Also, this really belongs to the original PR but there's nothing we can do about it now.

Yeah, we must find a way to remember it every time :/ 

> poiana, will you pick this up? arrow_down
> 
> /approve

**Review by FedeDP — DISMISSED** [review]
/approve

**Comment by gnosek** [comment]
How about an entry in the PR template?

API version increased:
- major
- minor
- patch
- not needed

(same for schema version). Fancy automation could come later.

**Comment by FedeDP** [comment]
I think we should also bump `SCAP_MINIMUM_DRIVER_API_VERSION` @Andreagit97

**Comment by Andreagit97** [comment]
> How about an entry in the PR template?
> 
> API version increased:
> 
>     * major
> 
>     * minor
> 
>     * patch
> 
>     * not needed
> 
> 
> (same for schema version). Fancy automation could come later.

I have done something similar, but this is just a proposal let me know if it sounds good to you :) @gnosek @FedeDP @leogr

**Comment by FedeDP** [comment]
I like it!

**Review by FedeDP — APPROVED** [review]
/approve

**Review by Molter73 — APPROVED** [review]

**Pull request merged**
