### PR TITLE
tests(sinsp): Fix infer_defaults_to_first_non_loopback TC

### PR DESCRIPTION
**Pull request by SohamM-Ibm**
**What type of PR is this?**

/kind failing-test

**Any specific area of the project related to this PR?**

/area tests

**Does this PR require a change in the driver versions?**

No

**What this PR does / why we need it**:

We need to ensure the same byte order for all architectures, so added the Byte order modifiers.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by SohamM-Ibm** [comment]
The PR resolves the Test case failure observed on s390x system for `sinsp_network_interfaces.infer_defaults_to_first_non_loopback` while running the command - `make run-unit-test-libsinsp`.

```
[ RUN      ] sinsp_network_interfaces.infer_defaults_to_first_non_loopback
/home/test/sysdig/build/falcosecurity-libs-repo/falcosecurity-libs-prefix/src/falcosecurity-libs/userspace/libsinsp/test/ifinfo.ut.cpp:126: Failure
Expected equality of these values:
  "192.168.22.149"
  buf
    Which is: "127.0.0.1"

[  FAILED  ] sinsp_network_interfaces.infer_defaults_to_first_non_loopback (0 ms)
[----------] 6 tests from sinsp_network_interfaces (0 ms total)

```

**Comment by SohamM-Ibm** [comment]
@Andreagit97 May you please review.

**Review by Andreagit97 — APPROVED** [review]
Thank you for this!
/approve

**Review by LucaGuerra — APPROVED** [review]

**Pull request merged**
