### PR TITLE
cleanup(build): enable cmake CMP0135 policy

### PR DESCRIPTION
**Pull request by gnosek**
Enabling this changes the behavior of timestamps for downloaded/extracted file timestamps, but more importantly avoids a ton of cmake warnings during build.

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

/kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area API-version

/area build

> /area CI

> /area driver-kmod

> /area driver-bpf

> /area driver-modern-bpf

> /area libscap-engine-bpf

> /area libscap-engine-gvisor

> /area libscap-engine-kmod

> /area libscap-engine-modern-bpf

> /area libscap-engine-nodriver

> /area libscap-engine-noop

> /area libscap-engine-source-plugin

> /area libscap-engine-savefile

> /area libscap-engine-udig

> /area libscap

> /area libpman

> /area libsinsp

> /area tests

> /area proposals

**Does this PR require a change in the driver versions?**

> /version driver-API-version-major

> /version driver-API-version-minor

> /version driver-API-version-patch

> /version driver-SCHEMA-version-major

> /version driver-SCHEMA-version-minor

> /version driver-SCHEMA-version-patch

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by jasondellaluce — APPROVED** [review]
/approve

**Comment by FedeDP** [comment]
Hi @gnosek ! Can you rebase?

**Comment by Andreagit97** [comment]
@gnosek can we rebase this?

**Comment by gnosek** [comment]
yeah, yeah, you don't need to remind me every month :D 

seriously though, thanks for the ping, just pushed it (even though it's a clean rebase with no conflicts)

**Review by FedeDP — APPROVED** [review]
/approve

**Review by Andreagit97 — APPROVED** [review]
/approve
We needed a rebase to check if the CI was still green after 2 months! Thanks!

**Comment by gnosek** [comment]
@Andreagit97 wanna unhold?

**Pull request merged**
