### PR TITLE
Convert savefile (scap file reader) to a scap engine [3/n]

### PR DESCRIPTION
**Pull request by gnosek**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

/kind cleanup

/kind design

> /kind documentation

> /kind failing-test

> /kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

> /area driver-kmod

> /area driver-bpf

> /area driver-modern-bpf

> /area libscap-engine-bpf

> /area libscap-engine-gvisor

> /area libscap-engine-kmod

> /area libscap-engine-modern-bpf

> /area libscap-engine-nodriver

> /area libscap-engine-noop

> /area libscap-engine-source-plugin

> /area libscap-engine-udig

/area libscap

> /area libpman

> /area libsinsp

> /area tests

> /area proposals

**What this PR does / why we need it**:

This PR continues the work of abstracting all engine-specific behavior under vtables by converting scap file reading support to an engine.

Note: even though all engines now have a vtable, the "if vtable" checks aren't removed yet. I plan to do this after unifying all the distinct open paths, so that creating an engine without a vtable becomes much harder.

**Special notes for your reviewer**:

I expect n=5. I have a series on top of this one, cleaning up the platform specific behavior and then there will be a hopefully final one, removing all the accumulated cruft, like "if vtable" checks.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by leogr** [comment]
> If we can fix windows build, i am all for getting this light-reviewed and eventually merged asap, to allow us to move on!

Totally agree. 

PS @gnosek your PRs are awesome :heart_eyes:

**Comment by gnosek** [comment]
Ooh we have a Windows CI setup now, hooray! :D And I see a mac one too!

**Comment by gnosek** [comment]
Windows/Mac builds successful :)

**Review by jasondellaluce — COMMENTED** [review]
Lots of changes! I think this looks great.

**Comment by FedeDP** [comment]
Mmmh rebase needed @gnosek eheh

**Comment by gnosek** [comment]
YOLOOOOOOO ;D 🤞

**Review by FedeDP — APPROVED** [review]
/approve

Imho, this is not easy to review, but i think we can move on as quick as possible to hopefully complete the libscap refactor asap :)

**Comment by gnosek** [comment]
It should be easier if you go commit by commit, otherwise I agree, it's unreadable ;)

**Comment by FedeDP** [comment]
Yeah i tried my best at reviewing it entirely, skipping those parts that seemed really copy-pasted :)

**Comment by Andreagit97** [comment]
Agree entirely with @FedeDP I will take another look and I will probably approve, I can't wait to see the scap `v-table` completed :heart_eyes:

**Review by FedeDP — APPROVED** [review]
/approve

**Review by leogr — APPROVED** [review]

**Pull request merged**
