### PR TITLE
update(libscap): introduce new options in `scap-open` example

### PR DESCRIPTION
**Pull request by Andreagit97**
Signed-off-by: Andrea Terzolo <andrea.terzolo@polito.it>

**What type of PR is this?**

/kind feature

**Any specific area of the project related to this PR?**

/area libscap

**What this PR does / why we need it**:

This PR adds some new features to the `scap-open` example:

* enable the `kernel_simple_consumer` logic
* capture only a limited number of events (maybe also `0` to test only the BPF verifier).
* print some information about what is happening during the execution.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by FedeDP** [comment]
Nice, thanks!
/ok-to-test

**Review by FedeDP — DISMISSED** [review]
/approve

**Comment by FedeDP** [comment]
Closing and reopening to trigger poiana.
/close

**Review by FedeDP — APPROVED** [review]
/approve

Thank you! That's great!

**Review by leogr — APPROVED** [review]
:factory_worker:

**Pull request merged**
