### PR TITLE
sync: 0.10.1

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind cleanup

**Any specific area of the project related to this PR?**

**Does this PR require a change in the driver versions?**

**What this PR does / why we need it**:

Sync of release branch for 0.10.1.
It ships:
* https://github.com/falcosecurity/libs/pull/802
* https://github.com/falcosecurity/libs/pull/804
* https://github.com/falcosecurity/libs/pull/807
* https://github.com/falcosecurity/libs/pull/818
* https://github.com/falcosecurity/libs/pull/822
* #814
* https://github.com/falcosecurity/libs/pull/820
* #833 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by FedeDP** [comment]
I would try to go on and merge this; other 2 missing PRs will need some work before merging (all the test part will generate conflicts given that it is based on a new version of the driver testing framework (https://github.com/falcosecurity/libs/pull/783)

**Comment by FedeDP** [comment]
Partially merged #814, only first 2 commits, ie:
* de17488d3b7221e17cbdddd67851856bb0378976
* 1c9935b094f758ef9e5f5fec995296d3f0162ca2

Last commit implemented some tests, that depend on multiple changes on the testing framework that we are not going to port back to 0.10.x.

**Comment by FedeDP** [comment]
I tried to merge also 29c2ed191096612c40a0a41e2a6834751805fc26 as it is needed to allow modern bpf tests to build.

**Comment by FedeDP** [comment]
30bb711494ca7d489f454977da10ac4619da1d7b is needed to fix build of modern bpf tests. It is not a cherry pick.

**Review by Andreagit97 — APPROVED** [review]
/approve

**Review by LucaGuerra — APPROVED** [review]

**Pull request merged**
