### PR TITLE
new(modern_probe): Add getresuid

### PR DESCRIPTION
**Pull request by dwindsor**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

/kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area API-version

> /area build

> /area CI

> /area driver-kmod

> /area driver-bpf

/area driver-modern-bpf

> /area libscap-engine-bpf

> /area libscap-engine-gvisor

> /area libscap-engine-kmod

> /area libscap-engine-modern-bpf

> /area libscap-engine-nodriver

> /area libscap-engine-noop

> /area libscap-engine-source-plugin

> /area libscap-engine-savefile

> /area libscap-engine-udig

> /area libscap

> /area libpman

> /area libsinsp

> /area tests

> /area proposals

**Does this PR require a change in the driver versions?**

> /version driver-API-version-major

> /version driver-API-version-minor

> /version driver-API-version-patch

> /version driver-SCHEMA-version-major

> /version driver-SCHEMA-version-minor

> /version driver-SCHEMA-version-patch

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

#723 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by Andreagit97 — APPROVED** [review]
/approve

**Comment by Andreagit97** [comment]
Unfortunately we need a rebase here :/

**Review by hbrueckner — APPROVED** [review]
Thanks a lot @dwindsor !
/approve

**Review by Andreagit97 — DISMISSED** [review]
/approve
thank you :)

**Review by hbrueckner — APPROVED** [review]

**Comment by Andreagit97** [comment]
Probably is easier to rebase this one with respect to https://github.com/falcosecurity/libs/pull/905, so we could try to merge the #905 before this one, and don't worry I will rebase this when it's time since you've already done it once :(

**Review by hbrueckner — APPROVED** [review]

**Review by FedeDP — APPROVED** [review]
/approve

**Comment by Andreagit97** [comment]
just rebased :)

**Review by hbrueckner — APPROVED** [review]

**Pull request merged**
