### PR TITLE
fix(sinsp-example): handle SCAP_FILTERED_EVENT

### PR DESCRIPTION
**Pull request by deepskyblue86**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

**Any specific area of the project related to this PR?**

/area tests

**Does this PR require a change in the driver versions?**

**What this PR does / why we need it**:
Adapt `sinsp-example` to https://github.com/falcosecurity/libs/pull/674 and restore its functionality

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
See https://github.com/falcosecurity/libs/pull/674

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by deepskyblue86** [comment]
@Molter73 hopefully this would fix the e2e :slightly_smiling_face:

**Comment by FedeDP** [comment]
Yay passing! Great job man!

**Review by FedeDP — APPROVED** [review]
/approve

**Review by Molter73 — APPROVED** [review]
/lgtm

Thanks for this Angelo, I see two of the e2e tests already pass so I have no reason to believe the last one will fail. Sorry I didn't catch this before merging the CI change, but in fairness, I rebased the PR on Tuesday and by Thursday it was already broken 😞

**Comment by FedeDP** [comment]
We break at a ftl speed! :laughing:

**Comment by Molter73** [comment]
> We break at a ftl speed! 😆
Hopefully not anymore 🤣

**Pull request merged**
