### PR TITLE
Use same version in all cmake_minimum_required() statements

### PR DESCRIPTION
**Pull request by federico-sysdig**
**What type of PR is this?**

/kind cleanup
/release-note-none

**Any specific area of the project related to this PR?**

/area build

**What this PR does / why we need it**:

The project `libs` declares in several CMake files the required version of CMake.

```cmake
cmake_minimum_required(VERSION 3.5.1)
```

The values for the version are all different (`2.8.2`, `2.8.5`). The change aims at making the older ones uniform to the latest of `falcosecurity/falco`, `3.5.1`. This should also avoid some warnings that come up with newer versions of CMake.

**Does this PR introduce a user-facing change?**:
```
NONE
```

### CODE REVIEW

**Comment by Andreagit97** [comment]
The problem with these changes is that bumping the CMake version in some files the behavior of the CMake code changes and as you can see the tests are failing :(

**Comment by incertum** [comment]
Kindly checking in on the status, thank you!

**Comment by federico-sysdig** [comment]
This has already been implemented in another PR.

**Pull request closed without merging**
