### PR TITLE
cleanup(drivers): driver inconsistencies CHECK_RES

### LINKED ISSUE #902: [CLEANUP] Drivers inconsistencies
While working on our drivers I am noticing many inconsistencies. 

For instance: 

- we indistinguishably use `s32` and int32_t` types. I think we should one or the other for consistency, and I would use the `_t` ones because are defined by the C standard. 
- in our kmod, there is a macro `CHECK_RES` that can be used to check if a previous operation succeeded or not. It is not consistently used in the whole file.
- there is a `syscall_arg_t` type that is seldom used throughout the file.

Still adding things to this. Once we are done with introducing syscall for modern probe we can think about this!

### PR DESCRIPTION
**Pull request by ecbadeaux**
**What type of PR is this?**

/kind bug

/kind cleanup

**Any specific area of the project related to this PR?**

/area driver-bpf

/area driver-modern-bpf

**Does this PR require a change in the driver versions?**

No I do not think so.

**What this PR does / why we need it**:

Make driver code more consistent.

**Which issue(s) this PR fixes**:

part of #902
(partial fix other issues still remain in 902)

**Special notes for your reviewer**:

Tagging @dwindsor for visibility.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by incertum** [comment]
Ok now -- just for the future: We typically try to use commit conventions https://github.com/falcosecurity/.github/blob/main/CONTRIBUTING.md#commit-convention in a way similar to `fix(drivers): ...` and here we probably would have used `cleanup(drivers): ...`.

Sometimes some spaces before the comments were removed, but it's not a big deal from my perspective.

**Review by incertum — APPROVED** [review]
/approve

**Comment by ecbadeaux** [comment]
> Ok now -- just for the future: We typically try to use commit conventions https://github.com/falcosecurity/.github/blob/main/CONTRIBUTING.md#commit-convention in a way similar to `fix(drivers): ...` and here we probably would have used `cleanup(drivers): ...`.
> 
> Sometimes some spaces before the comments were removed, but it's not a big deal from my perspective.

@incertum Ok I squashed the commits and changed the commit message to match the standard.

**Review by Andreagit97 — APPROVED** [review]
Thank you!
/approve

**Pull request merged**
