### PR TITLE
fix(CI): remove an old reference

### PR DESCRIPTION
**Pull request by Andreagit97**
Signed-off-by: Andrea Terzolo <andrea.terzolo@polito.it>

**What type of PR is this?**

/kind bug

**Any specific area of the project related to this PR?**

/area driver-modern-bpf

**Does this PR require a change in the driver versions?**

No

**What this PR does / why we need it**:

This PR fixes a broken CI job

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by FedeDP — APPROVED** [review]
/approve

**Comment by LucaGuerra** [comment]
I will approve it once the CI is completely green :)

**Review by leogr — APPROVED** [review]

**Pull request merged**
