### PR TITLE
chore: Use modern Lua functions in chisels

### PR DESCRIPTION
**Pull request by federico-sysdig**
**What type of PR is this?**
/kind cleanup

**Any specific area of the project related to this PR?**
/area build

**Does this PR require a change in the driver versions?**
No.

**What this PR does / why we need it**:
Replaces outdated functions of the library for embedding Lua with more modern ones. This will allow to upgrade the Lua library in the future. For instance Vcpkg, the Microsoft package manager, provides a more modern version of Lua that would need this change. 

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
Some minor cleanup has been performed in the involved files.

**Does this PR introduce a user-facing change?**:
No.

```release-note
NONE
```

### CODE REVIEW

**Review by incertum — APPROVED** [review]
/milestone 0.15.0

/approve

note for the second reviewer: not too knowledgeable about the chisels and our lua use, but just looking at the code changes totally LGTM

**Comment by incertum** [comment]
@federico-sysdig few CI hiccups, will re-approve after fixing them all.

**Comment by federico-sysdig** [comment]
> @federico-sysdig few CI hiccups, will re-approve after fixing them all.

Thanks. Yes, the CI builds with "non-bundled" libs use liblua5.1 which is not as updated as the LuaJIT of the bundled lib. I have updated the CI builds, this should hopefully fix those builds.

**Review by incertum — APPROVED** [review]
/approve

**Review by jasondellaluce — APPROVED** [review]
/approve

**Comment by FedeDP** [comment]
This needs to be rebased on master to fix CI :)

**Comment by federico-sysdig** [comment]
> This needs to be rebased on master to fix CI :)

@FedeDP Done.

**Review by FedeDP — APPROVED** [review]
/approve

**Review by incertum — APPROVED** [review]
/approve

**Comment by leogr** [comment]
Hey @federico-sysdig 

This PR is blocked by this failing test :point_down: 
[CI Build / build-libs-linux-arm64 😁 (system_deps_minimal) (pull_request)](https://github.com/falcosecurity/libs/actions/runs/7531162610/job/20502348168?pr=1616)

Could you take a look please? :pray: 

Otherwise, LGTM.

**Comment by federico-sysdig** [comment]
> This PR is blocked by this failing test 👇 [CI Build / build-libs-linux-arm64 😁 (system_deps_minimal) (pull_request)](https://github.com/falcosecurity/libs/actions/runs/7531162610/job/20502348168?pr=1616)
> Could you take a look please? 🙏

I've looked and there is a test that's timing out. The test seems to be unrelated to the change and I don't recall it failing before rebasing (did it in order to be able to merge). Do we have experience of some tests failing erratically due to some other reason?

**Pull request merged**
