### PR TITLE
update(OWNERS): add Hendrik Brueckner (hbrueckner) as reviewer

### PR DESCRIPTION
**Pull request by hbrueckner**
Signed-off-by: Hendrik Brueckner <brueckner@de.ibm.com>

**What type of PR is this?**

/kind documentation

**Any specific area of the project related to this PR?**

/area proposals

**Does this PR require a change in the driver versions?**

None

**What this PR does / why we need it**:

Based the very nice discussion [#569](https://github.com/falcosecurity/libs/pull/569#issuecomment-1239312157) and

@Andreagit97 and @FedeDP feedback:

> I fully agree with Andrea; @hbrueckner you are doing such a tremendous job in reviewing and testing every modern-bpf related PR, it's really stunning! Please take a moment and think about joining us :) it would be great to have such a domain expert helping us with code reviews!

I am delighted to join your team as reviewer! Many thanks for this offer and looking forward for the next reviews. Thanks a lot!

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by FedeDP — APPROVED** [review]
/approve

**Comment by FedeDP** [comment]
I am so happy to see you here!

**Comment by FedeDP** [comment]
You'll also need to add yourself as a falcosecurity member, like this: https://github.com/falcosecurity/test-infra/pull/788

**Comment by leogr** [comment]
> You'll also need to add yourself as a falcosecurity member, like this: [falcosecurity/test-infra#788](https://github.com/falcosecurity/test-infra/pull/788)
> 
> /cc @leogr

Yes, please! It's required to get the invitation to the falcosecurity github org.

**Review by Andreagit97 — APPROVED** [review]
Thank you for joining us @hbrueckner :rocket: !!
/approve

**Comment by Molter73** [comment]
Huge +1 from me on this!

**Pull request merged**
