### PR TITLE
sync: release 0.15.x

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind cleanup

**Any specific area of the project related to this PR?**

/area libsinsp

**Does this PR require a change in the driver versions?**

**What this PR does / why we need it**:

Cherry picks https://github.com/falcosecurity/libs/pull/1753  and https://github.com/falcosecurity/libs/pull/1754 from master to release/0.15.x branch.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by FedeDP** [comment]
/close
@Andreagit97 is right; since we build on a X system and then run Falco on Y systems, this PR can cause issues.

**Comment by FedeDP** [comment]
/reopen
Wrong PR :D

**Review by Andreagit97 — APPROVED** [review]
/approve

**Review by leogr — APPROVED** [review]

**Pull request merged**
