### PR TITLE
update(build): use -Og when debugging

### PR DESCRIPTION
**Pull request by LucaGuerra**
Signed-off-by: Luca Guerra <luca@guerra.sh>

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area build

**Does this PR require a change in the driver versions?**

**What this PR does / why we need it**:

I use the debugger a lot. I got frustrated by a bunch of `<optimized out>`. Then today I realized the likely reason why I was seeing so many :)

Anyone that has historical knowledge, if this flag was already there and was removed for a reason let me know, otherwise I probably want it.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by FedeDP** [comment]
I actually think that the issue is that we are overriding `CMAKE_C_FLAGS_DEBUG` instead of adding element to it; 
`CMAKE_C_FLAGS_DEBUG` already has the debug param:
```
CMAKE_C_FLAGS_DEBUG is -g
CMAKE_C_FLAGS_RELEASE is -O3 -DNDEBUG
CMAKE_C_FLAGS_RELWITHDEBINFO is -O2 -g -DNDEBUG
CMAKE_C_FLAGS_MINSIZEREL is -Os -DNDEBUG

CMAKE_CXX_FLAGS_DEBUG is -g
CMAKE_CXX_FLAGS_RELEASE is -O3 -DNDEBUG
CMAKE_CXX_FLAGS_RELWITHDEBINFO is -O2 -g -DNDEBUG
CMAKE_CXX_FLAGS_MINSIZEREL is -Os -DNDEBUG
```

Note the difference:
```
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${FALCOSECURITY_LIBS_COMMON_FLAGS}")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${FALCOSECURITY_LIBS_COMMON_FLAGS} -std=c++0x")
...
set(CMAKE_C_FLAGS_DEBUG "${FALCOSECURITY_LIBS_DEBUG_FLAGS}")
set(CMAKE_CXX_FLAGS_DEBUG "${FALCOSECURITY_LIBS_DEBUG_FLAGS}")
```

**Comment by LucaGuerra** [comment]
@FedeDP the modification sounds about right then since I only wish to add `-Og` to the rest of the debug flags we already have. (note that `-g` and `-Og` are two different flags)

**Review by FedeDP — APPROVED** [review]
/approve

**Review by leogr — APPROVED** [review]
:+1:

**Pull request merged**
