### PR TITLE
keep lookup history when refreshing cache

### PR DESCRIPTION
**Pull request by VadimZy**
Signed-off-by: vadim.zyarko <vadim.zyarko@sysdig.com>

**What type of PR is this?**

/kind feature

**Any specific area of the project related to this PR?**

/area libsinsp

**What this PR does / why we need it**:

This PR is to refactor dns_manager:
- introduce a client API to clear the DNS cache, it might be required when client configuration has changed 
but the cache keeps on refreshing with all values.
- introduces new logic to retain previously discovered records while refreshing the cache. 
Currently, records discovered in previous refreshes are discarded and replaced with newly received ones. 
This makes the cache less useful in cases of multiple records for a name. 
eg loginmicrofsoft.com can resolve to 40 entries but DNS system reports only 8 records at a time. 
Thus keeping more records gives more precision to the cache.
 

**Does this PR introduce a user-facing change?**:
yes

```release-note
update: introduce a client API to clear the DNS cache, it might be required when client configuration has changed
but the cache keeps on refreshing with all values.
new: introduce new logic to retain previously discovered records while refreshing the cache.
```

### CODE REVIEW

**Comment by deepskyblue86** [comment]
@VadimZy as far as I can tell, there's a Prow automation plugin on the release-note block, so please update it to have something meaningful.

**Comment by FedeDP** [comment]
@VadimZy can you rebase this one?

**Comment by FedeDP** [comment]
@VadimZy is this still needed/alive?

**Comment by VadimZy** [comment]
@FedeDP Hi Federico, sorry for the delay.
This PR is obsolete. We no longer use reverse DNS lookup in the agent. We moved to the bad IPs list matching.

**Pull request closed without merging**
