### PR TITLE
chore: sync release branch `0.11.x`

### PR DESCRIPTION
**Pull request by Andreagit97**
**What type of PR is this?**

/kind feature

**Any specific area of the project related to this PR?**

/area libsinsp

**Does this PR require a change in the driver versions?**

**What this PR does / why we need it**:

This PR syncs the release branch with these PRs:
- [x] https://github.com/falcosecurity/libs/pull/1106
- [x] https://github.com/falcosecurity/libs/pull/1108

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by Andreagit97** [comment]
updated with https://github.com/falcosecurity/libs/pull/1108

**Review by FedeDP — APPROVED** [review]
/approve

**Pull request merged**
