### PR TITLE
Support PT_FD param types when converting to json/string

### PR DESCRIPTION
**Pull request by mstemm**
No filterchecks have PT_FD params, but it's possible to have an
evt.arg.fd param for many syscalls and that could be printed in output
fields.

It's a 64 bit int so just add it to the sections that work with that
underlying type.

Signed-off-by: Mark Stemm <mark.stemm@gmail.com>

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

> /area driver-kmod

> /area driver-ebpf

> /area libscap

/area libsinsp

> /area tests

> /area proposals

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by FedeDP** [comment]
You're on fire 🔥 man! 
Thanks for this! I agree with you, it makes sense to me!

**Review by FedeDP — APPROVED** [review]
/approve

**Review by leogr — APPROVED** [review]
:+1: 

/approve

**Pull request merged**
