### PR TITLE
chore: sync release branch `0.11.x`

### PR DESCRIPTION
**Pull request by Andreagit97**
**What type of PR is this?**

/kind feature

**Any specific area of the project related to this PR?**

/area libsinsp

**Does this PR require a change in the driver versions?**

**What this PR does / why we need it**:

This PR syncs the release branch with these PRs:
- [x] https://github.com/falcosecurity/libs/pull/1095
- [x] https://github.com/falcosecurity/libs/pull/1098
- [x] https://github.com/falcosecurity/libs/pull/1100
- [x] https://github.com/falcosecurity/libs/pull/1102
- [x] https://github.com/falcosecurity/libs/pull/1103
- [x] https://github.com/falcosecurity/libs/pull/1105

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by Andreagit97** [comment]
Please check that commits are right but I just rebased on master so we should be fine :)

**Comment by Andreagit97** [comment]
we need to cheery pick also this https://github.com/falcosecurity/libs/pull/1105

**Comment by Andreagit97** [comment]
done :) we should be fine!

**Review by LucaGuerra — APPROVED** [review]

**Pull request merged**
