### PR TITLE
update(OWNERS): add Mauro Moltrasio (Molter73) to OWNERS

### PR DESCRIPTION
**Pull request by Molter73**
**What type of PR is this?**

/kind documentation

**Any specific area of the project related to this PR?**

/area proposals

**What this PR does / why we need it**:

As discussed during today's community call, I've been contributing with reviews and fixes in the repository over the last couple of months, I feel it is time for me to make a bigger commitment with the project so I'm proposing myself as maintainer for it.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by FedeDP** [comment]
Huge +1 from me! Mauro the regressions hunter ❤️

**Review by leogr — APPROVED** [review]
Huge +1 from me too. Mauro has always helped from the first time he joined the community. Also, meeting him during the last Kubecon was great!
I can't wait to see you on board :)

**Review by FedeDP — APPROVED** [review]
/approve

**Comment by jasondellaluce** [comment]
+1 from me too! 👍🏼 👍🏼  I don't maintain this repository, but I witnessed how much you contributed to the community over the past few months. Having you onboard will be a great addition for the project, thanks for stepping up! 😄

**Comment by loresuso** [comment]
Not a maintainer here too, but as a contributor of the project I'm glad you are becoming a maintainer, well deserved! 🙂

**Comment by Molter73** [comment]
Thank you everyone! Really excited to join as a maintainer! 😄

**Pull request merged**
