### PR TITLE
update(OWNERS): add Andrea Terzolo (andreagit97) to OWNERS

### PR DESCRIPTION
**Pull request by Andreagit97**
Signed-off-by: Andrea Terzolo <andrea.terzolo@polito.it>

**What type of PR is this?**

/kind documentation

**Any specific area of the project related to this PR?**

/area proposals

**What this PR does / why we need it**:

As said in today's community call, in this PR I want to propose myself as a libs maintainer: during the last few months, I have been quite busy fixing issues around the repo, mainly in our drivers. By the way, I have also good knowledge about how our library works and I can help the actual maintainers in reviewing the code since every day we have more and more PRs in the libs repo.  I offer here my support, let me know if it can be useful for you or not, remember that this is just a proposal. Thank you.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jasondellaluce** [comment]
I'm not a maintainer of this repo, but I just wanted to leave my +1 as a community member and Falco maintainer.

I saw your involvement with the community grow a lot over the past few months, and I think you are one of the most knowledgeable community members about the libs codebase, especially for what concerns the kernel module and the eBPF probe. I think you demonstrated this very well with your recent eBPF probe proposal.

It would be great to have you onboard, thank you for committing your time into this! 🙏🏼

**Comment by FedeDP** [comment]
As i already stated during the community call, big +1 from me!  
Andrea is always helpful; moreover, he took over lots of eBPF/drivers related duties, with his great willingness to always deliver the best.  

Given his proposal for a new eBPF probe, and given his involvement with the community, i am looking forward to have him on board! He will be a precious resource for the Falco project and its community.
:rocket:

**Comment by Andreagit97** [comment]
Thank you very much! I really appriciate it 🚀

**Comment by leogr** [comment]
big +1 for me!

**Review by leogr — APPROVED** [review]
/approve

**Review by FedeDP — APPROVED** [review]
/approve

**Pull request merged**
