### PR TITLE
update: in nodriver mode, avoid loading proc, users and interfaces related informations

### PR DESCRIPTION
**Pull request by FedeDP**
Signed-off-by: Federico Di Pierro <nierro92@gmail.com>

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind cleanup

**Any specific area of the project related to this PR?**

/area libscap

/area libsinsp

**What this PR does / why we need it**:

In nodriver mode, skip loading proc, users and interfaces related informations as all event sources will be system-external.

**Which issue(s) this PR fixes**:

Possibly: https://github.com/falcosecurity/falco/issues/1757

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by mstemm — COMMENTED** [review]
Don't you still want the initial process/user/interface lists in nodriver mode? I'm not sure I understand why we would not want them.

**Comment by FedeDP** [comment]
> Don't you still want the initial process/user/interface lists in nodriver mode? I'm not sure I understand why we would not want them.

What's the use for that? I mean, is there any particular use case where we want that in nodriver mode?

**Comment by mstemm** [comment]
I thought nodriver mode still attempted to get a reconstructed view of the world and a minimal set of events that could be written to a capture file. (I don't remember the details). Do you know?

**Comment by mstemm** [comment]
One big difference between nodriver mode and plugin mode is that when in plugin mode, the *only* events and state are within the plugin. All of libsinsp is effectively disabled.

That's not true for nodriver mode, where the goal is to still obtain process and thread level state of the system.

Let me get more familiar with nodriver mode and then comment more.

**Comment by mstemm** [comment]
I double-checked and nodriver mode depends on reading this info from /proc, so I think if the goal is to come up with a "light" mode that allowed only k8s audit logs and no syscalls, we should come up with another mode/solution, perhaps at the falco level instead of the libs level, to fix this.

**Comment by FedeDP** [comment]
> I double-checked and nodriver mode depends on reading this info from /proc, so I think if the goal is to come up with a "light" mode that allowed only k8s audit logs and no syscalls, we should come up with another mode/solution, perhaps at the falco level instead of the libs level, to fix this.

I think that when k8s audit logs will become a plugin, the issue will be fixed in any case; it's ok for me to close this PR and wait for a proper plugin implementation.

**Comment by FedeDP** [comment]
Closing because nodriver mode still needs a system view.  
Issue itself (https://github.com/falcosecurity/falco/issues/1757) will be fixed once k8s audit log becomes a plugin.

**Pull request closed without merging**
