### PR TITLE
cleanup(driver,userspace)!: renamed `accept4` syscall mapping event to "accept4"

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind cleanup

**Any specific area of the project related to this PR?**

/area driver-kmod
/area driver-bpf
/area driver-modern-bpf
/area libscap
/area libpman
/area libsinsp

**Does this PR require a change in the driver versions?**

Yep SCHEMA VERSION minor. **BUT** was already bumped since latest release ;)
  
**What this PR does / why we need it**:

Before, the accept4 event was called "accept".
Following #911 , we want to properly map each event to its own syscall using syscall name; therefore, rename the event to accept4 (we needed to add a new event!).

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
cleanup(driver,userspace)!: renamed `accept4` syscall mapping event to "accept4"
```

### CODE REVIEW

**Review by Andreagit97 — APPROVED** [review]
thank you
/approve

**Review by incertum — APPROVED** [review]
/approve

/hold until after 2023-03-15 community call formal agreement, see https://github.com/falcosecurity/falco/issues/2443

**Pull request merged**
