### PR TITLE
cleanup sysdig references

### PR DESCRIPTION
**Pull request by loresuso**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

/kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

/area driver-kmod

/area driver-ebpf

/area libscap

> /area libsinsp

> /area tests

> /area proposals

**What this PR does / why we need it**:
Removing useless references to Sysdig in kernel module, bpf probe and libscap

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by FedeDP** [comment]
Thank you very much @loresuso for this PR!

**Review by nathan-b — APPROVED** [review]
LGTM, thanks!

**Review by FedeDP — APPROVED** [review]

**Review by leogr — APPROVED** [review]
/approve

:star_struck:

**Pull request merged**
