### PR TITLE
update(release): sync commits from master

### PR DESCRIPTION
**Pull request by jasondellaluce**
**What type of PR is this?**

/kind cleanup

**Any specific area of the project related to this PR?**

**Does this PR require a change in the driver versions?**

**What this PR does / why we need it**:

Synching release branch with commits from (see https://github.com/falcosecurity/libs/issues/626):
- https://github.com/falcosecurity/libs/pull/653
- https://github.com/falcosecurity/libs/pull/652
- https://github.com/falcosecurity/libs/pull/655
- https://github.com/falcosecurity/libs/pull/656

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by FedeDP — APPROVED** [review]
/approve

**Review by Andreagit97 — APPROVED** [review]
/approve

**Comment by FedeDP** [comment]
Manually rebasing and merging because poiana is :skull:

**Pull request merged**
