### PR TITLE
update(ci): update actuated test job with label

### PR DESCRIPTION
**Pull request by LucaGuerra**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

**Any specific area of the project related to this PR?**

/area CI

**Does this PR require a change in the driver versions?**

No

**What this PR does / why we need it**:

Let's use the same label as we use in other parts of the CI so we are sure we use the same types of runners. This job will then be removed after troubleshooting

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by FedeDP — APPROVED** [review]
/approve

**Review by Andreagit97 — APPROVED** [review]
/approve

**Comment by FedeDP** [comment]
I think we can remove this job actually.

**Comment by LucaGuerra** [comment]
superseded by https://github.com/falcosecurity/libs/pull/1591

**Pull request closed without merging**
