### PR TITLE
update(userspace/libsinsp): bumped jsoncpp to latest 1.9.5 release.

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind cleanup

**Any specific area of the project related to this PR?**

/area libsinsp

**Does this PR require a change in the driver versions?**

**What this PR does / why we need it**:

Updates jsoncpp to 1.9.5 release (amalgamated).

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by jasondellaluce — APPROVED** [review]

**Comment by FedeDP** [comment]
Perhaps we can move it to its own cmake module, like all other deps?

**Comment by Andreagit97** [comment]
yeah it seems the right thing to do

**Comment by FedeDP** [comment]
Closing in favor of #1271 
/close

**Pull request closed without merging**
