### PR TITLE
fix(userspace/libsinsp): properly use `strlen` instead of `sizeof` when assigning user/group string infos

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind bug

**Any specific area of the project related to this PR?**

/area libsinsp

**Does this PR require a change in the driver versions?**

**What this PR does / why we need it**:

Small fixup on top of https://github.com/falcosecurity/libs/pull/1765.
cc @erthalion 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by Andreagit97 — APPROVED** [review]
/approve

**Review by LucaGuerra — DISMISSED** [review]

**Comment by erthalion** [comment]
Thanks @FedeDP. From what I understand the data for those fields is coming from `getpwent/fgetpwent`. I can't find immediately if those functions always return null terminated strings, but probably worth using `strnlen` with `MAX_CREDENTIALS_STR_LEN`/`SCAP_MAX_PATH_SIZE`?

**Comment by FedeDP** [comment]
> I can't find immediately if those functions always return null terminated strings

While i can't find it either, i assume it returns NULL terminated strings since it does not return any `len` for the char buffers.
Otherwise it would be a really bad API :) 

But better safe than sorry, i agree.

**Review by Andreagit97 — APPROVED** [review]
/approve

**Review by LucaGuerra — APPROVED** [review]

**Pull request merged**
