### PR TITLE
fix(ci): fixed release-body double quoted string usage.

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind bug

**Any specific area of the project related to this PR?**

/area CI

**What this PR does / why we need it**:

Fixes double quotes usage in release-body workflow; see https://github.com/actions/runner/issues/866

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by LucaGuerra — APPROVED** [review]
LGTM

**Review by Andreagit97 — APPROVED** [review]
/approve

**Pull request merged**
