### PR TITLE
new(ci): add libsinsp unit test code coverage

### PR DESCRIPTION
**Pull request by LucaGuerra**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area CI

**Does this PR require a change in the driver versions?**

No

**What this PR does / why we need it**:

Add code coverage reports for libsinsp unit tests via [codecov](https://about.codecov.io/)

Part of: https://github.com/falcosecurity/libs/issues/1784

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by LucaGuerra** [comment]
Ok the message above confirms that `codecov` is working but it needs `master` coverage data in order to provide useful data. I think this can be merged.

**Review by FedeDP — APPROVED** [review]
/approve

**Review by Andreagit97 — COMMENTED** [review]
Cool, thank you
/approve

**Review by Andreagit97 — APPROVED** [review]

**Pull request merged**
