### PR TITLE
chore(driver): properly use `strscpy`.

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind cleanup

**Any specific area of the project related to this PR?**

/area driver-kmod

**Does this PR require a change in the driver versions?**

/version driver-API-version-patch

**What this PR does / why we need it**:

This PR adapts kmod code to use `strscpy` in place of `strlcpy` in kernels where `strscpy` is available (ie: since 4.3.0: https://github.com/torvalds/linux/commit/30035e45753b708e7d47a98398500ca005e02b86).
`strscpy` is safer and has better results; moreover, `strlcpy` is being sunsetted (https://lore.kernel.org/lkml/202401191311.B6AA79D@keescook/ in kernel 6.8 for the full removal, but the effort to drop it from all drivers did .start quite a while ago).
See https://lwn.net/Articles/659214/ and `strscpy` code: https://elixir.bootlin.com/linux/latest/source/lib/string.c#L122

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by FedeDP** [comment]
This also fixes build against v6.8-rc1: https://github.com/falcosecurity/libs/actions/runs/7622725910/job/20761330947

**Comment by FedeDP** [comment]
rc3 still fixed ;)

**Comment by FedeDP** [comment]
Still good against linux 6.8-rc5: https://github.com/falcosecurity/libs/actions/runs/7622725910

**Comment by FedeDP** [comment]
Testing against rc6: https://github.com/falcosecurity/libs/actions/runs/8064072897 :green_circle:

**Review by Andreagit97 — APPROVED** [review]
/approve

**Comment by Andreagit97** [comment]
i think you need to rebase to remove the stale required jobs

**Comment by FedeDP** [comment]
You are right! Rebased!

**Review by jasondellaluce — APPROVED** [review]

**Pull request merged**
