### PR TITLE
fix(driver,bpf_probe): capture also execveat exit event

### PR DESCRIPTION
**Pull request by Andreagit97**
Signed-off-by: Andrea Terzolo <andrea.terzolo@polito.it>

**What type of PR is this?**

/kind bug

**Any specific area of the project related to this PR?**

/area driver-kmod

/area driver-ebpf

**What this PR does / why we need it**:

This PR allows us to capture the exit event of the `execveat`, which after adding the `is_exe_writable` flag was no longer pushed correctly in the ring_buffer. The `g_event_info` table shows `19` parameters for this event, while, with the new flag mentioned above, they are `20`. 

> **Note**: an `execveat` exit event is returned only when the `execveat` syscall fails, in case of success we obtain an `execve` exit event.
 
Although the impact on the system security is therefore limited, we want to keep track of the `execveat` exit event to have a complete and exhaustive scenario.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
catch also execveat exit event
```

### CODE REVIEW

**Review by LucaGuerra — APPROVED** [review]
lgtm!

**Review by FedeDP — APPROVED** [review]
/approve

**Comment by FedeDP** [comment]
Can you rebase @Andreagit97 ? Thanks!

**Review by FedeDP — APPROVED** [review]
/approve

**Review by leogr — APPROVED** [review]
/approve

**Pull request merged**
