### PR TITLE
new(gha): enable UndefinedBehaviorSanitizer

### LINKED ISSUE #1470: Support UndefinedBehaviorSanitizer in CI/test builds
We have already enabled AddressSanitizer in CI with both unit and e2e tests, successfully as it allowed us to prevent a number of oob reads/writes before they landed. As we increase our testing coverage and clean up the codebase we wish to enable more safeguards and UBSan is the first that came to mind to spot potential segfaults early.

In order to do so, we need to remove some "clever code tricks" that would trip UBSan, mostly regarding misaligned memory accesses. This gives us another opportunity to clean up the codebase. We have already started in https://github.com/falcosecurity/libs/pull/1447 bringing the warnings from 154 to 29 but we need to continue until at least unit tests and e2e give 0 warnings, at which point we can enable UBSan.

### PR DESCRIPTION
**Pull request by LucaGuerra**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area CI

**Does this PR require a change in the driver versions?**

No

**What this PR does / why we need it**:

This enables UBSan for tests. Please note that it's a work in progress until we are sure it works.
EDIT: it works with no warnings with the current state of the repo, so it's out of wip!

**Which issue(s) this PR fixes**:

Fixes #1470

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by LucaGuerra** [comment]
Enforcement is not avilable yet. The following warnings were identified by the GHA run:
* 2024-02-12T15:32:15.5043419Z /__w/libs/libs/userspace/libsinsp/container.cpp:303:58: runtime error: load of value 3200171710, which is not a valid value for type 'sinsp_container_type'
* 2024-02-12T15:32:15.5046109Z /__w/libs/libs/userspace/libsinsp/container_info.h:37:44: runtime error: load of value 3200171710, which is not a valid value for type 'sinsp_container_type'
* 2024-02-12T15:32:15.5048629Z /usr/include/c++/8/tuple:1668:70: runtime error: load of value 3200171710, which is not a valid value for type 'sinsp_container_type'
* 2024-02-12T15:32:24.6114438Z /__w/libs/libs/userspace/libsinsp/parsers.cpp:1706:47: runtime error: load of value 190, which is not a valid value for type 'bool'
* 2024-02-12T15:32:24.6116431Z /__w/libs/libs/userspace/libsinsp/parsers.cpp:1708:50: runtime error: load of value 190, which is not a valid value for type 'bool'
* 2024-02-12T15:32:24.6117803Z /__w/libs/libs/userspace/libsinsp/parsers.cpp:1710:49: runtime error: load of value 190, which is not a valid value for type 'bool'
* 2024-02-12T15:32:24.6571001Z /__w/libs/libs/userspace/libsinsp/sinsp_filtercheck.cpp:454:27: runtime error: load of misaligned address 0x60400001e96c for type 'int64_t', which requires 8 byte alignment
2024-02-12T15:32:24.6572639Z 0x60400001e96c: note: pointer points here
2024-02-12T15:32:24.6573572Z   00 00 08 00 00 00 00 00  00 00 00 00 be be be be  be be be 00 00 00 00 00  03 00 00 00 00 00 00 04
2024-02-12T15:32:24.6574473Z               ^

**Comment by LucaGuerra** [comment]
I have removed the wip. After the CI passes I think we can merge this.

**Review by FedeDP — APPROVED** [review]
/approve
LOVE THIS ONE

**Review by leogr — APPROVED** [review]

**Pull request merged**
