### PR TITLE
libsinsp: increase log-level of cri errors

### PR DESCRIPTION
**Pull request by alban**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

/kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

> /area driver-kmod

> /area driver-ebpf

> /area libscap

/area libsinsp

> /area tests

> /area proposals

**What this PR does / why we need it**:

Sometimes the container metadata is missing. In order to figure out why
the CRI does not return the container metadata, increase log-level.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

When using this patch in sysdig, you could take https://github.com/draios/sysdig/pull/1871

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

Signed-off-by: Alban Crequy <albancrequy@microsoft.com>

### CODE REVIEW

**Comment by FedeDP** [comment]
Hi! Thanks for this PR!
I think that the main issue is that increasing the log level would flood your log super quickly!
I guess that's the reason why it was put as debug.

**Comment by alban** [comment]
Hi [@FedeDP](https://github.com/FedeDP), yes, that's indeed a concern. My goal is to make use of that in production, so I tried to only increase the log level of actual errors, so that it would not be flooded. I left other debugs untouched. Do you think it could still flood the logs?

**Comment by alban** [comment]
I have a version of this patch rebased on commit e5c53d648f3c4694385bbe488e7d47eaa36c229a (see branch [alban_e5c53d648f3c_cri_getstatususing](https://github.com/kinvolk/falcosecurity-libs/commits/alban_e5c53d648f3c_cri_getstatus)) because that's what sysdig is using (see [cmake/modules/falcosecurity-libs.cmake#L32](https://github.com/draios/sysdig/blob/fd40512f7e40fbeb706b5f7f2359c9a8812c24f7/cmake/modules/falcosecurity-libs.cmake#L32)). Sysdig can be compiled with that patch with something like the following:
```
$ cmake ../sysdig -DFALCOSECURITY_LIBS_SOURCE_DIR=$(realpath $PWD/../../falcosecurity/libs) && time make
```

Then, the error logs from this patch should be visible with the command `sysdig -D --log-level=error`.

**Comment by leogr** [comment]
Closing and reopening to trigger the CI
/close

**Comment by Andreagit97** [comment]
Hi, @alban thanks for that. I don't like too much the idea since maybe not all Falco users would have this severity enabled, maybe the best solution is to build it from sources changing only these lines and seeing what is not working correctly. Anyway, if this is not a viable solution for you, we may temporarily enable this severity, let's see what other maintainers think about it

**Comment by FedeDP** [comment]
@alban can you try with Falco 0.32.1 that ships the PR linked by @jasondellaluce ? 
If it works for you, i think we can close this one :)

**Pull request closed without merging**
