### PR TITLE
fix(install): install the 10 libscap related libraries

### PR DESCRIPTION
**Pull request by terylt**
Signed-off-by: Teryl <terylt@ibm.com>

**What type of PR is this?**

/kind bug

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area build
/area libscap

**What this PR does / why we need it**:

The scap library was recently broken out into 10 separate libs, but they were not added to the installation script in cmake.  All 10 libraries are needed to build consumer applications.

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
It installs all 10 libraries.

```release-note
added scap engine related libs to install
```

### CODE REVIEW

**Comment by FedeDP** [comment]
Hi @terylt ! This LGTM!
I think you need to rebase on top of master because we had a failing test (gtest cmake was hooked to main version, instead of a tag; and main broke our build).

**Comment by FedeDP** [comment]
I meant that you need to rebase your PR on top of master :) 
Like:
* git checkout master
* git pull upstream master
* git checkout libscap_install
* git rebase master
* git push origin HEAD --force-with-lease

**Comment by terylt** [comment]
@FedeDP Thanks for the comments.  I rebased to master as requested which included the GTest change.  It looks like the retest builds timed out due to lack of resources.

**Comment by FedeDP** [comment]
Yep, prow is quite busy atm building drivers for 0.32.1 Falco release :) 
We will move libs CI to gh actions soon :tm:  see #453

**Comment by terylt** [comment]
@FedeDP Oh great!  If you need any help with GHA and setting up CI's let us know.  We use it exclusively in our project and even have a repo that builds falco base images and lib images.

**Review by leogr — APPROVED** [review]

**Review by FedeDP — APPROVED** [review]
/approve

**Pull request merged**
