### PR TITLE
fix(userspace/libsinsp): make plugin_filtercheck arg parsing more resilient

### PR DESCRIPTION
**Pull request by jasondellaluce**
**What type of PR is this?**

/kind bug

**Any specific area of the project related to this PR?**

/area libsinsp

**Does this PR require a change in the driver versions?**

**What this PR does / why we need it**:

The plugin filtercheck parsing function used when compiling filters was faulted in corner cases involving field arguments. For reference, assuming a valid plugin field `some.field` allowing an argument, both the following used to be accepted whereas the second case is wrong:
- `some.field[some_arg]`
- `some.field_that_does_not_exist[some_arg]`

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by incertum — APPROVED** [review]
/approve

**Review by FedeDP — APPROVED** [review]
/approve

**Comment by FedeDP** [comment]
@Andreagit97 this is a small fix that perhaps might make sense for 0.13.2?

**Comment by Andreagit97** [comment]
> @Andreagit97 this is a small fix that perhaps might make sense for 0.13.2?

Makes sense!

**Pull request merged**
