### PR TITLE
fix(driver/bpf): sys_open_e verifier issue on aarch64

### PR DESCRIPTION
**Pull request by deepskyblue86**
**What type of PR is this?**

/kind bug

**Any specific area of the project related to this PR?**

/area driver-ebpf

**What this PR does / why we need it**:
Deal with clang quirkiness and make it use the proper register

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
No

```release-note
NONE
```

### CODE REVIEW

**Comment by deepskyblue86** [comment]
I'd like to thank @FedeDP who suggested to me how to narrow down the issue and @Andreagit97 for trying to explain what was going on (even if it turned out it's just clang doing weird stuff)

**Comment by Andreagit97** [comment]
Thank you @deepskyblue86, for fixing it!

**Review by Andreagit97 — APPROVED** [review]
LGTM!

**Review by gnosek — APPROVED** [review]

**Review by FedeDP — APPROVED** [review]
/approve

**Pull request merged**
