### PR TITLE
fix(ci): pin semgrep to 1.41.0

### PR DESCRIPTION
**Pull request by LucaGuerra**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area CI

**Does this PR require a change in the driver versions?**

No.

**What this PR does / why we need it**:

Semgrep 1.42.0 exits the following error in the libs repo. In addition, if a diff between commits is required it exits with error 2, while a full scan returns 0. Since it is a best practice to use a specific version and not automatically the latest, I'm pinning the version and I should probably also open a bug report :sweat_smile: 

```
[ERROR] Fatal error at line /src/userspace/libsinsp/parsers.cpp:1:
 Failure: ii_of_name: IdDeref
====[ BEGIN error trace ]====
Failure: ii_of_name: IdDeref
Raised at Stdlib.failwith in file "stdlib.ml", line 29, characters 17-33
Called from Parse_cpp_tree_sitter.id_of_dname_for_parameter in file "languages/cpp/tree-sitter/Parse_cpp_tree_sitter.ml", line 225, characters 37-56
Called from Parse_cpp_tree_sitter.map_parameter_declaration in file "languages/cpp/tree-sitter/Parse_cpp_tree_sitter.ml", line 3777, characters 21-53
Called from Parse_cpp_tree_sitter.map_anon_choice_param_decl_d9083af in file "languages/cpp/tree-sitter/Parse_cpp_tree_sitter.ml", line 1687, characters 14-45
Called from Common.fast_map in file "libs/commons/Common.ml", line 201, characters 16-19
Called from Parse_cpp_tree_sitter.map_parameter_list in file "languages/cpp/tree-sitter/Parse_cpp_tree_sitter.ml", line 3794, characters 10-200
Called from Parse_cpp_tree_sitter.map_function_declarator_seq in file "languages/cpp/tree-sitter/Parse_cpp_tree_sitter.ml", line 3237, characters 11-36
Called from Parse_cpp_tree_sitter.map_function_definition in file "languages/cpp/tree-sitter/Parse_cpp_tree_sitter.ml", line 3309, characters 19-40
Called from Parse_cpp_tree_sitter.map_top_level_item in file "languages/cpp/tree-sitter/Parse_cpp_tree_sitter.ml", line 4473, characters 14-43
Called from Stdlib__List.concat_map.aux in file "list.ml", line 268, characters 16-19
Called from Parse_cpp_tree_sitter.map_program_or_expr in file "languages/cpp/tree-sitter/Parse_cpp_tree_sitter.ml", line 4544, characters 11-56
Called from Parse_cpp_tree_sitter.parse.(fun) in file "languages/cpp/tree-sitter/Parse_cpp_tree_sitter.ml", line 4903, characters 12-39
Called from Parse_tree_sitter_helpers.wrap_parser in file "libs/lib_parsing_tree_sitter/Parse_tree_sitter_helpers.ml", line 121, characters 13-29
Called from Pfff_or_tree_sitter.run_parser in file "src/parsing/Pfff_or_tree_sitter.ml", line 161, characters 18-24
Re-raised at Exception.reraise in file "libs/commons/Exception.ml", line 19, characters 33-72
Called from Parse_target.parse_and_resolve_name in file "src/parsing/Parse_target.ml", line 105, characters 12-42
Called from Parse_with_caching.parse_and_resolve_name in file "src/parsing/Parse_with_caching.ml", line 137, characters 10-57
Called from CamlinternalLazy.force_lazy_block in file "camlinternalLazy.ml", line 31, characters 17-27
Re-raised at CamlinternalLazy.force_lazy_block in file "camlinternalLazy.ml", line 36, characters 4-11
Called from Common.with_time in file "libs/commons/Common.ml", line 110, characters 12-16
Called from Match_search_mode.matches_of_patterns in file "src/engine/Match_search_mode.ml", line 232, characters 8-67
Called from Match_search_mode.matches_of_xpatterns in file "src/engine/Match_search_mode.ml", line 465, characters 6-67 
Called from Match_search_mode.matches_of_formula in file "src/engine/Match_search_mode.ml", line 881, characters 4-66
Called from Match_search_mode.check_rule in file "src/engine/Match_search_mode.ml", line 916, characters 26-73
Called from Time_limit.set_timeout in file "libs/process_limits/Time_limit.ml", line 91, characters 12-16
Re-raised at Exception.reraise in file "libs/commons/Exception.ml", line 19, characters 33-72
Called from Match_rules.timeout_function in file "src/engine/Match_rules.ml", line 47, characters 4-77
Called from Match_rules.per_rule_boilerplate_fn.(fun) in file "src/engine/Match_rules.ml", line 156, characters 6-193
Called from Common.fast_map in file "libs/commons/Common.ml", line 193, characters 17-20
Called from Match_rules.check in file "src/engine/Match_rules.ml", line 209, characters 4-741
Called from Core_scan.scan.(fun) in file "src/core_scan/Core_scan.ml", line 884, characters 15-149
Called from Core_scan.iter_targets_and_get_matches_and_exn_to_errors.(fun) in file "src/core_scan/Core_scan.ml", line 508, characters 21-29
Called from Stdlib__Fun.protect in file "fun.ml", line 33, characters 8-15
Re-raised at Stdlib__Fun.protect in file "fun.ml", line 38, characters 6-52
Called from Memory_limit.run_with_memory_limit in file "libs/process_limits/Memory_limit.ml", line 118, characters 6-62 
Called from Core_scan.iter_targets_and_get_matches_and_exn_to_errors.(fun) in file "src/core_scan/Core_scan.ml", line 499, characters 17-1023
=====[ END error trace ]=====
```

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by FedeDP — APPROVED** [review]
/approve

**Review by Andreagit97 — APPROVED** [review]
/approve

**Comment by LucaGuerra** [comment]
Semgrep issue: https://github.com/returntocorp/semgrep/issues/8896

**Comment by Andreagit97** [comment]
This needs to be cherry-picked to pass the CI tests in the release branch, see https://github.com/falcosecurity/libs/pull/1412

**Pull request merged**
