### PR TITLE
fix(libsinsp): memleak in sinsp_dns_manager

### PR DESCRIPTION
**Pull request by incertum**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area API-version

> /area build

> /area CI

> /area driver-kmod

> /area driver-bpf

> /area driver-modern-bpf

> /area libscap-engine-bpf

> /area libscap-engine-gvisor

> /area libscap-engine-kmod

> /area libscap-engine-modern-bpf

> /area libscap-engine-nodriver

> /area libscap-engine-noop

> /area libscap-engine-source-plugin

> /area libscap-engine-savefile

> /area libscap

> /area libpman

/area libsinsp

> /area tests

> /area proposals

**Does this PR require a change in the driver versions?**

> /version driver-API-version-major

> /version driver-API-version-minor

> /version driver-API-version-patch

> /version driver-SCHEMA-version-major

> /version driver-SCHEMA-version-minor

> /version driver-SCHEMA-version-patch

**What this PR does / why we need it**:

LeakSanitizer: detected memory leaks

Direct leak of 8 byte(s) in 1 object(s) allocated from:
#0 0x7f84317d54c8 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:95
#1 0x56319abb44cc in sinsp_dns_manager::match(char const*, int, void*, unsigned long) /build/falcosecurity-libs-repo/falcosecurity-libs-prefix/src/falcosecurity-libs/userspace/libsinsp/dns_manager.cpp:121

add destructor to class sinsp_dns_manager to ensure m_resolver is always released when the object goes out of scope

@LucaGuerra 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by FedeDP — APPROVED** [review]
/approve

**Review by LucaGuerra — APPROVED** [review]

**Comment by incertum** [comment]
@LucaGuerra @FedeDP and @federico-sysdig while it appeared to make sense adding the destructor I am still seeing the memleak. Seems like we need to invest more and actually look into this more thoroughly and add a test so we check it with asan in the CI.

**Comment by federico-sysdig** [comment]
> @LucaGuerra @FedeDP and @federico-sysdig while it appeared to make sense adding the destructor I am still seeing the memleak. Seems like we need to invest more and actually look into this more thoroughly and add a test so we check it with asan in the CI.

@incertum I'm not sure if I can be of great help here... The only thing I find odd is keeping the thread as a pointer and, on top of that, never deleting it. I'd change the thread data member as a normal `std::thread` object or, at the very least, use a `unique_ptr`.

**Comment by incertum** [comment]
> > @LucaGuerra @FedeDP and @federico-sysdig while it appeared to make sense adding the destructor I am still seeing the memleak. Seems like we need to invest more and actually look into this more thoroughly and add a test so we check it with asan in the CI.
> 
> @incertum I'm not sure if I can be of great help here... The only thing I find odd is keeping the thread as a pointer and, on top of that, never deleting it. I'd change the thread data member as a normal `std::thread` object or, at the very least, use a `unique_ptr`.

SGTM and like a great improvement regardless. Do you want to author the PR? Thanks in advance 🙏 !

**Comment by federico-sysdig** [comment]
@incertum Feel free to proceed as you wish. It's a small thing. Thanks for asking.

**Pull request merged**
