### PR TITLE
fix(userspace/libscap): prevent libbf stats from being collected with no bpf stats

### PR DESCRIPTION
**Pull request by jasondellaluce**
**What type of PR is this?**

/kind bug

/kind cleanup

**Any specific area of the project related to this PR?**

/area libscap-engine-bpf

/area libscap-engine-modern-bpf

**Does this PR require a change in the driver versions?**

**What this PR does / why we need it**:

This check used to be in Falco, which however is not the right place as each engine should be responsible of doing safety checks before attempting executing problematic requests.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by FedeDP — DISMISSED** [review]
/approve

**Review by Andreagit97 — APPROVED** [review]
/approve

**Review by FedeDP — APPROVED** [review]
/approve

**Pull request merged**
