### PR TITLE
update kernel check for modern-bpf

### LINKED ISSUE #1719: [BUG] Compile modern_bpf error
**Describe the bug**
make drivers_test
```
/home/yzw/rd/libs/driver/modern_bpf/helpers/extract/extract_from_kernel.h:648:49: error: member reference base type 'struct percpu_counter[4]' is not a structure or union
  648 |                 BPF_CORE_READ_INTO(&swap_entries, mm, rss_stat.count[MM_SWAPENTS].counter);
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
The code files involved include :
modern_bpf/programs/tail_called/events/syscall_dispatched_events/execve.bpf.c modern_bpf/programs/tail_called/events/syscall_dispatched_events/execveat.bpf.c modern_bpf/helpers/extract/extract_from_kernel.h

**How to reproduce it**
First judge the kernel version, and then execute the corresponding operation. like this:
```
#if LINUX_VERSION_CODE >= KERNEL_VERSION(6, 3, 0)
```
instead of
```
if(bpf_core_field_exists(((struct kernel_cap_struct *)0)->cap)){...}
```

**Expected behaviour**

**Screenshots**

**Environment**

- Falco version:

- System info:

- Cloud provider or hardware configuration:
- OS:

- Kernel:

- Installation method:

**Additional context**

```[tasklist]
### Tasks
- [ ] https://github.com/falcosecurity/libs/pull/1654
```

```[tasklist]
### Tasks
- [ ] add ebpf support for loongarch64
```

### PR DESCRIPTION
**Pull request by yzewei**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

 /kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area API-version

 /area build

> /area CI

> /area driver-kmod

> /area driver-bpf

 /area driver-modern-bpf

> /area libscap-engine-bpf

> /area libscap-engine-gvisor

> /area libscap-engine-kmod

> /area libscap-engine-modern-bpf

> /area libscap-engine-nodriver

> /area libscap-engine-noop

> /area libscap-engine-source-plugin

> /area libscap-engine-savefile

> /area libscap

> /area libpman

> /area libsinsp

> /area tests

> /area proposals

**Does this PR require a change in the driver versions?**

> /version driver-API-version-major

> /version driver-API-version-minor

> /version driver-API-version-patch

> /version driver-SCHEMA-version-major

> /version driver-SCHEMA-version-minor

> /version driver-SCHEMA-version-patch

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #1719

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Kernel version used 6.8.0 -rc5

```

### CODE REVIEW

**Comment by yzewei** [comment]
Or is there a better solution?

**Comment by FedeDP** [comment]
/hold
Since our modern probe is CO-RE, it should not spot any ifdef inside on the kernel release: it is built just once and then distributed to all supported systems. 
"bpf_core_" APIs are made exactly for this reason: dynamically ask the running kernel to check for something and then react accordingly.

So, in the end, this is not a viable solution.
I will check the issue and try to understand what's happening next week!

**Comment by FedeDP** [comment]
Closing this one since it uses a wrong approach.
/close

**Pull request closed without merging**
