### PR TITLE
update(libscap-engine-kmod): avoid a write operation when not necessary

### PR DESCRIPTION
**Pull request by Andreagit97**
**What type of PR is this?**

/kind feature

**Any specific area of the project related to this PR?**

/area libscap-engine-kmod

**Does this PR require a change in the driver versions?**

No

**What this PR does / why we need it**:

This PR avoid to write into the `/sys/module/scap/parameters/g_buffer_bytes_dim` when not necessary, so when the user provided dim is the same written into the `/sys/module/scap/parameters/g_buffer_bytes_dim` file.

We have 2 advantages from this:
* Only read operation in case the default buffer size is used.
* Some system mounts the `/sys/module/...` as read-only by default, if the user doesn't need to update this shared dimension there is no need to put this mount this `fs` in reading and writing. Right now the default buffer size for the `kmod` is `8 MB`

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by FedeDP — APPROVED** [review]
/approve

**Review by LucaGuerra — APPROVED** [review]
lgtm

**Pull request merged**
