### PR TITLE
fix umount2 syscall flags type, add conversion helper function

### PR DESCRIPTION
**Pull request by oheifetz**
- change the flags (param 1) from u32 to s32
- add a userspace to scap flag conversion helper routine

Reported by: github issue #515

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area API-version

> /area build

> /area CI

> /area driver-kmod

/area driver-bpf

/area driver-modern-bpf

> /area libscap-engine-bpf

> /area libscap-engine-gvisor

> /area libscap-engine-kmod

> /area libscap-engine-modern-bpf

> /area libscap-engine-nodriver

> /area libscap-engine-noop

> /area libscap-engine-source-plugin

> /area libscap-engine-savefile

> /area libscap-engine-udig

/area libscap

/area libpman

/area libsinsp

/area tests

> /area proposals

**Does this PR require a change in the driver versions?**

> /version driver-API-version-major

> /version driver-API-version-minor

> /version driver-API-version-patch

> /version driver-SCHEMA-version-major

> /version driver-SCHEMA-version-minor

> /version driver-SCHEMA-version-patch

**What this PR does / why we need it**: change the flags (param 1) from u32 to s32 and add a userspace to scap flag conversion helper routine

**Which issue(s) this PR fixes**: issue 515 umount2 bullet

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by incertum** [comment]
@oheifetz just wanted to let you know, we are discussing in the other PR https://github.com/falcosecurity/libs/pull/1192#issuecomment-1642344240 how to make the executive decision on when we absolutely need to bump the event given it's rather a long list of minor type miss casts. We will keep you updated, for now we are holding all these PRs until we have clarified the open questions.

**Comment by oheifetz** [comment]
Hi @incertum,
Saw that some CI builds failed even though my builds and tests passed. I ran:
```
cmake -DUSE_BUNDLED_DEPS=On -DBUILD_LIBSCAP_GVISOR=Off \
      -DENABLE_DRIVERS_TESTS=On -DCREATE_TEST_TARGETS=On \
      -DBUILD_BPF=On -DBUILD_LIBSCAP_MODERN_BPF=On -DMODERN_BPF_DEBUG_MODE=On ..
make drivers_test
make driver bpf
make unit-test-libsinsp; make run-unit-test-libsinsp;
make unit-test-libscap; sudo libscap/test/unit-test-libscap;
sudo ./test/drivers/drivers_test -b driver/bpf/probe.o;
sudo ./test/drivers/drivers_test -m
sudo ./test/drivers/drivers_test -k
```
If there are some additional builds I can run to confirm that it will not fail on CI it would be great

**Comment by Andreagit97** [comment]
hey @oheifetz yes if you want to reproduce the failure locally you have to put `-DBUILD_LIBSCAP_GVISOR=On` the fix here seems to put `ifdefs around the flag you added` so

```c
#ifdef MNT_FORCE
	if (flags & MNT_FORCE)
		res |= PPM_MNT_FORCE;
#endif
#ifdef MNT_DETACH
	if (flags & MNT_DETACH)
		res |= PPM_MNT_DETACH;
#endif

    ...
	return res;
```

The `ifdef __NR_umount2` is not enough because the syscall numbers are defined in another header with respect to the flags

**Comment by oheifetz** [comment]
Hi @incertum,
When pushing code now I get: `! [remote rejected]   issue_515_umount2 -> issue_515_umount2 (refusing to allow a Personal Access Token to create or update workflow ``
Is there some explanation on the workflow changes that needs to be done to make a push work?

**Comment by incertum** [comment]
@oheifetz probably not, I just pushed myself onto my branch. I have had such issues in the past and likely something in your settings changed or you need to setup a new ssh key or something. Please let us know if you keep having these issues after checking everything.

**Pull request closed without merging**
