### PR TITLE
update(cri): `cri-dockerd` support

### PR DESCRIPTION
**Pull request by incertum**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

/kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area API-version

> /area build

> /area CI

> /area driver-kmod

> /area driver-bpf

> /area driver-modern-bpf

> /area libscap-engine-bpf

> /area libscap-engine-gvisor

> /area libscap-engine-kmod

> /area libscap-engine-modern-bpf

> /area libscap-engine-nodriver

> /area libscap-engine-noop

> /area libscap-engine-source-plugin

> /area libscap-engine-savefile

> /area libscap

> /area libpman

/area libsinsp

> /area tests

> /area proposals

**Does this PR require a change in the driver versions?**

> /version driver-API-version-major

> /version driver-API-version-minor

> /version driver-API-version-patch

> /version driver-SCHEMA-version-major

> /version driver-SCHEMA-version-minor

> /version driver-SCHEMA-version-patch

**What this PR does / why we need it**:

Support `cri-dockerd` container runtime. Fixes https://github.com/falcosecurity/falco/issues/3243.
To avoid looking up docker containers in this scenario from both the cri wrapper socket and the original docker socket configure the client like this: https://github.com/falcosecurity/falco/issues/3243#issuecomment-2195465490.

Falco PR https://github.com/falcosecurity/falco/pull/3266.

**Which issue(s) this PR fixes**:

https://github.com/falcosecurity/falco/issues/3243

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by incertum** [comment]
I have the Falco PR up as well. This is ready for review, thanks.

**Comment by darryk10** [comment]
@incertum should we also add cri-dockerd in rules? 
container_entrypoint macro should be one

**Comment by incertum** [comment]
> @incertum should we also add cri-dockerd in rules? container_entrypoint macro should be one

Let's check, it may be just like regular docker (haven't checked the proc lineage) . I believe cri-dockerd is just a wrapper socket on top.

**Comment by incertum** [comment]
@falcosecurity/libs-maintainers any news on this PR or objections? Ty

**Comment by leogr** [comment]
> @falcosecurity/libs-maintainers any news on this PR or objections? Ty

I haven't tested it, anyway no concerns from me.

**Review by LucaGuerra — APPROVED** [review]

**Review by FedeDP — APPROVED** [review]
/approve

**Pull request merged**
