### PR TITLE
fix(scap): Properly reset handle->m_userlist

### PR DESCRIPTION
**Pull request by gnosek**
34e8c2723b554d15981a96b9e07e2dc9d1361367 went a little bit too far with introducing a dedicated variable for the userlist, so in one error path we ended up with a dangling pointer in the handle

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area API-version

> /area build

> /area CI

> /area driver-kmod

> /area driver-bpf

> /area driver-modern-bpf

> /area libscap-engine-bpf

> /area libscap-engine-gvisor

> /area libscap-engine-kmod

> /area libscap-engine-modern-bpf

> /area libscap-engine-nodriver

> /area libscap-engine-noop

> /area libscap-engine-source-plugin

> /area libscap-engine-savefile

> /area libscap-engine-udig

/area libscap

> /area libpman

> /area libsinsp

> /area tests

> /area proposals

**Does this PR require a change in the driver versions?**

> /version driver-API-version-major

> /version driver-API-version-minor

> /version driver-API-version-patch

> /version driver-SCHEMA-version-major

> /version driver-SCHEMA-version-minor

> /version driver-SCHEMA-version-patch

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

Sorry :)

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by gnosek** [comment]
Thanks @Andreagit97 for the help with analyzing the test failures! I guess we got (un)lucky in the original PR run

**Comment by FedeDP** [comment]
Uh that's a classic! Thanks both for spotting this! Hopefully this also fixes Falco issues with the libs bump!

**Review by FedeDP — APPROVED** [review]
/approve

**Review by Andreagit97 — APPROVED** [review]
Thank you for the fix
/approve

**Pull request merged**
