### PR TITLE
Updated protobuf version for s390x

### PR DESCRIPTION
**Pull request by dandotimujahid**
Signed-off-by: Mujahid-Dandoti <Mujahid.Dandoti@ibm.com>

**What type of PR is this?**

/kind bug

**Any specific area of the project related to this PR?**

/area build

**What this PR does / why we need it**:
Updated protobuf version from 3.5.0 to 3.17.3 in protobuf.cmake for s390x.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
build: updated protobuf version from 3.5.0 to 3.17.3 for s390x
```

### CODE REVIEW

**Comment by dandotimujahid** [comment]
@gnosek could you please have a look on my PR.

**Review by leogr — APPROVED** [review]
LGTM

Also, tested on s390x (thanks to @terylt)

/approve

**Review by gnosek — APPROVED** [review]

**Pull request merged**
