### PR TITLE
Scoped target_link_libraries() commands for libsinsp

### PR DESCRIPTION
**Pull request by mprzybylski**
Migrated 'sinsp' CMake target_link_libraies() commands to the scoped PRIVATE / PUBLIC / INTERFACE signature.  This is to minimize the potential for symbol conflicts in applications that use the library.

**What type of PR is this?**

/kind cleanup

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area build
/area libsinsp

> /area tests

> /area proposals

**Does this PR require a change in the driver versions?**

> /version driver-API-version-major

> /version driver-API-version-minor

> /version driver-API-version-patch

> /version driver-SCHEMA-version-major

> /version driver-SCHEMA-version-minor

> /version driver-SCHEMA-version-patch

**What this PR does / why we need it**:

Migrates `libsinsp` `target_link_library()` commands to the scoped `PRIVATE` / `PUBLIC` / `INTERFACE` signature to reduce the likelihood of symbol conflicts in projects that use the library.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by jasondellaluce — APPROVED** [review]
/approve

**Comment by Andreagit97** [comment]
before merging it, I would like to test it on Falco, I will take a look ASAP thank you!
/hold

**Review by Andreagit97 — APPROVED** [review]
/approve

**Pull request merged**
