### PR TITLE
mitigation for falco#1909

### PR DESCRIPTION
**Pull request by leogr**
**What type of PR is this?**

/kind bug
/kind cleanup

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area libsinsp

**What this PR does / why we need it**:

This PR aims to introduce a mitigation for https://github.com/falcosecurity/falco/issues/1909 and related improvements.

**Which issue(s) this PR fixes**:

I can't say this PR definitively fixes any issue.

Fixes #

**Special notes for your reviewer**:

The branch is temporarily based on the `0.7.0` to easily test it with Falco 0.32.2 (a released version affected by the bug).
I'll rebase it on the master branch once I'm confident this works as expected.

Tentatively for 
/milestone 0.9.0

TODOs 
- [x] Initial connection retry (discussed with @alacuku )
- [x] Test the dumping mode (not yet totally sure if [this commit](https://github.com/falcosecurity/libs/commit/7dc84d578f7b1e7884489a225953cdcc6dfc297a) works as expected, discussed with @FedeDP )

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by leogr** [comment]
cc @alacuku

**Review by Andreagit97 — COMMENTED** [review]
LGTM

**Comment by leogr** [comment]
Too late to test this :(
/milestone 0.10.0

**Comment by Andreagit97** [comment]
I would give it an attempt, let's see if during the release process we are enough confident to merge it
/milestone 0.9.0

**Review by Andreagit97 — APPROVED** [review]
/approve

**Review by LucaGuerra — APPROVED** [review]

**Pull request merged**
