### PR TITLE
feature(sinsp): expose container engine list.

### PR DESCRIPTION
**Pull request by Molter73**
**What type of PR is this?**

/kind feature

**Any specific area of the project related to this PR?**

/area libsinsp

**Does this PR require a change in the driver versions?**

**What this PR does / why we need it**:
Exposing the list of container engines allows for more control over what is loaded. This would allow adopters to load custom container engines that might not fit in Falco. An example of such a container engine can be found [here](https://github.com/stackrox/collector/blob/e10bebe79d78d50710b204739f124a10451e4d40/collector/lib/ContainerEngine.h), in our use case we only care about the container ID, so we built a catch all engine and used it in place of the default engines.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by incertum — APPROVED** [review]
/approve

/milestone 0.14.0

**Comment by FedeDP** [comment]
Wouldn't it be better to allow people to override `void sinsp_container_manager::create_engines()` instead?

**Comment by Molter73** [comment]
> Wouldn't it be better to allow people to override `void sinsp_container_manager::create_engines()` instead?
> 
> EDIT: Anyway, i get the change and i am ok with it! Just thinking out loud!

I don't know if I'm right here, but in order to do this, wouldn't I need to turn `sinsp_container_manager` into an interface/abstract class? then the current version needs to become the default implementation that is provided to the inspector and then I also need to make it possible to override the implementation either in a constructor, with a method or both. Seems like a lot of work when all I want is to be able to inject my own container engine into the existing code. Alternatively, we could make `sinsp_container_manager::create_engines()` call an inner method stored in a member and change that, but that just seems messy to me.

**Review by FedeDP — APPROVED** [review]
/approve

**Pull request merged**
