### PR TITLE
cleanup(scap): Remove SunOS support

### PR DESCRIPTION
**Pull request by gnosek**
**What type of PR is this?**

/kind cleanup

**Any specific area of the project related to this PR?**

/area build

/area libscap

**What this PR does / why we need it**:

Remove the remnants of (consumer side) SunOS support

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
cleanup(scap): remove SunOS support
```

### CODE REVIEW

**Review by FedeDP — APPROVED** [review]
LGTM
/approve

**Comment by Andreagit97** [comment]
never noticed them :joy: thank you very much! I will approve it when the CI will be green :)!

**Comment by gnosek** [comment]
The SunOS Ci might complain ;P

**Comment by Andreagit97** [comment]
The CI is dead :roll_eyes:

**Comment by Andreagit97** [comment]
close to trigger the CI

**Comment by gnosek** [comment]
> The CI is dead roll_eyes

long live the CI

**Review by Andreagit97 — APPROVED** [review]
/approve

**Pull request merged**
