### PR TITLE
Ssprod 7548 agent libs 1 lua modernize

### PR DESCRIPTION
**Pull request by jcpittman144**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

/kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area build

> /area driver-kmod

> /area driver-ebpf

> /area libscap

> /area libsinsp

> /area tests

> /area proposals

**What this PR does / why we need it**:
Changes needed to support aarch64 (64-bit ARM) architecture

**Which issue(s) this PR fixes**:
Part of the fix for SSPROD-7548

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by fntlnz** [comment]
Hi @jcpittman144 thanks for your PR. There are a couple of problems in it:

- There is no explanation of what the code does and what problem/bug/feature it solves
- It is definitely too big, please split it in multiple PRs 
- I see signature changes, for example in `scap_open_live_int` this is a breaking change
- Looks like most of the work here is from other people, should they open the PRs instead?

I'm closing for now but please don't take it as non appreciation for your work. Your work is very appreciated !

**Comment by leodido** [comment]
It's barely impossible to review this.

No previous issue with a description of the problem, no previous context, neither intent.

Furthermore, it seems to reference things the community and neither the other maintainers have visibility.

**Comment by fntlnz** [comment]
Also please remove references to your internal ticketing system `SSPROD-7548` - this is something the community has no visibility into.

**Comment by danpopSD** [comment]
please close this PR.

**Pull request closed without merging**
