### PR TITLE
[2/n] new(libscap): platform abstraction support

### PR DESCRIPTION
**Pull request by gnosek**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

/kind cleanup

/kind design

> /kind documentation

> /kind failing-test

> /kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area API-version

> /area build

> /area CI

> /area driver-kmod

> /area driver-bpf

> /area driver-modern-bpf

> /area libscap-engine-bpf

> /area libscap-engine-gvisor

> /area libscap-engine-kmod

> /area libscap-engine-modern-bpf

> /area libscap-engine-nodriver

> /area libscap-engine-noop

> /area libscap-engine-source-plugin

> /area libscap-engine-savefile

> /area libscap-engine-udig

/area libscap

> /area libpman

> /area libsinsp

> /area tests

> /area proposals

**Does this PR require a change in the driver versions?**

> /version driver-API-version-major

> /version driver-API-version-minor

> /version driver-API-version-patch

> /version driver-SCHEMA-version-major

> /version driver-SCHEMA-version-minor

> /version driver-SCHEMA-version-patch

**What this PR does / why we need it**:

This PR fleshes out platform support so that everything promised in #1040 actually happens.

**Special notes for your reviewer**:

This PR contains https://github.com/falcosecurity/libs/pull/1040 inside and will get somewhat smaller when that one gets merged. Still, I'm happy to split the PR further if it makes review easier (in any case, reviewing this commit by commit makes the most sense IMHO)

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by FedeDP — APPROVED** [review]
/approve

**Comment by FedeDP** [comment]
@gnosek i considered this to be out of wip, right?

**Comment by gnosek** [comment]
@FedeDP I'll un`wip` it tomorrow I hope. But please feel free to review it, I don't expect any changes (or maybe one; depending on how https://github.com/falcosecurity/libs/pull/1159 goes)

**Review by FedeDP — APPROVED** [review]
LGTM
/approve

**Review by incertum — APPROVED** [review]
/approve

**Pull request merged**
