### PR TITLE
new(ci:) add driverkit tests for arm64

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind feature

**Any specific area of the project related to this PR?**

/area CI

**Does this PR require a change in the driver versions?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by FedeDP** [comment]
See run: https://github.com/falcosecurity/libs/actions/runs/5442431870/jobs/9897646262.

This will allow us to catch PRs that break drivers on arm64.
/cc @leogr @LucaGuerra

**Review by jasondellaluce — APPROVED** [review]
/approve

**Review by LucaGuerra — APPROVED** [review]

**Pull request merged**
